package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmArwValue generated by hbm2java
 */
@Entity
@Table(name = "adm_arw_value")
public class AdmArwValue implements java.io.Serializable {

	private String customerInfoId;
	private String customerInfoTitle;
	private int arwValue;
	private int dateFlag;
	private Date startDate;
	private Date endDate;
	private Date updateDate;
	private Date createDate;

	public AdmArwValue() {
	}

	public AdmArwValue(String customerInfoId, String customerInfoTitle, int arwValue, int dateFlag, Date startDate,
			Date endDate, Date updateDate, Date createDate) {
		this.customerInfoId = customerInfoId;
		this.customerInfoTitle = customerInfoTitle;
		this.arwValue = arwValue;
		this.dateFlag = dateFlag;
		this.startDate = startDate;
		this.endDate = endDate;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id

	@Column(name = "customer_info_id", unique = true, nullable = false, length = 20)
	public String getCustomerInfoId() {
		return this.customerInfoId;
	}

	public void setCustomerInfoId(String customerInfoId) {
		this.customerInfoId = customerInfoId;
	}

	@Column(name = "customer_info_title", nullable = false, length = 20)
	public String getCustomerInfoTitle() {
		return this.customerInfoTitle;
	}

	public void setCustomerInfoTitle(String customerInfoTitle) {
		this.customerInfoTitle = customerInfoTitle;
	}

	@Column(name = "arw_value", nullable = false)
	public int getArwValue() {
		return this.arwValue;
	}

	public void setArwValue(int arwValue) {
		this.arwValue = arwValue;
	}

	@Column(name = "date_flag", nullable = false)
	public int getDateFlag() {
		return this.dateFlag;
	}

	public void setDateFlag(int dateFlag) {
		this.dateFlag = dateFlag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
