package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AdmAdPool generated by hbm2java
 */
@Entity
@Table(name = "adm_ad_pool")
public class AdmAdPool implements java.io.Serializable {

	private String adPoolSeq;
	private String adPoolName;
	private String diffCompany;
	private int dadCount;
	private Set<AdmTemplateAd> admTemplateAds = new HashSet<AdmTemplateAd>(0);
	private Set<AdmRelateTadDad> admRelateTadDads = new HashSet<AdmRelateTadDad>(0);

	public AdmAdPool() {
	}

	public AdmAdPool(String adPoolSeq, String adPoolName, String diffCompany, int dadCount) {
		this.adPoolSeq = adPoolSeq;
		this.adPoolName = adPoolName;
		this.diffCompany = diffCompany;
		this.dadCount = dadCount;
	}

	public AdmAdPool(String adPoolSeq, String adPoolName, String diffCompany, int dadCount,
			Set<AdmTemplateAd> admTemplateAds, Set<AdmRelateTadDad> admRelateTadDads) {
		this.adPoolSeq = adPoolSeq;
		this.adPoolName = adPoolName;
		this.diffCompany = diffCompany;
		this.dadCount = dadCount;
		this.admTemplateAds = admTemplateAds;
		this.admRelateTadDads = admRelateTadDads;
	}

	@Id

	@Column(name = "ad_pool_seq", unique = true, nullable = false, length = 20)
	public String getAdPoolSeq() {
		return this.adPoolSeq;
	}

	public void setAdPoolSeq(String adPoolSeq) {
		this.adPoolSeq = adPoolSeq;
	}

	@Column(name = "ad_pool_name", nullable = false, length = 20)
	public String getAdPoolName() {
		return this.adPoolName;
	}

	public void setAdPoolName(String adPoolName) {
		this.adPoolName = adPoolName;
	}

	@Column(name = "diff_company", nullable = false, length = 1)
	public String getDiffCompany() {
		return this.diffCompany;
	}

	public void setDiffCompany(String diffCompany) {
		this.diffCompany = diffCompany;
	}

	@Column(name = "dad_count", nullable = false)
	public int getDadCount() {
		return this.dadCount;
	}

	public void setDadCount(int dadCount) {
		this.dadCount = dadCount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admAdPool")
	public Set<AdmTemplateAd> getAdmTemplateAds() {
		return this.admTemplateAds;
	}

	public void setAdmTemplateAds(Set<AdmTemplateAd> admTemplateAds) {
		this.admTemplateAds = admTemplateAds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admAdPool")
	public Set<AdmRelateTadDad> getAdmRelateTadDads() {
		return this.admRelateTadDads;
	}

	public void setAdmRelateTadDads(Set<AdmRelateTadDad> admRelateTadDads) {
		this.admRelateTadDads = admRelateTadDads;
	}

}
