package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmBonusSet generated by hbm2java
 */
@Entity
@Table(name = "adm_bonus_set")
public class AdmBonusSet implements java.io.Serializable {

	private Integer id;
	private Date startDate;
	private float pfpPercent;
	private float pfbPercent;
	private String status;
	private String note;
	private Date createDate;
	private Date updateDate;

	public AdmBonusSet() {
	}

	public AdmBonusSet(Date startDate, float pfpPercent, float pfbPercent, String status, Date createDate,
			Date updateDate) {
		this.startDate = startDate;
		this.pfpPercent = pfpPercent;
		this.pfbPercent = pfbPercent;
		this.status = status;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public AdmBonusSet(Date startDate, float pfpPercent, float pfbPercent, String status, String note, Date createDate,
			Date updateDate) {
		this.startDate = startDate;
		this.pfpPercent = pfpPercent;
		this.pfbPercent = pfbPercent;
		this.status = status;
		this.note = note;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "pfp_percent", nullable = false, precision = 5)
	public float getPfpPercent() {
		return this.pfpPercent;
	}

	public void setPfpPercent(float pfpPercent) {
		this.pfpPercent = pfpPercent;
	}

	@Column(name = "pfb_percent", nullable = false, precision = 5)
	public float getPfbPercent() {
		return this.pfbPercent;
	}

	public void setPfbPercent(float pfbPercent) {
		this.pfbPercent = pfbPercent;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "note", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
