package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmBonusDetailReport generated by hbm2java
 */
@Entity
@Table(name = "adm_bonus_detail_report")
public class AdmBonusDetailReport implements java.io.Serializable {

	private Integer id;
	private Date reportDate;
	private String detailItem;
	private String itemName;
	private String incomeExpense;
	private float save;
	private float free;
	private float postpaid;
	private float total;
	private Date createDate;

	public AdmBonusDetailReport() {
	}

	public AdmBonusDetailReport(Date reportDate, String detailItem, String itemName, String incomeExpense, float save,
			float free, float postpaid, float total, Date createDate) {
		this.reportDate = reportDate;
		this.detailItem = detailItem;
		this.itemName = itemName;
		this.incomeExpense = incomeExpense;
		this.save = save;
		this.free = free;
		this.postpaid = postpaid;
		this.total = total;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "report_date", nullable = false, length = 10)
	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "detail_item", nullable = false, length = 2)
	public String getDetailItem() {
		return this.detailItem;
	}

	public void setDetailItem(String detailItem) {
		this.detailItem = detailItem;
	}

	@Column(name = "item_name", nullable = false, length = 100)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "income_expense", nullable = false, length = 1)
	public String getIncomeExpense() {
		return this.incomeExpense;
	}

	public void setIncomeExpense(String incomeExpense) {
		this.incomeExpense = incomeExpense;
	}

	@Column(name = "save", nullable = false, precision = 10)
	public float getSave() {
		return this.save;
	}

	public void setSave(float save) {
		this.save = save;
	}

	@Column(name = "free", nullable = false, precision = 10)
	public float getFree() {
		return this.free;
	}

	public void setFree(float free) {
		this.free = free;
	}

	@Column(name = "postpaid", nullable = false, precision = 10)
	public float getPostpaid() {
		return this.postpaid;
	}

	public void setPostpaid(float postpaid) {
		this.postpaid = postpaid;
	}

	@Column(name = "total", nullable = false, precision = 10)
	public float getTotal() {
		return this.total;
	}

	public void setTotal(float total) {
		this.total = total;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
