package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmBonusBillReport generated by hbm2java
 */
@Entity
@Table(name = "adm_bonus_bill_report")
public class AdmBonusBillReport implements java.io.Serializable {

	private Integer id;
	private Date reportDate;
	private Float pchomePercent;
	private float sysClkPrice;
	private float income;
	private float expense;
	private float total;
	private Date createDate;

	public AdmBonusBillReport() {
	}

	public AdmBonusBillReport(Date reportDate, float sysClkPrice, float income, float expense, float total,
			Date createDate) {
		this.reportDate = reportDate;
		this.sysClkPrice = sysClkPrice;
		this.income = income;
		this.expense = expense;
		this.total = total;
		this.createDate = createDate;
	}

	public AdmBonusBillReport(Date reportDate, Float pchomePercent, float sysClkPrice, float income, float expense,
			float total, Date createDate) {
		this.reportDate = reportDate;
		this.pchomePercent = pchomePercent;
		this.sysClkPrice = sysClkPrice;
		this.income = income;
		this.expense = expense;
		this.total = total;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "report_date", nullable = false, length = 10)
	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "pchome_percent", precision = 10)
	public Float getPchomePercent() {
		return this.pchomePercent;
	}

	public void setPchomePercent(Float pchomePercent) {
		this.pchomePercent = pchomePercent;
	}

	@Column(name = "sys_clk_price", nullable = false, precision = 10)
	public float getSysClkPrice() {
		return this.sysClkPrice;
	}

	public void setSysClkPrice(float sysClkPrice) {
		this.sysClkPrice = sysClkPrice;
	}

	@Column(name = "income", nullable = false, precision = 10)
	public float getIncome() {
		return this.income;
	}

	public void setIncome(float income) {
		this.income = income;
	}

	@Column(name = "expense", nullable = false, precision = 10)
	public float getExpense() {
		return this.expense;
	}

	public void setExpense(float expense) {
		this.expense = expense;
	}

	@Column(name = "total", nullable = false, precision = 10)
	public float getTotal() {
		return this.total;
	}

	public void setTotal(float total) {
		this.total = total;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
