package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmBrandCorrespond generated by hbm2java
 */
@Entity
@Table(name = "adm_brand_correspond")
public class AdmBrandCorrespond implements java.io.Serializable {

	private Integer id;
	private String brandEng;
	private String brandCh;
	private Date updateDate;
	private Date createDate;

	public AdmBrandCorrespond() {
	}

	public AdmBrandCorrespond(String brandEng, String brandCh, Date updateDate, Date createDate) {
		this.brandEng = brandEng;
		this.brandCh = brandCh;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "brand_eng", nullable = false, length = 30)
	public String getBrandEng() {
		return this.brandEng;
	}

	public void setBrandEng(String brandEng) {
		this.brandEng = brandEng;
	}

	@Column(name = "brand_ch", nullable = false, length = 30)
	public String getBrandCh() {
		return this.brandCh;
	}

	public void setBrandCh(String brandCh) {
		this.brandCh = brandCh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
