package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AdmDefineAdType generated by hbm2java
 */
@Entity
@Table(name = "adm_define_ad_type")
public class AdmDefineAdType implements java.io.Serializable {

	private Integer defineAdTypeId;
	private String defineAdTypeName;
	private Set<AdmDefineAd> admDefineAds = new HashSet<AdmDefineAd>(0);

	public AdmDefineAdType() {
	}

	public AdmDefineAdType(String defineAdTypeName) {
		this.defineAdTypeName = defineAdTypeName;
	}

	public AdmDefineAdType(String defineAdTypeName, Set<AdmDefineAd> admDefineAds) {
		this.defineAdTypeName = defineAdTypeName;
		this.admDefineAds = admDefineAds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "define_ad_type_id", unique = true, nullable = false)
	public Integer getDefineAdTypeId() {
		return this.defineAdTypeId;
	}

	public void setDefineAdTypeId(Integer defineAdTypeId) {
		this.defineAdTypeId = defineAdTypeId;
	}

	@Column(name = "define_ad_type_name", nullable = false, length = 50)
	public String getDefineAdTypeName() {
		return this.defineAdTypeName;
	}

	public void setDefineAdTypeName(String defineAdTypeName) {
		this.defineAdTypeName = defineAdTypeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admDefineAdType")
	public Set<AdmDefineAd> getAdmDefineAds() {
		return this.admDefineAds;
	}

	public void setAdmDefineAds(Set<AdmDefineAd> admDefineAds) {
		this.admDefineAds = admDefineAds;
	}

}
