package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AdmDefineAd generated by hbm2java
 */
@Entity
@Table(name = "adm_define_ad")
public class AdmDefineAd implements java.io.Serializable {

	private String defineAdSeq;
	private AdmDefineAdType admDefineAdType;
	private String defineAdId;
	private String defineAdName;
	private String defineAdWidth;
	private String defineAdHeight;
	private String defineAdFile;
	private String adPoolSeq;
	private Set<AdmRelateTadDad> admRelateTadDads = new HashSet<AdmRelateTadDad>(0);

	public AdmDefineAd() {
	}

	public AdmDefineAd(String defineAdSeq, AdmDefineAdType admDefineAdType, String defineAdId, String defineAdName,
			String defineAdWidth, String defineAdHeight, String defineAdFile) {
		this.defineAdSeq = defineAdSeq;
		this.admDefineAdType = admDefineAdType;
		this.defineAdId = defineAdId;
		this.defineAdName = defineAdName;
		this.defineAdWidth = defineAdWidth;
		this.defineAdHeight = defineAdHeight;
		this.defineAdFile = defineAdFile;
	}

	public AdmDefineAd(String defineAdSeq, AdmDefineAdType admDefineAdType, String defineAdId, String defineAdName,
			String defineAdWidth, String defineAdHeight, String defineAdFile, String adPoolSeq,
			Set<AdmRelateTadDad> admRelateTadDads) {
		this.defineAdSeq = defineAdSeq;
		this.admDefineAdType = admDefineAdType;
		this.defineAdId = defineAdId;
		this.defineAdName = defineAdName;
		this.defineAdWidth = defineAdWidth;
		this.defineAdHeight = defineAdHeight;
		this.defineAdFile = defineAdFile;
		this.adPoolSeq = adPoolSeq;
		this.admRelateTadDads = admRelateTadDads;
	}

	@Id

	@Column(name = "define_ad_seq", unique = true, nullable = false, length = 20)
	public String getDefineAdSeq() {
		return this.defineAdSeq;
	}

	public void setDefineAdSeq(String defineAdSeq) {
		this.defineAdSeq = defineAdSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "define_ad_type", nullable = false)
	public AdmDefineAdType getAdmDefineAdType() {
		return this.admDefineAdType;
	}

	public void setAdmDefineAdType(AdmDefineAdType admDefineAdType) {
		this.admDefineAdType = admDefineAdType;
	}

	@Column(name = "define_ad_id", nullable = false, length = 30)
	public String getDefineAdId() {
		return this.defineAdId;
	}

	public void setDefineAdId(String defineAdId) {
		this.defineAdId = defineAdId;
	}

	@Column(name = "define_ad_name", nullable = false, length = 50)
	public String getDefineAdName() {
		return this.defineAdName;
	}

	public void setDefineAdName(String defineAdName) {
		this.defineAdName = defineAdName;
	}

	@Column(name = "define_ad_width", nullable = false, length = 4)
	public String getDefineAdWidth() {
		return this.defineAdWidth;
	}

	public void setDefineAdWidth(String defineAdWidth) {
		this.defineAdWidth = defineAdWidth;
	}

	@Column(name = "define_ad_height", nullable = false, length = 4)
	public String getDefineAdHeight() {
		return this.defineAdHeight;
	}

	public void setDefineAdHeight(String defineAdHeight) {
		this.defineAdHeight = defineAdHeight;
	}

	@Column(name = "define_ad_file", nullable = false, length = 500)
	public String getDefineAdFile() {
		return this.defineAdFile;
	}

	public void setDefineAdFile(String defineAdFile) {
		this.defineAdFile = defineAdFile;
	}

	@Column(name = "ad_pool_seq", length = 20)
	public String getAdPoolSeq() {
		return this.adPoolSeq;
	}

	public void setAdPoolSeq(String adPoolSeq) {
		this.adPoolSeq = adPoolSeq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admDefineAd")
	public Set<AdmRelateTadDad> getAdmRelateTadDads() {
		return this.admRelateTadDads;
	}

	public void setAdmRelateTadDads(Set<AdmRelateTadDad> admRelateTadDads) {
		this.admRelateTadDads = admRelateTadDads;
	}

}
