package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmPfbxBlockUrl generated by hbm2java
 */
@Entity
@Table(name = "adm_pfbx_block_url")
public class AdmPfbxBlockUrl implements java.io.Serializable {

	private Integer id;
	private PfbxCustomerInfo pfbxCustomerInfo;
	private String blockUrl;
	private String blockNote;
	private Date updateDate;
	private Date createDate;

	public AdmPfbxBlockUrl() {
	}

	public AdmPfbxBlockUrl(PfbxCustomerInfo pfbxCustomerInfo, Date updateDate, Date createDate) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public AdmPfbxBlockUrl(PfbxCustomerInfo pfbxCustomerInfo, String blockUrl, String blockNote, Date updateDate,
			Date createDate) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.blockUrl = blockUrl;
		this.blockNote = blockNote;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfb_id", nullable = false)
	public PfbxCustomerInfo getPfbxCustomerInfo() {
		return this.pfbxCustomerInfo;
	}

	public void setPfbxCustomerInfo(PfbxCustomerInfo pfbxCustomerInfo) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
	}

	@Column(name = "block_url", length = 2000)
	public String getBlockUrl() {
		return this.blockUrl;
	}

	public void setBlockUrl(String blockUrl) {
		this.blockUrl = blockUrl;
	}

	@Column(name = "block_note", length = 200)
	public String getBlockNote() {
		return this.blockNote;
	}

	public void setBlockNote(String blockNote) {
		this.blockNote = blockNote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
