package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmPortalBonusReport generated by hbm2java
 */
@Entity
@Table(name = "adm_portal_bonus_report")
public class AdmPortalBonusReport implements java.io.Serializable {

	private Integer reportSeq;
	private String pfdCustomerInfoId;
	private Date adPvclkDate;
	private float adValidPrice;
	private int pfpClientCount;
	private float pfdBonus;
	private float portalPfbBonus;
	private float portalOperatingIncome;
	private Date updateDate;
	private Date createDate;

	public AdmPortalBonusReport() {
	}

	public AdmPortalBonusReport(Date adPvclkDate, float adValidPrice, int pfpClientCount, float pfdBonus,
			float portalPfbBonus, float portalOperatingIncome, Date updateDate, Date createDate) {
		this.adPvclkDate = adPvclkDate;
		this.adValidPrice = adValidPrice;
		this.pfpClientCount = pfpClientCount;
		this.pfdBonus = pfdBonus;
		this.portalPfbBonus = portalPfbBonus;
		this.portalOperatingIncome = portalOperatingIncome;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public AdmPortalBonusReport(String pfdCustomerInfoId, Date adPvclkDate, float adValidPrice, int pfpClientCount,
			float pfdBonus, float portalPfbBonus, float portalOperatingIncome, Date updateDate, Date createDate) {
		this.pfdCustomerInfoId = pfdCustomerInfoId;
		this.adPvclkDate = adPvclkDate;
		this.adValidPrice = adValidPrice;
		this.pfpClientCount = pfpClientCount;
		this.pfdBonus = pfdBonus;
		this.portalPfbBonus = portalPfbBonus;
		this.portalOperatingIncome = portalOperatingIncome;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "report_seq", unique = true, nullable = false)
	public Integer getReportSeq() {
		return this.reportSeq;
	}

	public void setReportSeq(Integer reportSeq) {
		this.reportSeq = reportSeq;
	}

	@Column(name = "pfd_customer_info_id", length = 20)
	public String getPfdCustomerInfoId() {
		return this.pfdCustomerInfoId;
	}

	public void setPfdCustomerInfoId(String pfdCustomerInfoId) {
		this.pfdCustomerInfoId = pfdCustomerInfoId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ad_pvclk_date", nullable = false, length = 10)
	public Date getAdPvclkDate() {
		return this.adPvclkDate;
	}

	public void setAdPvclkDate(Date adPvclkDate) {
		this.adPvclkDate = adPvclkDate;
	}

	@Column(name = "ad_valid_price", nullable = false, precision = 10)
	public float getAdValidPrice() {
		return this.adValidPrice;
	}

	public void setAdValidPrice(float adValidPrice) {
		this.adValidPrice = adValidPrice;
	}

	@Column(name = "pfp_client_count", nullable = false)
	public int getPfpClientCount() {
		return this.pfpClientCount;
	}

	public void setPfpClientCount(int pfpClientCount) {
		this.pfpClientCount = pfpClientCount;
	}

	@Column(name = "pfd_bonus", nullable = false, precision = 10)
	public float getPfdBonus() {
		return this.pfdBonus;
	}

	public void setPfdBonus(float pfdBonus) {
		this.pfdBonus = pfdBonus;
	}

	@Column(name = "portal_pfb_bonus", nullable = false, precision = 10)
	public float getPortalPfbBonus() {
		return this.portalPfbBonus;
	}

	public void setPortalPfbBonus(float portalPfbBonus) {
		this.portalPfbBonus = portalPfbBonus;
	}

	@Column(name = "portal_operating_income", nullable = false, precision = 10)
	public float getPortalOperatingIncome() {
		return this.portalOperatingIncome;
	}

	public void setPortalOperatingIncome(float portalOperatingIncome) {
		this.portalOperatingIncome = portalOperatingIncome;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
