package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmRetrieveRecord generated by hbm2java
 */
@Entity
@Table(name = "adm_retrieve_record")
public class AdmRetrieveRecord implements java.io.Serializable {

	private Integer recordId;
	private String actionId;
	private String recordType;
	private String pfpCustomerInfoId;
	private Date giftDate;
	private int giftMoney;
	private int spendMoney;
	private int retrieveMoney;
	private Date inviledDate;
	private Date recordDate;
	private Date createDate;

	public AdmRetrieveRecord() {
	}

	public AdmRetrieveRecord(String actionId, String recordType, String pfpCustomerInfoId, Date giftDate, int giftMoney,
			int spendMoney, int retrieveMoney, Date inviledDate, Date recordDate, Date createDate) {
		this.actionId = actionId;
		this.recordType = recordType;
		this.pfpCustomerInfoId = pfpCustomerInfoId;
		this.giftDate = giftDate;
		this.giftMoney = giftMoney;
		this.spendMoney = spendMoney;
		this.retrieveMoney = retrieveMoney;
		this.inviledDate = inviledDate;
		this.recordDate = recordDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "record_id", unique = true, nullable = false)
	public Integer getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	@Column(name = "action_id", nullable = false, length = 20)
	public String getActionId() {
		return this.actionId;
	}

	public void setActionId(String actionId) {
		this.actionId = actionId;
	}

	@Column(name = "record_type", nullable = false, length = 1)
	public String getRecordType() {
		return this.recordType;
	}

	public void setRecordType(String recordType) {
		this.recordType = recordType;
	}

	@Column(name = "pfp_customer_info_id", nullable = false, length = 20)
	public String getPfpCustomerInfoId() {
		return this.pfpCustomerInfoId;
	}

	public void setPfpCustomerInfoId(String pfpCustomerInfoId) {
		this.pfpCustomerInfoId = pfpCustomerInfoId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "gift_date", nullable = false, length = 19)
	public Date getGiftDate() {
		return this.giftDate;
	}

	public void setGiftDate(Date giftDate) {
		this.giftDate = giftDate;
	}

	@Column(name = "gift_money", nullable = false)
	public int getGiftMoney() {
		return this.giftMoney;
	}

	public void setGiftMoney(int giftMoney) {
		this.giftMoney = giftMoney;
	}

	@Column(name = "spend_money", nullable = false)
	public int getSpendMoney() {
		return this.spendMoney;
	}

	public void setSpendMoney(int spendMoney) {
		this.spendMoney = spendMoney;
	}

	@Column(name = "retrieve_money", nullable = false)
	public int getRetrieveMoney() {
		return this.retrieveMoney;
	}

	public void setRetrieveMoney(int retrieveMoney) {
		this.retrieveMoney = retrieveMoney;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "inviled_date", nullable = false, length = 19)
	public Date getInviledDate() {
		return this.inviledDate;
	}

	public void setInviledDate(Date inviledDate) {
		this.inviledDate = inviledDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "record_date", nullable = false, length = 10)
	public Date getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(Date recordDate) {
		this.recordDate = recordDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
