package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AdmRelateTproTad generated by hbm2java
 */
@Entity
@Table(name = "adm_relate_tpro_tad")
public class AdmRelateTproTad implements java.io.Serializable {

	private String relateTproTadSeq;
	private AdmTemplateProduct admTemplateProduct;
	private AdmTemplateAd admTemplateAd;
	private String templateProductSeqSub;
	private int templateAdOrder;

	public AdmRelateTproTad() {
	}

	public AdmRelateTproTad(String relateTproTadSeq, AdmTemplateProduct admTemplateProduct, int templateAdOrder) {
		this.relateTproTadSeq = relateTproTadSeq;
		this.admTemplateProduct = admTemplateProduct;
		this.templateAdOrder = templateAdOrder;
	}

	public AdmRelateTproTad(String relateTproTadSeq, AdmTemplateProduct admTemplateProduct, AdmTemplateAd admTemplateAd,
			String templateProductSeqSub, int templateAdOrder) {
		this.relateTproTadSeq = relateTproTadSeq;
		this.admTemplateProduct = admTemplateProduct;
		this.admTemplateAd = admTemplateAd;
		this.templateProductSeqSub = templateProductSeqSub;
		this.templateAdOrder = templateAdOrder;
	}

	@Id

	@Column(name = "relate_tpro_tad_seq", unique = true, nullable = false, length = 20)
	public String getRelateTproTadSeq() {
		return this.relateTproTadSeq;
	}

	public void setRelateTproTadSeq(String relateTproTadSeq) {
		this.relateTproTadSeq = relateTproTadSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "template_product_seq", nullable = false)
	public AdmTemplateProduct getAdmTemplateProduct() {
		return this.admTemplateProduct;
	}

	public void setAdmTemplateProduct(AdmTemplateProduct admTemplateProduct) {
		this.admTemplateProduct = admTemplateProduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "template_ad_seq")
	public AdmTemplateAd getAdmTemplateAd() {
		return this.admTemplateAd;
	}

	public void setAdmTemplateAd(AdmTemplateAd admTemplateAd) {
		this.admTemplateAd = admTemplateAd;
	}

	@Column(name = "template_product_seq_sub", length = 20)
	public String getTemplateProductSeqSub() {
		return this.templateProductSeqSub;
	}

	public void setTemplateProductSeqSub(String templateProductSeqSub) {
		this.templateProductSeqSub = templateProductSeqSub;
	}

	@Column(name = "template_ad_order", nullable = false)
	public int getTemplateAdOrder() {
		return this.templateAdOrder;
	}

	public void setTemplateAdOrder(int templateAdOrder) {
		this.templateAdOrder = templateAdOrder;
	}

}
