package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmTransLoss generated by hbm2java
 */
@Entity
@Table(name = "adm_trans_loss")
public class AdmTransLoss implements java.io.Serializable {

	private Integer id;
	private String customerInfoId;
	private String payType;
	private float lossCost;
	private Date transDate;
	private Date updateDate;
	private Date createDate;

	public AdmTransLoss() {
	}

	public AdmTransLoss(String customerInfoId, String payType, float lossCost, Date transDate, Date updateDate,
			Date createDate) {
		this.customerInfoId = customerInfoId;
		this.payType = payType;
		this.lossCost = lossCost;
		this.transDate = transDate;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "customer_info_id", nullable = false, length = 20)
	public String getCustomerInfoId() {
		return this.customerInfoId;
	}

	public void setCustomerInfoId(String customerInfoId) {
		this.customerInfoId = customerInfoId;
	}

	@Column(name = "pay_type", nullable = false, length = 1)
	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	@Column(name = "loss_cost", nullable = false, precision = 10)
	public float getLossCost() {
		return this.lossCost;
	}

	public void setLossCost(float lossCost) {
		this.lossCost = lossCost;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "trans_date", nullable = false, length = 10)
	public Date getTransDate() {
		return this.transDate;
	}

	public void setTransDate(Date transDate) {
		this.transDate = transDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
