package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AdmTemplateAd generated by hbm2java
 */
@Entity
@Table(name = "adm_template_ad")
public class AdmTemplateAd implements java.io.Serializable {

	private String templateAdSeq;
	private AdmAdPool admAdPool;
	private String templateAdName;
	private String templateAdWidth;
	private String templateAdHeight;
	private int admTemplateAdType;
	private String adTemplateProductXType;
	private int adType;
	private String templateAdFile;
	private String auto;
	private Integer defineAdCount;
	private Set<AdmRelateTadDad> admRelateTadDads = new HashSet<AdmRelateTadDad>(0);
	private Set<AdmRelateTproTad> admRelateTproTads = new HashSet<AdmRelateTproTad>(0);

	public AdmTemplateAd() {
	}

	public AdmTemplateAd(String templateAdSeq, AdmAdPool admAdPool, String templateAdName, String templateAdWidth,
			String templateAdHeight, int admTemplateAdType, String adTemplateProductXType, int adType,
			String templateAdFile, String auto) {
		this.templateAdSeq = templateAdSeq;
		this.admAdPool = admAdPool;
		this.templateAdName = templateAdName;
		this.templateAdWidth = templateAdWidth;
		this.templateAdHeight = templateAdHeight;
		this.admTemplateAdType = admTemplateAdType;
		this.adTemplateProductXType = adTemplateProductXType;
		this.adType = adType;
		this.templateAdFile = templateAdFile;
		this.auto = auto;
	}

	public AdmTemplateAd(String templateAdSeq, AdmAdPool admAdPool, String templateAdName, String templateAdWidth,
			String templateAdHeight, int admTemplateAdType, String adTemplateProductXType, int adType,
			String templateAdFile, String auto, Integer defineAdCount, Set<AdmRelateTadDad> admRelateTadDads,
			Set<AdmRelateTproTad> admRelateTproTads) {
		this.templateAdSeq = templateAdSeq;
		this.admAdPool = admAdPool;
		this.templateAdName = templateAdName;
		this.templateAdWidth = templateAdWidth;
		this.templateAdHeight = templateAdHeight;
		this.admTemplateAdType = admTemplateAdType;
		this.adTemplateProductXType = adTemplateProductXType;
		this.adType = adType;
		this.templateAdFile = templateAdFile;
		this.auto = auto;
		this.defineAdCount = defineAdCount;
		this.admRelateTadDads = admRelateTadDads;
		this.admRelateTproTads = admRelateTproTads;
	}

	@Id

	@Column(name = "template_ad_seq", unique = true, nullable = false, length = 50)
	public String getTemplateAdSeq() {
		return this.templateAdSeq;
	}

	public void setTemplateAdSeq(String templateAdSeq) {
		this.templateAdSeq = templateAdSeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ad_pool_seq", nullable = false)
	public AdmAdPool getAdmAdPool() {
		return this.admAdPool;
	}

	public void setAdmAdPool(AdmAdPool admAdPool) {
		this.admAdPool = admAdPool;
	}

	@Column(name = "template_ad_name", nullable = false, length = 50)
	public String getTemplateAdName() {
		return this.templateAdName;
	}

	public void setTemplateAdName(String templateAdName) {
		this.templateAdName = templateAdName;
	}

	@Column(name = "template_ad_width", nullable = false, length = 4)
	public String getTemplateAdWidth() {
		return this.templateAdWidth;
	}

	public void setTemplateAdWidth(String templateAdWidth) {
		this.templateAdWidth = templateAdWidth;
	}

	@Column(name = "template_ad_height", nullable = false, length = 4)
	public String getTemplateAdHeight() {
		return this.templateAdHeight;
	}

	public void setTemplateAdHeight(String templateAdHeight) {
		this.templateAdHeight = templateAdHeight;
	}

	@Column(name = "adm_template_ad_type", nullable = false)
	public int getAdmTemplateAdType() {
		return this.admTemplateAdType;
	}

	public void setAdmTemplateAdType(int admTemplateAdType) {
		this.admTemplateAdType = admTemplateAdType;
	}

	@Column(name = "ad_template_product_x_type", nullable = false, length = 10)
	public String getAdTemplateProductXType() {
		return this.adTemplateProductXType;
	}

	public void setAdTemplateProductXType(String adTemplateProductXType) {
		this.adTemplateProductXType = adTemplateProductXType;
	}

	@Column(name = "ad_type", nullable = false)
	public int getAdType() {
		return this.adType;
	}

	public void setAdType(int adType) {
		this.adType = adType;
	}

	@Column(name = "template_ad_file", nullable = false, length = 500)
	public String getTemplateAdFile() {
		return this.templateAdFile;
	}

	public void setTemplateAdFile(String templateAdFile) {
		this.templateAdFile = templateAdFile;
	}

	@Column(name = "auto", nullable = false, length = 1)
	public String getAuto() {
		return this.auto;
	}

	public void setAuto(String auto) {
		this.auto = auto;
	}

	@Column(name = "define_ad_count")
	public Integer getDefineAdCount() {
		return this.defineAdCount;
	}

	public void setDefineAdCount(Integer defineAdCount) {
		this.defineAdCount = defineAdCount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admTemplateAd")
	public Set<AdmRelateTadDad> getAdmRelateTadDads() {
		return this.admRelateTadDads;
	}

	public void setAdmRelateTadDads(Set<AdmRelateTadDad> admRelateTadDads) {
		this.admRelateTadDads = admRelateTadDads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admTemplateAd")
	public Set<AdmRelateTproTad> getAdmRelateTproTads() {
		return this.admRelateTproTads;
	}

	public void setAdmRelateTproTads(Set<AdmRelateTproTad> admRelateTproTads) {
		this.admRelateTproTads = admRelateTproTads;
	}

}
