package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DmpAdclassReport generated by hbm2java
 */
@Entity
@Table(name = "dmp_adclass_report")
public class DmpAdclassReport implements java.io.Serializable {

	private Integer id;
	private String adclass;
	private int counter;
	private String recordDate;
	private Date updateDate;
	private Date createDate;

	public DmpAdclassReport() {
	}

	public DmpAdclassReport(String adclass, int counter, String recordDate, Date updateDate, Date createDate) {
		this.adclass = adclass;
		this.counter = counter;
		this.recordDate = recordDate;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "adclass", nullable = false, length = 50)
	public String getAdclass() {
		return this.adclass;
	}

	public void setAdclass(String adclass) {
		this.adclass = adclass;
	}

	@Column(name = "counter", nullable = false)
	public int getCounter() {
		return this.counter;
	}

	public void setCounter(int counter) {
		this.counter = counter;
	}

	@Column(name = "record_date", nullable = false, length = 10)
	public String getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(String recordDate) {
		this.recordDate = recordDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
