package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DmpHitReport generated by hbm2java
 */
@Entity
@Table(name = "dmp_hit_report")
public class DmpHitReport implements java.io.Serializable {

	private Integer id;
	private int totalPv;
	private int hitDmpMemid;
	private int hitDmpUuid;
	private int hitAdMemid;
	private int hitAdUuid;
	private int hitBehavior1;
	private int hitBehavior2;
	private String recordDate;
	private Date updateDate;
	private Date createDate;

	public DmpHitReport() {
	}

	public DmpHitReport(int totalPv, int hitDmpMemid, int hitDmpUuid, int hitAdMemid, int hitAdUuid, int hitBehavior1,
			int hitBehavior2, String recordDate, Date updateDate, Date createDate) {
		this.totalPv = totalPv;
		this.hitDmpMemid = hitDmpMemid;
		this.hitDmpUuid = hitDmpUuid;
		this.hitAdMemid = hitAdMemid;
		this.hitAdUuid = hitAdUuid;
		this.hitBehavior1 = hitBehavior1;
		this.hitBehavior2 = hitBehavior2;
		this.recordDate = recordDate;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "total_pv", nullable = false)
	public int getTotalPv() {
		return this.totalPv;
	}

	public void setTotalPv(int totalPv) {
		this.totalPv = totalPv;
	}

	@Column(name = "hit_dmp_memid", nullable = false)
	public int getHitDmpMemid() {
		return this.hitDmpMemid;
	}

	public void setHitDmpMemid(int hitDmpMemid) {
		this.hitDmpMemid = hitDmpMemid;
	}

	@Column(name = "hit_dmp_uuid", nullable = false)
	public int getHitDmpUuid() {
		return this.hitDmpUuid;
	}

	public void setHitDmpUuid(int hitDmpUuid) {
		this.hitDmpUuid = hitDmpUuid;
	}

	@Column(name = "hit_ad_memid", nullable = false)
	public int getHitAdMemid() {
		return this.hitAdMemid;
	}

	public void setHitAdMemid(int hitAdMemid) {
		this.hitAdMemid = hitAdMemid;
	}

	@Column(name = "hit_ad_uuid", nullable = false)
	public int getHitAdUuid() {
		return this.hitAdUuid;
	}

	public void setHitAdUuid(int hitAdUuid) {
		this.hitAdUuid = hitAdUuid;
	}

	@Column(name = "hit_behavior1", nullable = false)
	public int getHitBehavior1() {
		return this.hitBehavior1;
	}

	public void setHitBehavior1(int hitBehavior1) {
		this.hitBehavior1 = hitBehavior1;
	}

	@Column(name = "hit_behavior2", nullable = false)
	public int getHitBehavior2() {
		return this.hitBehavior2;
	}

	public void setHitBehavior2(int hitBehavior2) {
		this.hitBehavior2 = hitBehavior2;
	}

	@Column(name = "record_date", nullable = false, length = 10)
	public String getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(String recordDate) {
		this.recordDate = recordDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
