package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PfbAdmAccount generated by hbm2java
 */
@Entity
@Table(name = "pfb_adm_account", uniqueConstraints = @UniqueConstraint(columnNames = "account"))
public class PfbAdmAccount implements java.io.Serializable {

	private Integer id;
	private String account;
	private String password;
	private String name;
	private String email;
	private String tel;
	private int gid;
	private String unit;
	private String weight;
	private boolean status;

	public PfbAdmAccount() {
	}

	public PfbAdmAccount(String account, String password, String name, String email, int gid, String unit,
			String weight, boolean status) {
		this.account = account;
		this.password = password;
		this.name = name;
		this.email = email;
		this.gid = gid;
		this.unit = unit;
		this.weight = weight;
		this.status = status;
	}

	public PfbAdmAccount(String account, String password, String name, String email, String tel, int gid, String unit,
			String weight, boolean status) {
		this.account = account;
		this.password = password;
		this.name = name;
		this.email = email;
		this.tel = tel;
		this.gid = gid;
		this.unit = unit;
		this.weight = weight;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "account", unique = true, nullable = false, length = 30)
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "tel", length = 4)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "gid", nullable = false)
	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	@Column(name = "unit", nullable = false, length = 50)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "weight", nullable = false, length = 65535)
	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
