package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PfbForegroundAccountNo generated by hbm2java
 */
@Entity
@Table(name = "pfb_foreground_account_no")
public class PfbForegroundAccountNo implements java.io.Serializable {

	private PfbForegroundAccountNoId id;
	private String accountNo;

	public PfbForegroundAccountNo() {
	}

	public PfbForegroundAccountNo(PfbForegroundAccountNoId id, String accountNo) {
		this.id = id;
		this.accountNo = accountNo;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "year", column = @Column(name = "year", nullable = false, length = 4)),
			@AttributeOverride(name = "season", column = @Column(name = "season", nullable = false, length = 2)),
			@AttributeOverride(name = "month", column = @Column(name = "month", nullable = false, length = 2)),
			@AttributeOverride(name = "day", column = @Column(name = "day", nullable = false, length = 2)),
			@AttributeOverride(name = "hash", column = @Column(name = "hash", nullable = false, length = 2)) })
	public PfbForegroundAccountNoId getId() {
		return this.id;
	}

	public void setId(PfbForegroundAccountNoId id) {
		this.id = id;
	}

	@Column(name = "account_no", nullable = false, length = 20)
	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

}
