package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PfbForegroundWeight generated by hbm2java
 */
@Entity
@Table(name = "pfb_foreground_weight")
public class PfbForegroundWeight implements java.io.Serializable {

	private Integer id;
	private String class_;
	private String subclass;
	private String search;
	private String add;
	private String edit;
	private String delete;

	public PfbForegroundWeight() {
	}

	public PfbForegroundWeight(String class_, String subclass, String search, String add, String edit, String delete) {
		this.class_ = class_;
		this.subclass = subclass;
		this.search = search;
		this.add = add;
		this.edit = edit;
		this.delete = delete;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "class", nullable = false, length = 20)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "subclass", nullable = false, length = 20)
	public String getSubclass() {
		return this.subclass;
	}

	public void setSubclass(String subclass) {
		this.subclass = subclass;
	}

	@Column(name = "search", nullable = false, length = 100)
	public String getSearch() {
		return this.search;
	}

	public void setSearch(String search) {
		this.search = search;
	}

	@Column(name = "add", nullable = false, length = 100)
	public String getAdd() {
		return this.add;
	}

	public void setAdd(String add) {
		this.add = add;
	}

	@Column(name = "edit", nullable = false, length = 100)
	public String getEdit() {
		return this.edit;
	}

	public void setEdit(String edit) {
		this.edit = edit;
	}

	@Column(name = "delete", nullable = false, length = 100)
	public String getDelete() {
		return this.delete;
	}

	public void setDelete(String delete) {
		this.delete = delete;
	}

}
