package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PfbForegroundAccount generated by hbm2java
 */
@Entity
@Table(name = "pfb_foreground_account", uniqueConstraints = @UniqueConstraint(columnNames = "account_no"))
public class PfbForegroundAccount implements java.io.Serializable {

	private Integer id;
	private String accountNo;
	private boolean type;
	private String accountName;
	private String company;
	private String ubNo;
	private boolean status;
	private Date createTime;
	private Date lastUpdateTime;

	public PfbForegroundAccount() {
	}

	public PfbForegroundAccount(String accountNo, boolean type, String accountName, String company, boolean status,
			Date createTime, Date lastUpdateTime) {
		this.accountNo = accountNo;
		this.type = type;
		this.accountName = accountName;
		this.company = company;
		this.status = status;
		this.createTime = createTime;
		this.lastUpdateTime = lastUpdateTime;
	}

	public PfbForegroundAccount(String accountNo, boolean type, String accountName, String company, String ubNo,
			boolean status, Date createTime, Date lastUpdateTime) {
		this.accountNo = accountNo;
		this.type = type;
		this.accountName = accountName;
		this.company = company;
		this.ubNo = ubNo;
		this.status = status;
		this.createTime = createTime;
		this.lastUpdateTime = lastUpdateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "account_no", unique = true, nullable = false, length = 20)
	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	@Column(name = "type", nullable = false)
	public boolean isType() {
		return this.type;
	}

	public void setType(boolean type) {
		this.type = type;
	}

	@Column(name = "account_name", nullable = false)
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Column(name = "company", nullable = false, length = 512)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "ub_no", length = 10)
	public String getUbNo() {
		return this.ubNo;
	}

	public void setUbNo(String ubNo) {
		this.ubNo = ubNo;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_time", nullable = false, length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

}
