package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PfbImpClickId generated by hbm2java
 */
@Embeddable
public class PfbImpClickId implements java.io.Serializable {

	private String styleNo;
	private String tproId;
	private Date date;
	private int hour;

	public PfbImpClickId() {
	}

	public PfbImpClickId(String styleNo, String tproId, Date date, int hour) {
		this.styleNo = styleNo;
		this.tproId = tproId;
		this.date = date;
		this.hour = hour;
	}

	@Column(name = "style_no", nullable = false, length = 30)
	public String getStyleNo() {
		return this.styleNo;
	}

	public void setStyleNo(String styleNo) {
		this.styleNo = styleNo;
	}

	@Column(name = "tpro_id", nullable = false, length = 20)
	public String getTproId() {
		return this.tproId;
	}

	public void setTproId(String tproId) {
		this.tproId = tproId;
	}

	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "hour", nullable = false)
	public int getHour() {
		return this.hour;
	}

	public void setHour(int hour) {
		this.hour = hour;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PfbImpClickId))
			return false;
		PfbImpClickId castOther = (PfbImpClickId) other;

		return ((this.getStyleNo() == castOther.getStyleNo()) || (this.getStyleNo() != null
				&& castOther.getStyleNo() != null && this.getStyleNo().equals(castOther.getStyleNo())))
				&& ((this.getTproId() == castOther.getTproId()) || (this.getTproId() != null
						&& castOther.getTproId() != null && this.getTproId().equals(castOther.getTproId())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())))
				&& (this.getHour() == castOther.getHour());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStyleNo() == null ? 0 : this.getStyleNo().hashCode());
		result = 37 * result + (getTproId() == null ? 0 : this.getTproId().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + this.getHour();
		return result;
	}

}
