package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbPchomeId generated by hbm2java
 */
@Entity
@Table(name = "pfb_pchome_id")
public class PfbPchomeId implements java.io.Serializable {

	private Integer id;
	private String pchomeId;
	private String name;
	private String email;
	private String phone;
	private String cellphone;
	private byte zipcode;
	private String address;
	private String accountNo;
	private String gid;
	private boolean status;
	private Date createTime;
	private Date inviteTime;
	private Date lastLoginTime;

	public PfbPchomeId() {
	}

	public PfbPchomeId(String pchomeId, String name, String email, String phone, String cellphone, byte zipcode,
			String address, String accountNo, String gid, boolean status, Date createTime, Date inviteTime,
			Date lastLoginTime) {
		this.pchomeId = pchomeId;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.cellphone = cellphone;
		this.zipcode = zipcode;
		this.address = address;
		this.accountNo = accountNo;
		this.gid = gid;
		this.status = status;
		this.createTime = createTime;
		this.inviteTime = inviteTime;
		this.lastLoginTime = lastLoginTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "pchome_id", nullable = false)
	public String getPchomeId() {
		return this.pchomeId;
	}

	public void setPchomeId(String pchomeId) {
		this.pchomeId = pchomeId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 600)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false, length = 30)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "cellphone", nullable = false, length = 20)
	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	@Column(name = "zipcode", nullable = false)
	public byte getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(byte zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "address", nullable = false, length = 512)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "account_no", nullable = false, length = 20)
	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	@Column(name = "gid", nullable = false, length = 20)
	public String getGid() {
		return this.gid;
	}

	public void setGid(String gid) {
		this.gid = gid;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "invite_time", nullable = false, length = 10)
	public Date getInviteTime() {
		return this.inviteTime;
	}

	public void setInviteTime(Date inviteTime) {
		this.inviteTime = inviteTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_login_time", nullable = false, length = 19)
	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

}
