package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PfbStyleNo generated by hbm2java
 */
@Entity
@Table(name = "pfb_style_no")
public class PfbStyleNo implements java.io.Serializable {

	private PfbStyleNoId id;
	private String styleNo;

	public PfbStyleNo() {
	}

	public PfbStyleNo(PfbStyleNoId id, String styleNo) {
		this.id = id;
		this.styleNo = styleNo;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "year", column = @Column(name = "year", nullable = false, length = 4)),
			@AttributeOverride(name = "season", column = @Column(name = "season", nullable = false, length = 2)),
			@AttributeOverride(name = "month", column = @Column(name = "month", nullable = false, length = 2)),
			@AttributeOverride(name = "day", column = @Column(name = "day", nullable = false, length = 2)),
			@AttributeOverride(name = "hash", column = @Column(name = "hash", nullable = false, length = 2)) })
	public PfbStyleNoId getId() {
		return this.id;
	}

	public void setId(PfbStyleNoId id) {
		this.id = id;
	}

	@Column(name = "style_no", nullable = false, length = 30)
	public String getStyleNo() {
		return this.styleNo;
	}

	public void setStyleNo(String styleNo) {
		this.styleNo = styleNo;
	}

}
