package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PfbStyleNoId generated by hbm2java
 */
@Embeddable
public class PfbStyleNoId implements java.io.Serializable {

	private String year;
	private String season;
	private String month;
	private String day;
	private String hash;

	public PfbStyleNoId() {
	}

	public PfbStyleNoId(String year, String season, String month, String day, String hash) {
		this.year = year;
		this.season = season;
		this.month = month;
		this.day = day;
		this.hash = hash;
	}

	@Column(name = "year", nullable = false, length = 4)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "season", nullable = false, length = 2)
	public String getSeason() {
		return this.season;
	}

	public void setSeason(String season) {
		this.season = season;
	}

	@Column(name = "month", nullable = false, length = 2)
	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	@Column(name = "day", nullable = false, length = 2)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Column(name = "hash", nullable = false, length = 2)
	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PfbStyleNoId))
			return false;
		PfbStyleNoId castOther = (PfbStyleNoId) other;

		return ((this.getYear() == castOther.getYear()) || (this.getYear() != null && castOther.getYear() != null
				&& this.getYear().equals(castOther.getYear())))
				&& ((this.getSeason() == castOther.getSeason()) || (this.getSeason() != null
						&& castOther.getSeason() != null && this.getSeason().equals(castOther.getSeason())))
				&& ((this.getMonth() == castOther.getMonth()) || (this.getMonth() != null
						&& castOther.getMonth() != null && this.getMonth().equals(castOther.getMonth())))
				&& ((this.getDay() == castOther.getDay()) || (this.getDay() != null && castOther.getDay() != null
						&& this.getDay().equals(castOther.getDay())))
				&& ((this.getHash() == castOther.getHash()) || (this.getHash() != null && castOther.getHash() != null
						&& this.getHash().equals(castOther.getHash())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getYear() == null ? 0 : this.getYear().hashCode());
		result = 37 * result + (getSeason() == null ? 0 : this.getSeason().hashCode());
		result = 37 * result + (getMonth() == null ? 0 : this.getMonth().hashCode());
		result = 37 * result + (getDay() == null ? 0 : this.getDay().hashCode());
		result = 37 * result + (getHash() == null ? 0 : this.getHash().hashCode());
		return result;
	}

}
