package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbStyleInfo generated by hbm2java
 */
@Entity
@Table(name = "pfb_style_info")
public class PfbStyleInfo implements java.io.Serializable {

	private String styleNo;
	private PfbWebInfo pfbWebInfo;
	private String accountNo;
	private String styleName;
	private int class_;
	private String width;
	private String height;
	private String style;
	private String description;
	private Date createTime;
	private Date updateTime;
	private boolean status;

	public PfbStyleInfo() {
	}

	public PfbStyleInfo(String styleNo, PfbWebInfo pfbWebInfo, String accountNo, String styleName, int class_,
			String width, String height, String style, String description, Date createTime, Date updateTime,
			boolean status) {
		this.styleNo = styleNo;
		this.pfbWebInfo = pfbWebInfo;
		this.accountNo = accountNo;
		this.styleName = styleName;
		this.class_ = class_;
		this.width = width;
		this.height = height;
		this.style = style;
		this.description = description;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.status = status;
	}

	@Id

	@Column(name = "style_no", unique = true, nullable = false, length = 30)
	public String getStyleNo() {
		return this.styleNo;
	}

	public void setStyleNo(String styleNo) {
		this.styleNo = styleNo;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "wid", nullable = false)
	public PfbWebInfo getPfbWebInfo() {
		return this.pfbWebInfo;
	}

	public void setPfbWebInfo(PfbWebInfo pfbWebInfo) {
		this.pfbWebInfo = pfbWebInfo;
	}

	@Column(name = "account_no", nullable = false, length = 20)
	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	@Column(name = "style_name", nullable = false, length = 1024)
	public String getStyleName() {
		return this.styleName;
	}

	public void setStyleName(String styleName) {
		this.styleName = styleName;
	}

	@Column(name = "class", nullable = false)
	public int getClass_() {
		return this.class_;
	}

	public void setClass_(int class_) {
		this.class_ = class_;
	}

	@Column(name = "width", nullable = false, length = 4)
	public String getWidth() {
		return this.width;
	}

	public void setWidth(String width) {
		this.width = width;
	}

	@Column(name = "height", nullable = false, length = 4)
	public String getHeight() {
		return this.height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	@Column(name = "style", nullable = false, length = 512)
	public String getStyle() {
		return this.style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
