package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbWebInfo generated by hbm2java
 */
@Entity
@Table(name = "pfb_web_info")
public class PfbWebInfo implements java.io.Serializable {

	private Integer id;
	private int cid;
	private String accountNo;
	private String url;
	private String urlName;
	private String urlDesc;
	private int flag;
	private Date createTime;
	private Date lastUpdateTime;
	private boolean status;
	private Set<PfbStyleInfo> pfbStyleInfos = new HashSet<PfbStyleInfo>(0);

	public PfbWebInfo() {
	}

	public PfbWebInfo(int cid, String accountNo, String url, String urlName, String urlDesc, int flag, Date createTime,
			Date lastUpdateTime, boolean status) {
		this.cid = cid;
		this.accountNo = accountNo;
		this.url = url;
		this.urlName = urlName;
		this.urlDesc = urlDesc;
		this.flag = flag;
		this.createTime = createTime;
		this.lastUpdateTime = lastUpdateTime;
		this.status = status;
	}

	public PfbWebInfo(int cid, String accountNo, String url, String urlName, String urlDesc, int flag, Date createTime,
			Date lastUpdateTime, boolean status, Set<PfbStyleInfo> pfbStyleInfos) {
		this.cid = cid;
		this.accountNo = accountNo;
		this.url = url;
		this.urlName = urlName;
		this.urlDesc = urlDesc;
		this.flag = flag;
		this.createTime = createTime;
		this.lastUpdateTime = lastUpdateTime;
		this.status = status;
		this.pfbStyleInfos = pfbStyleInfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cid", nullable = false)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	@Column(name = "account_no", nullable = false, length = 20)
	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	@Column(name = "url", nullable = false, length = 1024)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "url_name", nullable = false, length = 512)
	public String getUrlName() {
		return this.urlName;
	}

	public void setUrlName(String urlName) {
		this.urlName = urlName;
	}

	@Column(name = "url_desc", nullable = false, length = 65535)
	public String getUrlDesc() {
		return this.urlDesc;
	}

	public void setUrlDesc(String urlDesc) {
		this.urlDesc = urlDesc;
	}

	@Column(name = "flag", nullable = false)
	public int getFlag() {
		return this.flag;
	}

	public void setFlag(int flag) {
		this.flag = flag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_update_time", nullable = false, length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbWebInfo")
	public Set<PfbStyleInfo> getPfbStyleInfos() {
		return this.pfbStyleInfos;
	}

	public void setPfbStyleInfos(Set<PfbStyleInfo> pfbStyleInfos) {
		this.pfbStyleInfos = pfbStyleInfos;
	}

}
