package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxPosition generated by hbm2java
 */
@Entity
@Table(name = "pfbx_position")
public class PfbxPosition implements java.io.Serializable {

	private String PId;
	private PfbxCustomerInfo pfbxCustomerInfo;
	private String PName;
	private String templateProductXType;
	private Integer SId;
	private String pfpCustInfoId;
	private String pfdCustInfoId;
	private String httpsType;
	private int deleteFlag;
	private String PType;
	private Integer PPrice;
	private Date updateDate;
	private Date createDate;
	private Set<PfbxSampleCode> pfbxSampleCodes = new HashSet<PfbxSampleCode>(0);
	private Set<PfbxGroupCode> pfbxGroupCodes = new HashSet<PfbxGroupCode>(0);
	private Set<PfbxOptionCode> pfbxOptionCodes = new HashSet<PfbxOptionCode>(0);
	private Set<PfbxPriceCode> pfbxPriceCodes = new HashSet<PfbxPriceCode>(0);

	public PfbxPosition() {
	}

	public PfbxPosition(String PId, String PName, String templateProductXType, String httpsType, int deleteFlag,
			Date updateDate, Date createDate) {
		this.PId = PId;
		this.PName = PName;
		this.templateProductXType = templateProductXType;
		this.httpsType = httpsType;
		this.deleteFlag = deleteFlag;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public PfbxPosition(String PId, PfbxCustomerInfo pfbxCustomerInfo, String PName, String templateProductXType,
			Integer SId, String pfpCustInfoId, String pfdCustInfoId, String httpsType, int deleteFlag, String PType,
			Integer PPrice, Date updateDate, Date createDate, Set<PfbxSampleCode> pfbxSampleCodes,
			Set<PfbxGroupCode> pfbxGroupCodes, Set<PfbxOptionCode> pfbxOptionCodes, Set<PfbxPriceCode> pfbxPriceCodes) {
		this.PId = PId;
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.PName = PName;
		this.templateProductXType = templateProductXType;
		this.SId = SId;
		this.pfpCustInfoId = pfpCustInfoId;
		this.pfdCustInfoId = pfdCustInfoId;
		this.httpsType = httpsType;
		this.deleteFlag = deleteFlag;
		this.PType = PType;
		this.PPrice = PPrice;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.pfbxSampleCodes = pfbxSampleCodes;
		this.pfbxGroupCodes = pfbxGroupCodes;
		this.pfbxOptionCodes = pfbxOptionCodes;
		this.pfbxPriceCodes = pfbxPriceCodes;
	}

	@Id

	@Column(name = "p_id", unique = true, nullable = false, length = 20)
	public String getPId() {
		return this.PId;
	}

	public void setPId(String PId) {
		this.PId = PId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_info_id")
	public PfbxCustomerInfo getPfbxCustomerInfo() {
		return this.pfbxCustomerInfo;
	}

	public void setPfbxCustomerInfo(PfbxCustomerInfo pfbxCustomerInfo) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
	}

	@Column(name = "p_name", nullable = false, length = 50)
	public String getPName() {
		return this.PName;
	}

	public void setPName(String PName) {
		this.PName = PName;
	}

	@Column(name = "template_product_x_type", nullable = false, length = 3)
	public String getTemplateProductXType() {
		return this.templateProductXType;
	}

	public void setTemplateProductXType(String templateProductXType) {
		this.templateProductXType = templateProductXType;
	}

	@Column(name = "s_id")
	public Integer getSId() {
		return this.SId;
	}

	public void setSId(Integer SId) {
		this.SId = SId;
	}

	@Column(name = "pfp_cust_info_id", length = 20)
	public String getPfpCustInfoId() {
		return this.pfpCustInfoId;
	}

	public void setPfpCustInfoId(String pfpCustInfoId) {
		this.pfpCustInfoId = pfpCustInfoId;
	}

	@Column(name = "pfd_cust_info_id", length = 20)
	public String getPfdCustInfoId() {
		return this.pfdCustInfoId;
	}

	public void setPfdCustInfoId(String pfdCustInfoId) {
		this.pfdCustInfoId = pfdCustInfoId;
	}

	@Column(name = "https_type", nullable = false, length = 1)
	public String getHttpsType() {
		return this.httpsType;
	}

	public void setHttpsType(String httpsType) {
		this.httpsType = httpsType;
	}

	@Column(name = "delete_flag", nullable = false)
	public int getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(int deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Column(name = "p_type", length = 1)
	public String getPType() {
		return this.PType;
	}

	public void setPType(String PType) {
		this.PType = PType;
	}

	@Column(name = "p_price")
	public Integer getPPrice() {
		return this.PPrice;
	}

	public void setPPrice(Integer PPrice) {
		this.PPrice = PPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxPosition")
	public Set<PfbxSampleCode> getPfbxSampleCodes() {
		return this.pfbxSampleCodes;
	}

	public void setPfbxSampleCodes(Set<PfbxSampleCode> pfbxSampleCodes) {
		this.pfbxSampleCodes = pfbxSampleCodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxPosition")
	public Set<PfbxGroupCode> getPfbxGroupCodes() {
		return this.pfbxGroupCodes;
	}

	public void setPfbxGroupCodes(Set<PfbxGroupCode> pfbxGroupCodes) {
		this.pfbxGroupCodes = pfbxGroupCodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxPosition")
	public Set<PfbxOptionCode> getPfbxOptionCodes() {
		return this.pfbxOptionCodes;
	}

	public void setPfbxOptionCodes(Set<PfbxOptionCode> pfbxOptionCodes) {
		this.pfbxOptionCodes = pfbxOptionCodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxPosition")
	public Set<PfbxPriceCode> getPfbxPriceCodes() {
		return this.pfbxPriceCodes;
	}

	public void setPfbxPriceCodes(Set<PfbxPriceCode> pfbxPriceCodes) {
		this.pfbxPriceCodes = pfbxPriceCodes;
	}

}
