package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxInvalidTraffic generated by hbm2java
 */
@Entity
@Table(name = "pfbx_invalid_traffic")
public class PfbxInvalidTraffic implements java.io.Serializable {

	private String invId;
	private String pfbId;
	private Date invDate;
	private String invType;
	private String invNote;
	private float invPrice;
	private float invPfbBonus;
	private Date closeDate;
	private Date updateTime;
	private Date createDate;
	private Set<PfbxInvalidTrafficDetail> pfbxInvalidTrafficDetails = new HashSet<PfbxInvalidTrafficDetail>(0);

	public PfbxInvalidTraffic() {
	}

	public PfbxInvalidTraffic(String invId, String pfbId, Date invDate, String invType, float invPrice,
			float invPfbBonus, Date updateTime, Date createDate) {
		this.invId = invId;
		this.pfbId = pfbId;
		this.invDate = invDate;
		this.invType = invType;
		this.invPrice = invPrice;
		this.invPfbBonus = invPfbBonus;
		this.updateTime = updateTime;
		this.createDate = createDate;
	}

	public PfbxInvalidTraffic(String invId, String pfbId, Date invDate, String invType, String invNote, float invPrice,
			float invPfbBonus, Date closeDate, Date updateTime, Date createDate,
			Set<PfbxInvalidTrafficDetail> pfbxInvalidTrafficDetails) {
		this.invId = invId;
		this.pfbId = pfbId;
		this.invDate = invDate;
		this.invType = invType;
		this.invNote = invNote;
		this.invPrice = invPrice;
		this.invPfbBonus = invPfbBonus;
		this.closeDate = closeDate;
		this.updateTime = updateTime;
		this.createDate = createDate;
		this.pfbxInvalidTrafficDetails = pfbxInvalidTrafficDetails;
	}

	@Id

	@Column(name = "inv_id", unique = true, nullable = false, length = 20)
	public String getInvId() {
		return this.invId;
	}

	public void setInvId(String invId) {
		this.invId = invId;
	}

	@Column(name = "pfb_id", nullable = false, length = 20)
	public String getPfbId() {
		return this.pfbId;
	}

	public void setPfbId(String pfbId) {
		this.pfbId = pfbId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "inv_date", nullable = false, length = 10)
	public Date getInvDate() {
		return this.invDate;
	}

	public void setInvDate(Date invDate) {
		this.invDate = invDate;
	}

	@Column(name = "inv_type", nullable = false, length = 2)
	public String getInvType() {
		return this.invType;
	}

	public void setInvType(String invType) {
		this.invType = invType;
	}

	@Column(name = "inv_note", length = 2000)
	public String getInvNote() {
		return this.invNote;
	}

	public void setInvNote(String invNote) {
		this.invNote = invNote;
	}

	@Column(name = "inv_price", nullable = false, precision = 10)
	public float getInvPrice() {
		return this.invPrice;
	}

	public void setInvPrice(float invPrice) {
		this.invPrice = invPrice;
	}

	@Column(name = "inv_pfb_bonus", nullable = false, precision = 10)
	public float getInvPfbBonus() {
		return this.invPfbBonus;
	}

	public void setInvPfbBonus(float invPfbBonus) {
		this.invPfbBonus = invPfbBonus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "close_date", length = 10)
	public Date getCloseDate() {
		return this.closeDate;
	}

	public void setCloseDate(Date closeDate) {
		this.closeDate = closeDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxInvalidTraffic")
	public Set<PfbxInvalidTrafficDetail> getPfbxInvalidTrafficDetails() {
		return this.pfbxInvalidTrafficDetails;
	}

	public void setPfbxInvalidTrafficDetails(Set<PfbxInvalidTrafficDetail> pfbxInvalidTrafficDetails) {
		this.pfbxInvalidTrafficDetails = pfbxInvalidTrafficDetails;
	}

}
