package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxBonusTransDetail generated by hbm2java
 */
@Entity
@Table(name = "pfbx_bonus_trans_detail")
public class PfbxBonusTransDetail implements java.io.Serializable {

	private Integer id;
	private PfbxBonusApply pfbxBonusApply;
	private String pfbId;
	private Date recordDate;
	private Date startDate;
	private Date endDate;
	private String transItem;
	private String applyId;
	private String transDesc;
	private float transIn;
	private float transOut;
	private float transRemain;
	private float totalRemain;
	private Date createDate;

	public PfbxBonusTransDetail() {
	}

	public PfbxBonusTransDetail(String pfbId, Date recordDate, Date startDate, String transItem, String transDesc,
			float transIn, float transOut, float transRemain, float totalRemain, Date createDate) {
		this.pfbId = pfbId;
		this.recordDate = recordDate;
		this.startDate = startDate;
		this.transItem = transItem;
		this.transDesc = transDesc;
		this.transIn = transIn;
		this.transOut = transOut;
		this.transRemain = transRemain;
		this.totalRemain = totalRemain;
		this.createDate = createDate;
	}

	public PfbxBonusTransDetail(PfbxBonusApply pfbxBonusApply, String pfbId, Date recordDate, Date startDate,
			Date endDate, String transItem, String applyId, String transDesc, float transIn, float transOut,
			float transRemain, float totalRemain, Date createDate) {
		this.pfbxBonusApply = pfbxBonusApply;
		this.pfbId = pfbId;
		this.recordDate = recordDate;
		this.startDate = startDate;
		this.endDate = endDate;
		this.transItem = transItem;
		this.applyId = applyId;
		this.transDesc = transDesc;
		this.transIn = transIn;
		this.transOut = transOut;
		this.transRemain = transRemain;
		this.totalRemain = totalRemain;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fail_apply_id")
	public PfbxBonusApply getPfbxBonusApply() {
		return this.pfbxBonusApply;
	}

	public void setPfbxBonusApply(PfbxBonusApply pfbxBonusApply) {
		this.pfbxBonusApply = pfbxBonusApply;
	}

	@Column(name = "pfb_id", nullable = false, length = 20)
	public String getPfbId() {
		return this.pfbId;
	}

	public void setPfbId(String pfbId) {
		this.pfbId = pfbId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "record_date", nullable = false, length = 10)
	public Date getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(Date recordDate) {
		this.recordDate = recordDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "trans_item", nullable = false, length = 2)
	public String getTransItem() {
		return this.transItem;
	}

	public void setTransItem(String transItem) {
		this.transItem = transItem;
	}

	@Column(name = "apply_id", length = 20)
	public String getApplyId() {
		return this.applyId;
	}

	public void setApplyId(String applyId) {
		this.applyId = applyId;
	}

	@Column(name = "trans_desc", nullable = false, length = 50)
	public String getTransDesc() {
		return this.transDesc;
	}

	public void setTransDesc(String transDesc) {
		this.transDesc = transDesc;
	}

	@Column(name = "trans_in", nullable = false, precision = 10)
	public float getTransIn() {
		return this.transIn;
	}

	public void setTransIn(float transIn) {
		this.transIn = transIn;
	}

	@Column(name = "trans_out", nullable = false, precision = 10)
	public float getTransOut() {
		return this.transOut;
	}

	public void setTransOut(float transOut) {
		this.transOut = transOut;
	}

	@Column(name = "trans_remain", nullable = false, precision = 10)
	public float getTransRemain() {
		return this.transRemain;
	}

	public void setTransRemain(float transRemain) {
		this.transRemain = transRemain;
	}

	@Column(name = "total_remain", nullable = false, precision = 10)
	public float getTotalRemain() {
		return this.totalRemain;
	}

	public void setTotalRemain(float totalRemain) {
		this.totalRemain = totalRemain;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
