package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PfbxPriceUrl generated by hbm2java
 */
@Entity
@Table(name = "pfbx_price_url")
public class PfbxPriceUrl implements java.io.Serializable {

	private String UId;
	private PfbxUrl pfbxUrl;
	private PfbxUserPrice pfbxUserPrice;

	public PfbxPriceUrl() {
	}

	public PfbxPriceUrl(String UId, PfbxUrl pfbxUrl, PfbxUserPrice pfbxUserPrice) {
		this.UId = UId;
		this.pfbxUrl = pfbxUrl;
		this.pfbxUserPrice = pfbxUserPrice;
	}

	@Id

	@Column(name = "u_id", unique = true, nullable = false, length = 20)
	public String getUId() {
		return this.UId;
	}

	public void setUId(String UId) {
		this.UId = UId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "url_ref", nullable = false)
	public PfbxUrl getPfbxUrl() {
		return this.pfbxUrl;
	}

	public void setPfbxUrl(PfbxUrl pfbxUrl) {
		this.pfbxUrl = pfbxUrl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "p_id", nullable = false)
	public PfbxUserPrice getPfbxUserPrice() {
		return this.pfbxUserPrice;
	}

	public void setPfbxUserPrice(PfbxUserPrice pfbxUserPrice) {
		this.pfbxUserPrice = pfbxUserPrice;
	}

}
