package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PfbxGroupCode generated by hbm2java
 */
@Entity
@Table(name = "pfbx_group_code")
public class PfbxGroupCode implements java.io.Serializable {

	private String CId;
	private PfbxUserGroup pfbxUserGroup;
	private PfbxPosition pfbxPosition;

	public PfbxGroupCode() {
	}

	public PfbxGroupCode(String CId, PfbxUserGroup pfbxUserGroup, PfbxPosition pfbxPosition) {
		this.CId = CId;
		this.pfbxUserGroup = pfbxUserGroup;
		this.pfbxPosition = pfbxPosition;
	}

	@Id

	@Column(name = "c_id", unique = true, nullable = false, length = 20)
	public String getCId() {
		return this.CId;
	}

	public void setCId(String CId) {
		this.CId = CId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "g_id", nullable = false)
	public PfbxUserGroup getPfbxUserGroup() {
		return this.pfbxUserGroup;
	}

	public void setPfbxUserGroup(PfbxUserGroup pfbxUserGroup) {
		this.pfbxUserGroup = pfbxUserGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "name_ref", nullable = false)
	public PfbxPosition getPfbxPosition() {
		return this.pfbxPosition;
	}

	public void setPfbxPosition(PfbxPosition pfbxPosition) {
		this.pfbxPosition = pfbxPosition;
	}

}
