package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PfbxAssignBuyer generated by hbm2java
 */
@Entity
@Table(name = "pfbx_assign_buyer")
public class PfbxAssignBuyer implements java.io.Serializable {

	private String buyerId;
	private String assignPriceId;
	private int adBuyerRef;
	private Set<PfbxAssignPrice> pfbxAssignPrices = new HashSet<PfbxAssignPrice>(0);

	public PfbxAssignBuyer() {
	}

	public PfbxAssignBuyer(String buyerId, String assignPriceId, int adBuyerRef) {
		this.buyerId = buyerId;
		this.assignPriceId = assignPriceId;
		this.adBuyerRef = adBuyerRef;
	}

	public PfbxAssignBuyer(String buyerId, String assignPriceId, int adBuyerRef,
			Set<PfbxAssignPrice> pfbxAssignPrices) {
		this.buyerId = buyerId;
		this.assignPriceId = assignPriceId;
		this.adBuyerRef = adBuyerRef;
		this.pfbxAssignPrices = pfbxAssignPrices;
	}

	@Id

	@Column(name = "buyer_id", unique = true, nullable = false, length = 20)
	public String getBuyerId() {
		return this.buyerId;
	}

	public void setBuyerId(String buyerId) {
		this.buyerId = buyerId;
	}

	@Column(name = "assign_price_id", nullable = false, length = 20)
	public String getAssignPriceId() {
		return this.assignPriceId;
	}

	public void setAssignPriceId(String assignPriceId) {
		this.assignPriceId = assignPriceId;
	}

	@Column(name = "ad_buyer_ref", nullable = false)
	public int getAdBuyerRef() {
		return this.adBuyerRef;
	}

	public void setAdBuyerRef(int adBuyerRef) {
		this.adBuyerRef = adBuyerRef;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxAssignBuyer")
	public Set<PfbxAssignPrice> getPfbxAssignPrices() {
		return this.pfbxAssignPrices;
	}

	public void setPfbxAssignPrices(Set<PfbxAssignPrice> pfbxAssignPrices) {
		this.pfbxAssignPrices = pfbxAssignPrices;
	}

}
