package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxBonusDayReport generated by hbm2java
 */
@Entity
@Table(name = "pfbx_bonus_day_report")
public class PfbxBonusDayReport implements java.io.Serializable {

	private Integer id;
	private PfbxCustomerInfo pfbxCustomerInfo;
	private Date reportDate;
	private float pfbClkPrice;
	private float pfbBonusPercent;
	private float pchomeChargePercent;
	private float saveClkPrice;
	private float freeClkPrice;
	private float postpaidClkPrice;
	private float saveBonus;
	private float freeBonus;
	private float postpaidBonus;
	private float saveCharge;
	private float freeCharge;
	private float postpaidCharge;
	private float totalClkPrice;
	private float totalBonus;
	private float totalCharge;
	private Date createDate;

	public PfbxBonusDayReport() {
	}

	public PfbxBonusDayReport(PfbxCustomerInfo pfbxCustomerInfo, Date reportDate, float pfbClkPrice,
			float pfbBonusPercent, float pchomeChargePercent, float saveClkPrice, float freeClkPrice,
			float postpaidClkPrice, float saveBonus, float freeBonus, float postpaidBonus, float saveCharge,
			float freeCharge, float postpaidCharge, float totalClkPrice, float totalBonus, float totalCharge,
			Date createDate) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.reportDate = reportDate;
		this.pfbClkPrice = pfbClkPrice;
		this.pfbBonusPercent = pfbBonusPercent;
		this.pchomeChargePercent = pchomeChargePercent;
		this.saveClkPrice = saveClkPrice;
		this.freeClkPrice = freeClkPrice;
		this.postpaidClkPrice = postpaidClkPrice;
		this.saveBonus = saveBonus;
		this.freeBonus = freeBonus;
		this.postpaidBonus = postpaidBonus;
		this.saveCharge = saveCharge;
		this.freeCharge = freeCharge;
		this.postpaidCharge = postpaidCharge;
		this.totalClkPrice = totalClkPrice;
		this.totalBonus = totalBonus;
		this.totalCharge = totalCharge;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfb_id", nullable = false)
	public PfbxCustomerInfo getPfbxCustomerInfo() {
		return this.pfbxCustomerInfo;
	}

	public void setPfbxCustomerInfo(PfbxCustomerInfo pfbxCustomerInfo) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "report_date", nullable = false, length = 10)
	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "pfb_clk_price", nullable = false, precision = 10)
	public float getPfbClkPrice() {
		return this.pfbClkPrice;
	}

	public void setPfbClkPrice(float pfbClkPrice) {
		this.pfbClkPrice = pfbClkPrice;
	}

	@Column(name = "pfb_bonus_percent", nullable = false, precision = 5)
	public float getPfbBonusPercent() {
		return this.pfbBonusPercent;
	}

	public void setPfbBonusPercent(float pfbBonusPercent) {
		this.pfbBonusPercent = pfbBonusPercent;
	}

	@Column(name = "pchome_charge_percent", nullable = false, precision = 5)
	public float getPchomeChargePercent() {
		return this.pchomeChargePercent;
	}

	public void setPchomeChargePercent(float pchomeChargePercent) {
		this.pchomeChargePercent = pchomeChargePercent;
	}

	@Column(name = "save_clk_price", nullable = false, precision = 10)
	public float getSaveClkPrice() {
		return this.saveClkPrice;
	}

	public void setSaveClkPrice(float saveClkPrice) {
		this.saveClkPrice = saveClkPrice;
	}

	@Column(name = "free_clk_price", nullable = false, precision = 10)
	public float getFreeClkPrice() {
		return this.freeClkPrice;
	}

	public void setFreeClkPrice(float freeClkPrice) {
		this.freeClkPrice = freeClkPrice;
	}

	@Column(name = "postpaid_clk_price", nullable = false, precision = 10)
	public float getPostpaidClkPrice() {
		return this.postpaidClkPrice;
	}

	public void setPostpaidClkPrice(float postpaidClkPrice) {
		this.postpaidClkPrice = postpaidClkPrice;
	}

	@Column(name = "save_bonus", nullable = false, precision = 10)
	public float getSaveBonus() {
		return this.saveBonus;
	}

	public void setSaveBonus(float saveBonus) {
		this.saveBonus = saveBonus;
	}

	@Column(name = "free_bonus", nullable = false, precision = 10)
	public float getFreeBonus() {
		return this.freeBonus;
	}

	public void setFreeBonus(float freeBonus) {
		this.freeBonus = freeBonus;
	}

	@Column(name = "postpaid_bonus", nullable = false, precision = 10)
	public float getPostpaidBonus() {
		return this.postpaidBonus;
	}

	public void setPostpaidBonus(float postpaidBonus) {
		this.postpaidBonus = postpaidBonus;
	}

	@Column(name = "save_charge", nullable = false, precision = 10)
	public float getSaveCharge() {
		return this.saveCharge;
	}

	public void setSaveCharge(float saveCharge) {
		this.saveCharge = saveCharge;
	}

	@Column(name = "free_charge", nullable = false, precision = 10)
	public float getFreeCharge() {
		return this.freeCharge;
	}

	public void setFreeCharge(float freeCharge) {
		this.freeCharge = freeCharge;
	}

	@Column(name = "postpaid_charge", nullable = false, precision = 10)
	public float getPostpaidCharge() {
		return this.postpaidCharge;
	}

	public void setPostpaidCharge(float postpaidCharge) {
		this.postpaidCharge = postpaidCharge;
	}

	@Column(name = "total_clk_price", nullable = false, precision = 10)
	public float getTotalClkPrice() {
		return this.totalClkPrice;
	}

	public void setTotalClkPrice(float totalClkPrice) {
		this.totalClkPrice = totalClkPrice;
	}

	@Column(name = "total_bonus", nullable = false, precision = 10)
	public float getTotalBonus() {
		return this.totalBonus;
	}

	public void setTotalBonus(float totalBonus) {
		this.totalBonus = totalBonus;
	}

	@Column(name = "total_charge", nullable = false, precision = 10)
	public float getTotalCharge() {
		return this.totalCharge;
	}

	public void setTotalCharge(float totalCharge) {
		this.totalCharge = totalCharge;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
