package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxCustomerInfoRefXType generated by hbm2java
 */
@Entity
@Table(name = "pfbx_customer_info_ref_x_type")
public class PfbxCustomerInfoRefXType implements java.io.Serializable {

	private Integer xtypeRefId;
	private PfbxCustomerInfo pfbxCustomerInfo;
	private PfbxPositionMenu pfbxPositionMenu;
	private int status;
	private Date createDate;
	private Date updateDate;

	public PfbxCustomerInfoRefXType() {
	}

	public PfbxCustomerInfoRefXType(PfbxCustomerInfo pfbxCustomerInfo, PfbxPositionMenu pfbxPositionMenu, int status,
			Date createDate, Date updateDate) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.pfbxPositionMenu = pfbxPositionMenu;
		this.status = status;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "xtype_ref_id", unique = true, nullable = false)
	public Integer getXtypeRefId() {
		return this.xtypeRefId;
	}

	public void setXtypeRefId(Integer xtypeRefId) {
		this.xtypeRefId = xtypeRefId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfbx_customer_info_id", nullable = false)
	public PfbxCustomerInfo getPfbxCustomerInfo() {
		return this.pfbxCustomerInfo;
	}

	public void setPfbxCustomerInfo(PfbxCustomerInfo pfbxCustomerInfo) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfbx_position_menu_id", nullable = false)
	public PfbxPositionMenu getPfbxPositionMenu() {
		return this.pfbxPositionMenu;
	}

	public void setPfbxPositionMenu(PfbxPositionMenu pfbxPositionMenu) {
		this.pfbxPositionMenu = pfbxPositionMenu;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
