package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PfbxOptionCode generated by hbm2java
 */
@Entity
@Table(name = "pfbx_option_code")
public class PfbxOptionCode implements java.io.Serializable {

	private String CId;
	private PfbxPosition pfbxPosition;
	private PfbxUserOption pfbxUserOption;

	public PfbxOptionCode() {
	}

	public PfbxOptionCode(String CId, PfbxPosition pfbxPosition, PfbxUserOption pfbxUserOption) {
		this.CId = CId;
		this.pfbxPosition = pfbxPosition;
		this.pfbxUserOption = pfbxUserOption;
	}

	@Id

	@Column(name = "c_id", unique = true, nullable = false, length = 20)
	public String getCId() {
		return this.CId;
	}

	public void setCId(String CId) {
		this.CId = CId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "name_ref", nullable = false)
	public PfbxPosition getPfbxPosition() {
		return this.pfbxPosition;
	}

	public void setPfbxPosition(PfbxPosition pfbxPosition) {
		this.pfbxPosition = pfbxPosition;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "o_id", nullable = false)
	public PfbxUserOption getPfbxUserOption() {
		return this.pfbxUserOption;
	}

	public void setPfbxUserOption(PfbxUserOption pfbxUserOption) {
		this.pfbxUserOption = pfbxUserOption;
	}

}
