package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxBonusBill generated by hbm2java
 */
@Entity
@Table(name = "pfbx_bonus_bill")
public class PfbxBonusBill implements java.io.Serializable {

	private Integer id;
	private String pfbId;
	private String pfbBonusSetStatus;
	private float lastApplyMoney;
	private float applyMoney;
	private float totalApplyMoney;
	private float minLimit;
	private float billRemain;
	private Date updateDate;
	private Date createDate;

	public PfbxBonusBill() {
	}

	public PfbxBonusBill(String pfbId, String pfbBonusSetStatus, float lastApplyMoney, float applyMoney,
			float totalApplyMoney, float minLimit, float billRemain, Date updateDate, Date createDate) {
		this.pfbId = pfbId;
		this.pfbBonusSetStatus = pfbBonusSetStatus;
		this.lastApplyMoney = lastApplyMoney;
		this.applyMoney = applyMoney;
		this.totalApplyMoney = totalApplyMoney;
		this.minLimit = minLimit;
		this.billRemain = billRemain;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "pfb_id", nullable = false, length = 20)
	public String getPfbId() {
		return this.pfbId;
	}

	public void setPfbId(String pfbId) {
		this.pfbId = pfbId;
	}

	@Column(name = "pfb_bonus_set_status", nullable = false, length = 1)
	public String getPfbBonusSetStatus() {
		return this.pfbBonusSetStatus;
	}

	public void setPfbBonusSetStatus(String pfbBonusSetStatus) {
		this.pfbBonusSetStatus = pfbBonusSetStatus;
	}

	@Column(name = "last_apply_money", nullable = false, precision = 10)
	public float getLastApplyMoney() {
		return this.lastApplyMoney;
	}

	public void setLastApplyMoney(float lastApplyMoney) {
		this.lastApplyMoney = lastApplyMoney;
	}

	@Column(name = "apply_money", nullable = false, precision = 10)
	public float getApplyMoney() {
		return this.applyMoney;
	}

	public void setApplyMoney(float applyMoney) {
		this.applyMoney = applyMoney;
	}

	@Column(name = "total_apply_money", nullable = false, precision = 10)
	public float getTotalApplyMoney() {
		return this.totalApplyMoney;
	}

	public void setTotalApplyMoney(float totalApplyMoney) {
		this.totalApplyMoney = totalApplyMoney;
	}

	@Column(name = "min_limit", nullable = false, precision = 10)
	public float getMinLimit() {
		return this.minLimit;
	}

	public void setMinLimit(float minLimit) {
		this.minLimit = minLimit;
	}

	@Column(name = "bill_remain", nullable = false, precision = 10)
	public float getBillRemain() {
		return this.billRemain;
	}

	public void setBillRemain(float billRemain) {
		this.billRemain = billRemain;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
