package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxUser generated by hbm2java
 */
@Entity
@Table(name = "pfbx_user")
public class PfbxUser implements java.io.Serializable {

	private String userId;
	private PfbxCustomerInfo pfbxCustomerInfo;
	private int privilegeId;
	private String userName;
	private String memberId;
	private String userEmail;
	private String status;
	private Date lastLoginDate;
	private String lastLoginIp;
	private Date inviteDate;
	private Date activateDate;
	private Date createDate;
	private Date updateDate;

	public PfbxUser() {
	}

	public PfbxUser(String userId, int privilegeId, String userEmail, String status, Date createDate, Date updateDate) {
		this.userId = userId;
		this.privilegeId = privilegeId;
		this.userEmail = userEmail;
		this.status = status;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public PfbxUser(String userId, PfbxCustomerInfo pfbxCustomerInfo, int privilegeId, String userName, String memberId,
			String userEmail, String status, Date lastLoginDate, String lastLoginIp, Date inviteDate, Date activateDate,
			Date createDate, Date updateDate) {
		this.userId = userId;
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.privilegeId = privilegeId;
		this.userName = userName;
		this.memberId = memberId;
		this.userEmail = userEmail;
		this.status = status;
		this.lastLoginDate = lastLoginDate;
		this.lastLoginIp = lastLoginIp;
		this.inviteDate = inviteDate;
		this.activateDate = activateDate;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_info_id")
	public PfbxCustomerInfo getPfbxCustomerInfo() {
		return this.pfbxCustomerInfo;
	}

	public void setPfbxCustomerInfo(PfbxCustomerInfo pfbxCustomerInfo) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
	}

	@Column(name = "privilege_id", nullable = false)
	public int getPrivilegeId() {
		return this.privilegeId;
	}

	public void setPrivilegeId(int privilegeId) {
		this.privilegeId = privilegeId;
	}

	@Column(name = "user_name", length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "member_id", length = 20)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Column(name = "user_email", nullable = false, length = 50)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_login_date", length = 19)
	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	@Column(name = "last_login_ip", length = 20)
	public String getLastLoginIp() {
		return this.lastLoginIp;
	}

	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "invite_date", length = 19)
	public Date getInviteDate() {
		return this.inviteDate;
	}

	public void setInviteDate(Date inviteDate) {
		this.inviteDate = inviteDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "activate_date", length = 19)
	public Date getActivateDate() {
		return this.activateDate;
	}

	public void setActivateDate(Date activateDate) {
		this.activateDate = activateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
