package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PfbxUserSample generated by hbm2java
 */
@Entity
@Table(name = "pfbx_user_sample")
public class PfbxUserSample implements java.io.Serializable {

	private String SId;
	private PfbxCustomerInfo pfbxCustomerInfo;
	private int sort;
	private int piositionAllowType;
	private int urlAllowType;
	private int sizeAllowType;
	private String sampleName;
	private String adType;
	private String adwordType;
	private String borderColor;
	private String tittleColor;
	private String bgColor;
	private String fontColor;
	private String urlColor;
	private String adbackupType;
	private String adbackupContent;
	private Set<PfbxSampleUrl> pfbxSampleUrls = new HashSet<PfbxSampleUrl>(0);
	private Set<PfbxSampleCode> pfbxSampleCodes = new HashSet<PfbxSampleCode>(0);
	private Set<PfbxSampleSize> pfbxSampleSizes = new HashSet<PfbxSampleSize>(0);
	private Set<PfbxSampleArea> pfbxSampleAreas = new HashSet<PfbxSampleArea>(0);

	public PfbxUserSample() {
	}

	public PfbxUserSample(String SId, PfbxCustomerInfo pfbxCustomerInfo, int sort, int piositionAllowType,
			int urlAllowType, int sizeAllowType, String sampleName, String adType, String adwordType,
			String adbackupType) {
		this.SId = SId;
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.sort = sort;
		this.piositionAllowType = piositionAllowType;
		this.urlAllowType = urlAllowType;
		this.sizeAllowType = sizeAllowType;
		this.sampleName = sampleName;
		this.adType = adType;
		this.adwordType = adwordType;
		this.adbackupType = adbackupType;
	}

	public PfbxUserSample(String SId, PfbxCustomerInfo pfbxCustomerInfo, int sort, int piositionAllowType,
			int urlAllowType, int sizeAllowType, String sampleName, String adType, String adwordType,
			String borderColor, String tittleColor, String bgColor, String fontColor, String urlColor,
			String adbackupType, String adbackupContent, Set<PfbxSampleUrl> pfbxSampleUrls,
			Set<PfbxSampleCode> pfbxSampleCodes, Set<PfbxSampleSize> pfbxSampleSizes,
			Set<PfbxSampleArea> pfbxSampleAreas) {
		this.SId = SId;
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.sort = sort;
		this.piositionAllowType = piositionAllowType;
		this.urlAllowType = urlAllowType;
		this.sizeAllowType = sizeAllowType;
		this.sampleName = sampleName;
		this.adType = adType;
		this.adwordType = adwordType;
		this.borderColor = borderColor;
		this.tittleColor = tittleColor;
		this.bgColor = bgColor;
		this.fontColor = fontColor;
		this.urlColor = urlColor;
		this.adbackupType = adbackupType;
		this.adbackupContent = adbackupContent;
		this.pfbxSampleUrls = pfbxSampleUrls;
		this.pfbxSampleCodes = pfbxSampleCodes;
		this.pfbxSampleSizes = pfbxSampleSizes;
		this.pfbxSampleAreas = pfbxSampleAreas;
	}

	@Id

	@Column(name = "s_id", unique = true, nullable = false, length = 20)
	public String getSId() {
		return this.SId;
	}

	public void setSId(String SId) {
		this.SId = SId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_info_id", nullable = false)
	public PfbxCustomerInfo getPfbxCustomerInfo() {
		return this.pfbxCustomerInfo;
	}

	public void setPfbxCustomerInfo(PfbxCustomerInfo pfbxCustomerInfo) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
	}

	@Column(name = "sort", nullable = false)
	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

	@Column(name = "piosition_allow_type", nullable = false)
	public int getPiositionAllowType() {
		return this.piositionAllowType;
	}

	public void setPiositionAllowType(int piositionAllowType) {
		this.piositionAllowType = piositionAllowType;
	}

	@Column(name = "url_allow_type", nullable = false)
	public int getUrlAllowType() {
		return this.urlAllowType;
	}

	public void setUrlAllowType(int urlAllowType) {
		this.urlAllowType = urlAllowType;
	}

	@Column(name = "size_allow_type", nullable = false)
	public int getSizeAllowType() {
		return this.sizeAllowType;
	}

	public void setSizeAllowType(int sizeAllowType) {
		this.sizeAllowType = sizeAllowType;
	}

	@Column(name = "sample_name", nullable = false, length = 20)
	public String getSampleName() {
		return this.sampleName;
	}

	public void setSampleName(String sampleName) {
		this.sampleName = sampleName;
	}

	@Column(name = "ad_type", nullable = false, length = 10)
	public String getAdType() {
		return this.adType;
	}

	public void setAdType(String adType) {
		this.adType = adType;
	}

	@Column(name = "adword_type", nullable = false, length = 1)
	public String getAdwordType() {
		return this.adwordType;
	}

	public void setAdwordType(String adwordType) {
		this.adwordType = adwordType;
	}

	@Column(name = "border_color", length = 20)
	public String getBorderColor() {
		return this.borderColor;
	}

	public void setBorderColor(String borderColor) {
		this.borderColor = borderColor;
	}

	@Column(name = "tittle_color", length = 20)
	public String getTittleColor() {
		return this.tittleColor;
	}

	public void setTittleColor(String tittleColor) {
		this.tittleColor = tittleColor;
	}

	@Column(name = "bg_color", length = 20)
	public String getBgColor() {
		return this.bgColor;
	}

	public void setBgColor(String bgColor) {
		this.bgColor = bgColor;
	}

	@Column(name = "font_color", length = 20)
	public String getFontColor() {
		return this.fontColor;
	}

	public void setFontColor(String fontColor) {
		this.fontColor = fontColor;
	}

	@Column(name = "url_color", length = 20)
	public String getUrlColor() {
		return this.urlColor;
	}

	public void setUrlColor(String urlColor) {
		this.urlColor = urlColor;
	}

	@Column(name = "adbackup_type", nullable = false, length = 1)
	public String getAdbackupType() {
		return this.adbackupType;
	}

	public void setAdbackupType(String adbackupType) {
		this.adbackupType = adbackupType;
	}

	@Column(name = "adbackup_content", length = 1000)
	public String getAdbackupContent() {
		return this.adbackupContent;
	}

	public void setAdbackupContent(String adbackupContent) {
		this.adbackupContent = adbackupContent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserSample")
	public Set<PfbxSampleUrl> getPfbxSampleUrls() {
		return this.pfbxSampleUrls;
	}

	public void setPfbxSampleUrls(Set<PfbxSampleUrl> pfbxSampleUrls) {
		this.pfbxSampleUrls = pfbxSampleUrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserSample")
	public Set<PfbxSampleCode> getPfbxSampleCodes() {
		return this.pfbxSampleCodes;
	}

	public void setPfbxSampleCodes(Set<PfbxSampleCode> pfbxSampleCodes) {
		this.pfbxSampleCodes = pfbxSampleCodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserSample")
	public Set<PfbxSampleSize> getPfbxSampleSizes() {
		return this.pfbxSampleSizes;
	}

	public void setPfbxSampleSizes(Set<PfbxSampleSize> pfbxSampleSizes) {
		this.pfbxSampleSizes = pfbxSampleSizes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserSample")
	public Set<PfbxSampleArea> getPfbxSampleAreas() {
		return this.pfbxSampleAreas;
	}

	public void setPfbxSampleAreas(Set<PfbxSampleArea> pfbxSampleAreas) {
		this.pfbxSampleAreas = pfbxSampleAreas;
	}

}
