package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxBonusSet generated by hbm2java
 */
@Entity
@Table(name = "pfbx_bonus_set")
public class PfbxBonusSet implements java.io.Serializable {

	private Integer id;
	private String pfbId;
	private Date startDate;
	private float pfbPercent;
	private float pchomeChargePercent;
	private Date createDate;

	public PfbxBonusSet() {
	}

	public PfbxBonusSet(String pfbId, Date startDate, float pfbPercent, float pchomeChargePercent, Date createDate) {
		this.pfbId = pfbId;
		this.startDate = startDate;
		this.pfbPercent = pfbPercent;
		this.pchomeChargePercent = pchomeChargePercent;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "pfb_id", nullable = false, length = 20)
	public String getPfbId() {
		return this.pfbId;
	}

	public void setPfbId(String pfbId) {
		this.pfbId = pfbId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "pfb_percent", nullable = false, precision = 5)
	public float getPfbPercent() {
		return this.pfbPercent;
	}

	public void setPfbPercent(float pfbPercent) {
		this.pfbPercent = pfbPercent;
	}

	@Column(name = "pchome_charge_percent", nullable = false, precision = 5)
	public float getPchomeChargePercent() {
		return this.pchomeChargePercent;
	}

	public void setPchomeChargePercent(float pchomeChargePercent) {
		this.pchomeChargePercent = pchomeChargePercent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
