package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PfbxUserPrice generated by hbm2java
 */
@Entity
@Table(name = "pfbx_user_price")
public class PfbxUserPrice implements java.io.Serializable {

	private String PId;
	private PfbxPrice pfbxPriceByOtherRef;
	private PfbxCustomerInfo pfbxCustomerInfo;
	private PfbxAssignPrice pfbxAssignPrice;
	private PfbxPrice pfbxPriceByPriceRef;
	private String priceName;
	private String priceType;
	private Set<PfbxPriceSize> pfbxPriceSizes = new HashSet<PfbxPriceSize>(0);
	private Set<PfbxPriceUrl> pfbxPriceUrls = new HashSet<PfbxPriceUrl>(0);
	private Set<PfbxPriceArea> pfbxPriceAreas = new HashSet<PfbxPriceArea>(0);
	private Set<PfbxPriceCode> pfbxPriceCodes = new HashSet<PfbxPriceCode>(0);

	public PfbxUserPrice() {
	}

	public PfbxUserPrice(String PId, PfbxCustomerInfo pfbxCustomerInfo, String priceName, String priceType) {
		this.PId = PId;
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.priceName = priceName;
		this.priceType = priceType;
	}

	public PfbxUserPrice(String PId, PfbxPrice pfbxPriceByOtherRef, PfbxCustomerInfo pfbxCustomerInfo,
			PfbxAssignPrice pfbxAssignPrice, PfbxPrice pfbxPriceByPriceRef, String priceName, String priceType,
			Set<PfbxPriceSize> pfbxPriceSizes, Set<PfbxPriceUrl> pfbxPriceUrls, Set<PfbxPriceArea> pfbxPriceAreas,
			Set<PfbxPriceCode> pfbxPriceCodes) {
		this.PId = PId;
		this.pfbxPriceByOtherRef = pfbxPriceByOtherRef;
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.pfbxAssignPrice = pfbxAssignPrice;
		this.pfbxPriceByPriceRef = pfbxPriceByPriceRef;
		this.priceName = priceName;
		this.priceType = priceType;
		this.pfbxPriceSizes = pfbxPriceSizes;
		this.pfbxPriceUrls = pfbxPriceUrls;
		this.pfbxPriceAreas = pfbxPriceAreas;
		this.pfbxPriceCodes = pfbxPriceCodes;
	}

	@Id

	@Column(name = "p_id", unique = true, nullable = false, length = 20)
	public String getPId() {
		return this.PId;
	}

	public void setPId(String PId) {
		this.PId = PId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "other_ref")
	public PfbxPrice getPfbxPriceByOtherRef() {
		return this.pfbxPriceByOtherRef;
	}

	public void setPfbxPriceByOtherRef(PfbxPrice pfbxPriceByOtherRef) {
		this.pfbxPriceByOtherRef = pfbxPriceByOtherRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_info_id", nullable = false)
	public PfbxCustomerInfo getPfbxCustomerInfo() {
		return this.pfbxCustomerInfo;
	}

	public void setPfbxCustomerInfo(PfbxCustomerInfo pfbxCustomerInfo) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assign_ref")
	public PfbxAssignPrice getPfbxAssignPrice() {
		return this.pfbxAssignPrice;
	}

	public void setPfbxAssignPrice(PfbxAssignPrice pfbxAssignPrice) {
		this.pfbxAssignPrice = pfbxAssignPrice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "price_ref")
	public PfbxPrice getPfbxPriceByPriceRef() {
		return this.pfbxPriceByPriceRef;
	}

	public void setPfbxPriceByPriceRef(PfbxPrice pfbxPriceByPriceRef) {
		this.pfbxPriceByPriceRef = pfbxPriceByPriceRef;
	}

	@Column(name = "price_name", nullable = false, length = 20)
	public String getPriceName() {
		return this.priceName;
	}

	public void setPriceName(String priceName) {
		this.priceName = priceName;
	}

	@Column(name = "price_type", nullable = false, length = 1)
	public String getPriceType() {
		return this.priceType;
	}

	public void setPriceType(String priceType) {
		this.priceType = priceType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserPrice")
	public Set<PfbxPriceSize> getPfbxPriceSizes() {
		return this.pfbxPriceSizes;
	}

	public void setPfbxPriceSizes(Set<PfbxPriceSize> pfbxPriceSizes) {
		this.pfbxPriceSizes = pfbxPriceSizes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserPrice")
	public Set<PfbxPriceUrl> getPfbxPriceUrls() {
		return this.pfbxPriceUrls;
	}

	public void setPfbxPriceUrls(Set<PfbxPriceUrl> pfbxPriceUrls) {
		this.pfbxPriceUrls = pfbxPriceUrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserPrice")
	public Set<PfbxPriceArea> getPfbxPriceAreas() {
		return this.pfbxPriceAreas;
	}

	public void setPfbxPriceAreas(Set<PfbxPriceArea> pfbxPriceAreas) {
		this.pfbxPriceAreas = pfbxPriceAreas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserPrice")
	public Set<PfbxPriceCode> getPfbxPriceCodes() {
		return this.pfbxPriceCodes;
	}

	public void setPfbxPriceCodes(Set<PfbxPriceCode> pfbxPriceCodes) {
		this.pfbxPriceCodes = pfbxPriceCodes;
	}

}
