package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PfbxPrice generated by hbm2java
 */
@Entity
@Table(name = "pfbx_price")
public class PfbxPrice implements java.io.Serializable {

	private String priceId;
	private String positionType;
	private String priceType;
	private BigDecimal assignPositionPrice;
	private BigDecimal assignPrice;
	private Set<PfbxUserPrice> pfbxUserPricesForPriceRef = new HashSet<PfbxUserPrice>(0);
	private Set<PfbxUserPrice> pfbxUserPricesForOtherRef = new HashSet<PfbxUserPrice>(0);

	public PfbxPrice() {
	}

	public PfbxPrice(String priceId, String positionType, String priceType) {
		this.priceId = priceId;
		this.positionType = positionType;
		this.priceType = priceType;
	}

	public PfbxPrice(String priceId, String positionType, String priceType, BigDecimal assignPositionPrice,
			BigDecimal assignPrice, Set<PfbxUserPrice> pfbxUserPricesForPriceRef,
			Set<PfbxUserPrice> pfbxUserPricesForOtherRef) {
		this.priceId = priceId;
		this.positionType = positionType;
		this.priceType = priceType;
		this.assignPositionPrice = assignPositionPrice;
		this.assignPrice = assignPrice;
		this.pfbxUserPricesForPriceRef = pfbxUserPricesForPriceRef;
		this.pfbxUserPricesForOtherRef = pfbxUserPricesForOtherRef;
	}

	@Id

	@Column(name = "price_id", unique = true, nullable = false, length = 20)
	public String getPriceId() {
		return this.priceId;
	}

	public void setPriceId(String priceId) {
		this.priceId = priceId;
	}

	@Column(name = "position_type", nullable = false, length = 1)
	public String getPositionType() {
		return this.positionType;
	}

	public void setPositionType(String positionType) {
		this.positionType = positionType;
	}

	@Column(name = "price_type", nullable = false, length = 1)
	public String getPriceType() {
		return this.priceType;
	}

	public void setPriceType(String priceType) {
		this.priceType = priceType;
	}

	@Column(name = "assign_position_price", precision = 10)
	public BigDecimal getAssignPositionPrice() {
		return this.assignPositionPrice;
	}

	public void setAssignPositionPrice(BigDecimal assignPositionPrice) {
		this.assignPositionPrice = assignPositionPrice;
	}

	@Column(name = "assign_price", precision = 10)
	public BigDecimal getAssignPrice() {
		return this.assignPrice;
	}

	public void setAssignPrice(BigDecimal assignPrice) {
		this.assignPrice = assignPrice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxPriceByPriceRef")
	public Set<PfbxUserPrice> getPfbxUserPricesForPriceRef() {
		return this.pfbxUserPricesForPriceRef;
	}

	public void setPfbxUserPricesForPriceRef(Set<PfbxUserPrice> pfbxUserPricesForPriceRef) {
		this.pfbxUserPricesForPriceRef = pfbxUserPricesForPriceRef;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxPriceByOtherRef")
	public Set<PfbxUserPrice> getPfbxUserPricesForOtherRef() {
		return this.pfbxUserPricesForOtherRef;
	}

	public void setPfbxUserPricesForOtherRef(Set<PfbxUserPrice> pfbxUserPricesForOtherRef) {
		this.pfbxUserPricesForOtherRef = pfbxUserPricesForOtherRef;
	}

}
