package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PfbxGroupArea generated by hbm2java
 */
@Entity
@Table(name = "pfbx_group_area")
public class PfbxGroupArea implements java.io.Serializable {

	private String AId;
	private PfbxUserGroup pfbxUserGroup;
	private PfbxArea pfbxArea;

	public PfbxGroupArea() {
	}

	public PfbxGroupArea(String AId, PfbxUserGroup pfbxUserGroup, PfbxArea pfbxArea) {
		this.AId = AId;
		this.pfbxUserGroup = pfbxUserGroup;
		this.pfbxArea = pfbxArea;
	}

	@Id

	@Column(name = "a_id", unique = true, nullable = false, length = 20)
	public String getAId() {
		return this.AId;
	}

	public void setAId(String AId) {
		this.AId = AId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "g_id", nullable = false)
	public PfbxUserGroup getPfbxUserGroup() {
		return this.pfbxUserGroup;
	}

	public void setPfbxUserGroup(PfbxUserGroup pfbxUserGroup) {
		this.pfbxUserGroup = pfbxUserGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area_ref", nullable = false)
	public PfbxArea getPfbxArea() {
		return this.pfbxArea;
	}

	public void setPfbxArea(PfbxArea pfbxArea) {
		this.pfbxArea = pfbxArea;
	}

}
