package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxBank generated by hbm2java
 */
@Entity
@Table(name = "pfbx_bank")
public class PfbxBank implements java.io.Serializable {

	private Integer id;
	private PfbxCustomerInfo pfbxCustomerInfo;
	private String bankName;
	private String bankCode;
	private String branchName;
	private String branchCode;
	private String accountName;
	private String accountNumber;
	private String accountImg;
	private String mainUse;
	private String deleteFlag;
	private String checkStatus;
	private String checkNote;
	private Date createDate;
	private Date updateDate;
	private Set<PfbxBonusApply> pfbxBonusApplies = new HashSet<PfbxBonusApply>(0);
	private Set<PfbxBonusApply> pfbxBonusApplies_1 = new HashSet<PfbxBonusApply>(0);

	public PfbxBank() {
	}

	public PfbxBank(PfbxCustomerInfo pfbxCustomerInfo, String bankName, String bankCode, String accountName,
			String accountNumber, String mainUse, String deleteFlag, String checkStatus, Date createDate,
			Date updateDate) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.bankName = bankName;
		this.bankCode = bankCode;
		this.accountName = accountName;
		this.accountNumber = accountNumber;
		this.mainUse = mainUse;
		this.deleteFlag = deleteFlag;
		this.checkStatus = checkStatus;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public PfbxBank(PfbxCustomerInfo pfbxCustomerInfo, String bankName, String bankCode, String branchName,
			String branchCode, String accountName, String accountNumber, String accountImg, String mainUse,
			String deleteFlag, String checkStatus, String checkNote, Date createDate, Date updateDate,
			Set<PfbxBonusApply> pfbxBonusApplies, Set<PfbxBonusApply> pfbxBonusApplies_1) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.bankName = bankName;
		this.bankCode = bankCode;
		this.branchName = branchName;
		this.branchCode = branchCode;
		this.accountName = accountName;
		this.accountNumber = accountNumber;
		this.accountImg = accountImg;
		this.mainUse = mainUse;
		this.deleteFlag = deleteFlag;
		this.checkStatus = checkStatus;
		this.checkNote = checkNote;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.pfbxBonusApplies = pfbxBonusApplies;
		this.pfbxBonusApplies_1 = pfbxBonusApplies_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfbx_customer_info", nullable = false)
	public PfbxCustomerInfo getPfbxCustomerInfo() {
		return this.pfbxCustomerInfo;
	}

	public void setPfbxCustomerInfo(PfbxCustomerInfo pfbxCustomerInfo) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
	}

	@Column(name = "bank_name", nullable = false, length = 50)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "bank_code", nullable = false, length = 5)
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "branch_name", length = 50)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "branch_code", length = 5)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@Column(name = "account_name", nullable = false, length = 20)
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Column(name = "account_number", nullable = false, length = 20)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "account_img", length = 50)
	public String getAccountImg() {
		return this.accountImg;
	}

	public void setAccountImg(String accountImg) {
		this.accountImg = accountImg;
	}

	@Column(name = "main_use", nullable = false, length = 1)
	public String getMainUse() {
		return this.mainUse;
	}

	public void setMainUse(String mainUse) {
		this.mainUse = mainUse;
	}

	@Column(name = "delete_flag", nullable = false, length = 1)
	public String getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Column(name = "check_status", nullable = false, length = 1)
	public String getCheckStatus() {
		return this.checkStatus;
	}

	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus;
	}

	@Column(name = "check_note", length = 200)
	public String getCheckNote() {
		return this.checkNote;
	}

	public void setCheckNote(String checkNote) {
		this.checkNote = checkNote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxBank")
	public Set<PfbxBonusApply> getPfbxBonusApplies() {
		return this.pfbxBonusApplies;
	}

	public void setPfbxBonusApplies(Set<PfbxBonusApply> pfbxBonusApplies) {
		this.pfbxBonusApplies = pfbxBonusApplies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxBank")
	public Set<PfbxBonusApply> getPfbxBonusApplies_1() {
		return this.pfbxBonusApplies_1;
	}

	public void setPfbxBonusApplies_1(Set<PfbxBonusApply> pfbxBonusApplies_1) {
		this.pfbxBonusApplies_1 = pfbxBonusApplies_1;
	}

}
