package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PfbxUrl generated by hbm2java
 */
@Entity
@Table(name = "pfbx_url")
public class PfbxUrl implements java.io.Serializable {

	private Integer urlId;
	private PfbxCustomerInfo pfbxCustomerInfo;
	private String url;
	private Set<PfbxGroupUrl> pfbxGroupUrls = new HashSet<PfbxGroupUrl>(0);
	private Set<PfbxOptionUrl> pfbxOptionUrls = new HashSet<PfbxOptionUrl>(0);
	private Set<PfbxPriceUrl> pfbxPriceUrls = new HashSet<PfbxPriceUrl>(0);
	private Set<PfbxSampleUrl> pfbxSampleUrls = new HashSet<PfbxSampleUrl>(0);

	public PfbxUrl() {
	}

	public PfbxUrl(PfbxCustomerInfo pfbxCustomerInfo, String url) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.url = url;
	}

	public PfbxUrl(PfbxCustomerInfo pfbxCustomerInfo, String url, Set<PfbxGroupUrl> pfbxGroupUrls,
			Set<PfbxOptionUrl> pfbxOptionUrls, Set<PfbxPriceUrl> pfbxPriceUrls, Set<PfbxSampleUrl> pfbxSampleUrls) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.url = url;
		this.pfbxGroupUrls = pfbxGroupUrls;
		this.pfbxOptionUrls = pfbxOptionUrls;
		this.pfbxPriceUrls = pfbxPriceUrls;
		this.pfbxSampleUrls = pfbxSampleUrls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "url_id", unique = true, nullable = false)
	public Integer getUrlId() {
		return this.urlId;
	}

	public void setUrlId(Integer urlId) {
		this.urlId = urlId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_info_id", nullable = false)
	public PfbxCustomerInfo getPfbxCustomerInfo() {
		return this.pfbxCustomerInfo;
	}

	public void setPfbxCustomerInfo(PfbxCustomerInfo pfbxCustomerInfo) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
	}

	@Column(name = "url", nullable = false, length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUrl")
	public Set<PfbxGroupUrl> getPfbxGroupUrls() {
		return this.pfbxGroupUrls;
	}

	public void setPfbxGroupUrls(Set<PfbxGroupUrl> pfbxGroupUrls) {
		this.pfbxGroupUrls = pfbxGroupUrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUrl")
	public Set<PfbxOptionUrl> getPfbxOptionUrls() {
		return this.pfbxOptionUrls;
	}

	public void setPfbxOptionUrls(Set<PfbxOptionUrl> pfbxOptionUrls) {
		this.pfbxOptionUrls = pfbxOptionUrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUrl")
	public Set<PfbxPriceUrl> getPfbxPriceUrls() {
		return this.pfbxPriceUrls;
	}

	public void setPfbxPriceUrls(Set<PfbxPriceUrl> pfbxPriceUrls) {
		this.pfbxPriceUrls = pfbxPriceUrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUrl")
	public Set<PfbxSampleUrl> getPfbxSampleUrls() {
		return this.pfbxSampleUrls;
	}

	public void setPfbxSampleUrls(Set<PfbxSampleUrl> pfbxSampleUrls) {
		this.pfbxSampleUrls = pfbxSampleUrls;
	}

}
