package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PfbxOptionUrl generated by hbm2java
 */
@Entity
@Table(name = "pfbx_option_url")
public class PfbxOptionUrl implements java.io.Serializable {

	private String UId;
	private PfbxUrl pfbxUrl;
	private PfbxUserOption pfbxUserOption;

	public PfbxOptionUrl() {
	}

	public PfbxOptionUrl(String UId, PfbxUrl pfbxUrl, PfbxUserOption pfbxUserOption) {
		this.UId = UId;
		this.pfbxUrl = pfbxUrl;
		this.pfbxUserOption = pfbxUserOption;
	}

	@Id

	@Column(name = "u_id", unique = true, nullable = false, length = 20)
	public String getUId() {
		return this.UId;
	}

	public void setUId(String UId) {
		this.UId = UId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "url_ref", nullable = false)
	public PfbxUrl getPfbxUrl() {
		return this.pfbxUrl;
	}

	public void setPfbxUrl(PfbxUrl pfbxUrl) {
		this.pfbxUrl = pfbxUrl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "o_id", nullable = false)
	public PfbxUserOption getPfbxUserOption() {
		return this.pfbxUserOption;
	}

	public void setPfbxUserOption(PfbxUserOption pfbxUserOption) {
		this.pfbxUserOption = pfbxUserOption;
	}

}
