package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxUserGroupStyle generated by hbm2java
 */
@Entity
@Table(name = "pfbx_user_group_style")
public class PfbxUserGroupStyle implements java.io.Serializable {

	private String groupStyleId;
	private Integer adStyle;
	private String adStyleBackgroundColor;
	private String adStyleBorderColor;
	private String adStyleTitleColor;
	private String adStyleTextColor;
	private String adStyleUrlColor;
	private Integer mendingType;
	private String mendingContent;
	private String groupId;
	private Date createTime;
	private Date updateTime;

	public PfbxUserGroupStyle() {
	}

	public PfbxUserGroupStyle(String groupStyleId, String groupId) {
		this.groupStyleId = groupStyleId;
		this.groupId = groupId;
	}

	public PfbxUserGroupStyle(String groupStyleId, Integer adStyle, String adStyleBackgroundColor,
			String adStyleBorderColor, String adStyleTitleColor, String adStyleTextColor, String adStyleUrlColor,
			Integer mendingType, String mendingContent, String groupId, Date createTime, Date updateTime) {
		this.groupStyleId = groupStyleId;
		this.adStyle = adStyle;
		this.adStyleBackgroundColor = adStyleBackgroundColor;
		this.adStyleBorderColor = adStyleBorderColor;
		this.adStyleTitleColor = adStyleTitleColor;
		this.adStyleTextColor = adStyleTextColor;
		this.adStyleUrlColor = adStyleUrlColor;
		this.mendingType = mendingType;
		this.mendingContent = mendingContent;
		this.groupId = groupId;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id

	@Column(name = "group_style_id", unique = true, nullable = false, length = 20)
	public String getGroupStyleId() {
		return this.groupStyleId;
	}

	public void setGroupStyleId(String groupStyleId) {
		this.groupStyleId = groupStyleId;
	}

	@Column(name = "ad_style")
	public Integer getAdStyle() {
		return this.adStyle;
	}

	public void setAdStyle(Integer adStyle) {
		this.adStyle = adStyle;
	}

	@Column(name = "ad_style_background_color", length = 20)
	public String getAdStyleBackgroundColor() {
		return this.adStyleBackgroundColor;
	}

	public void setAdStyleBackgroundColor(String adStyleBackgroundColor) {
		this.adStyleBackgroundColor = adStyleBackgroundColor;
	}

	@Column(name = "ad_style_border_color", length = 20)
	public String getAdStyleBorderColor() {
		return this.adStyleBorderColor;
	}

	public void setAdStyleBorderColor(String adStyleBorderColor) {
		this.adStyleBorderColor = adStyleBorderColor;
	}

	@Column(name = "ad_style_title_color", length = 20)
	public String getAdStyleTitleColor() {
		return this.adStyleTitleColor;
	}

	public void setAdStyleTitleColor(String adStyleTitleColor) {
		this.adStyleTitleColor = adStyleTitleColor;
	}

	@Column(name = "ad_style_text_color", length = 20)
	public String getAdStyleTextColor() {
		return this.adStyleTextColor;
	}

	public void setAdStyleTextColor(String adStyleTextColor) {
		this.adStyleTextColor = adStyleTextColor;
	}

	@Column(name = "ad_style_url_color", length = 20)
	public String getAdStyleUrlColor() {
		return this.adStyleUrlColor;
	}

	public void setAdStyleUrlColor(String adStyleUrlColor) {
		this.adStyleUrlColor = adStyleUrlColor;
	}

	@Column(name = "mending_type")
	public Integer getMendingType() {
		return this.mendingType;
	}

	public void setMendingType(Integer mendingType) {
		this.mendingType = mendingType;
	}

	@Column(name = "mending_content")
	public String getMendingContent() {
		return this.mendingContent;
	}

	public void setMendingContent(String mendingContent) {
		this.mendingContent = mendingContent;
	}

	@Column(name = "group_id", nullable = false, length = 20)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
