package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PfbxSize generated by hbm2java
 */
@Entity
@Table(name = "pfbx_size")
public class PfbxSize implements java.io.Serializable {

	private Integer id;
	private Integer width;
	private Integer height;
	private Set<PfbxPriceSize> pfbxPriceSizes = new HashSet<PfbxPriceSize>(0);
	private Set<PfbxGroupSize> pfbxGroupSizes = new HashSet<PfbxGroupSize>(0);
	private Set<PfbxSampleSize> pfbxSampleSizes = new HashSet<PfbxSampleSize>(0);
	private Set<PfbxOptionSize> pfbxOptionSizes = new HashSet<PfbxOptionSize>(0);

	public PfbxSize() {
	}

	public PfbxSize(Integer width, Integer height, Set<PfbxPriceSize> pfbxPriceSizes, Set<PfbxGroupSize> pfbxGroupSizes,
			Set<PfbxSampleSize> pfbxSampleSizes, Set<PfbxOptionSize> pfbxOptionSizes) {
		this.width = width;
		this.height = height;
		this.pfbxPriceSizes = pfbxPriceSizes;
		this.pfbxGroupSizes = pfbxGroupSizes;
		this.pfbxSampleSizes = pfbxSampleSizes;
		this.pfbxOptionSizes = pfbxOptionSizes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "width")
	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	@Column(name = "height")
	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxSize")
	public Set<PfbxPriceSize> getPfbxPriceSizes() {
		return this.pfbxPriceSizes;
	}

	public void setPfbxPriceSizes(Set<PfbxPriceSize> pfbxPriceSizes) {
		this.pfbxPriceSizes = pfbxPriceSizes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxSize")
	public Set<PfbxGroupSize> getPfbxGroupSizes() {
		return this.pfbxGroupSizes;
	}

	public void setPfbxGroupSizes(Set<PfbxGroupSize> pfbxGroupSizes) {
		this.pfbxGroupSizes = pfbxGroupSizes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxSize")
	public Set<PfbxSampleSize> getPfbxSampleSizes() {
		return this.pfbxSampleSizes;
	}

	public void setPfbxSampleSizes(Set<PfbxSampleSize> pfbxSampleSizes) {
		this.pfbxSampleSizes = pfbxSampleSizes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxSize")
	public Set<PfbxOptionSize> getPfbxOptionSizes() {
		return this.pfbxOptionSizes;
	}

	public void setPfbxOptionSizes(Set<PfbxOptionSize> pfbxOptionSizes) {
		this.pfbxOptionSizes = pfbxOptionSizes;
	}

}
