package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PfbxOptionArea generated by hbm2java
 */
@Entity
@Table(name = "pfbx_option_area")
public class PfbxOptionArea implements java.io.Serializable {

	private String AId;
	private PfbxUserOption pfbxUserOption;
	private PfbxArea pfbxArea;

	public PfbxOptionArea() {
	}

	public PfbxOptionArea(String AId, PfbxUserOption pfbxUserOption, PfbxArea pfbxArea) {
		this.AId = AId;
		this.pfbxUserOption = pfbxUserOption;
		this.pfbxArea = pfbxArea;
	}

	@Id

	@Column(name = "a_id", unique = true, nullable = false, length = 20)
	public String getAId() {
		return this.AId;
	}

	public void setAId(String AId) {
		this.AId = AId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "o_id", nullable = false)
	public PfbxUserOption getPfbxUserOption() {
		return this.pfbxUserOption;
	}

	public void setPfbxUserOption(PfbxUserOption pfbxUserOption) {
		this.pfbxUserOption = pfbxUserOption;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area_ref", nullable = false)
	public PfbxArea getPfbxArea() {
		return this.pfbxArea;
	}

	public void setPfbxArea(PfbxArea pfbxArea) {
		this.pfbxArea = pfbxArea;
	}

}
