package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PfbxArea generated by hbm2java
 */
@Entity
@Table(name = "pfbx_area")
public class PfbxArea implements java.io.Serializable {

	private Integer id;
	private String area;
	private Set<PfbxOptionArea> pfbxOptionAreas = new HashSet<PfbxOptionArea>(0);
	private Set<PfbxSampleArea> pfbxSampleAreas = new HashSet<PfbxSampleArea>(0);
	private Set<PfbxGroupArea> pfbxGroupAreas = new HashSet<PfbxGroupArea>(0);
	private Set<PfbxPriceArea> pfbxPriceAreas = new HashSet<PfbxPriceArea>(0);

	public PfbxArea() {
	}

	public PfbxArea(String area) {
		this.area = area;
	}

	public PfbxArea(String area, Set<PfbxOptionArea> pfbxOptionAreas, Set<PfbxSampleArea> pfbxSampleAreas,
			Set<PfbxGroupArea> pfbxGroupAreas, Set<PfbxPriceArea> pfbxPriceAreas) {
		this.area = area;
		this.pfbxOptionAreas = pfbxOptionAreas;
		this.pfbxSampleAreas = pfbxSampleAreas;
		this.pfbxGroupAreas = pfbxGroupAreas;
		this.pfbxPriceAreas = pfbxPriceAreas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "area", nullable = false, length = 30)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxArea")
	public Set<PfbxOptionArea> getPfbxOptionAreas() {
		return this.pfbxOptionAreas;
	}

	public void setPfbxOptionAreas(Set<PfbxOptionArea> pfbxOptionAreas) {
		this.pfbxOptionAreas = pfbxOptionAreas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxArea")
	public Set<PfbxSampleArea> getPfbxSampleAreas() {
		return this.pfbxSampleAreas;
	}

	public void setPfbxSampleAreas(Set<PfbxSampleArea> pfbxSampleAreas) {
		this.pfbxSampleAreas = pfbxSampleAreas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxArea")
	public Set<PfbxGroupArea> getPfbxGroupAreas() {
		return this.pfbxGroupAreas;
	}

	public void setPfbxGroupAreas(Set<PfbxGroupArea> pfbxGroupAreas) {
		this.pfbxGroupAreas = pfbxGroupAreas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxArea")
	public Set<PfbxPriceArea> getPfbxPriceAreas() {
		return this.pfbxPriceAreas;
	}

	public void setPfbxPriceAreas(Set<PfbxPriceArea> pfbxPriceAreas) {
		this.pfbxPriceAreas = pfbxPriceAreas;
	}

}
