package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxBoard generated by hbm2java
 */
@Entity
@Table(name = "pfbx_board")
public class PfbxBoard implements java.io.Serializable {

	private Integer boardId;
	private String pfbxCustomerInfoId;
	private String boardContent;
	private String boardType;
	private Date startDate;
	private Date endDate;
	private String hasUrl;
	private String urlAddress;
	private String deleteId;
	private Date updateDate;
	private Date createDate;

	public PfbxBoard() {
	}

	public PfbxBoard(String boardContent, String boardType, Date startDate, Date endDate, String hasUrl,
			Date createDate) {
		this.boardContent = boardContent;
		this.boardType = boardType;
		this.startDate = startDate;
		this.endDate = endDate;
		this.hasUrl = hasUrl;
		this.createDate = createDate;
	}

	public PfbxBoard(String pfbxCustomerInfoId, String boardContent, String boardType, Date startDate, Date endDate,
			String hasUrl, String urlAddress, String deleteId, Date updateDate, Date createDate) {
		this.pfbxCustomerInfoId = pfbxCustomerInfoId;
		this.boardContent = boardContent;
		this.boardType = boardType;
		this.startDate = startDate;
		this.endDate = endDate;
		this.hasUrl = hasUrl;
		this.urlAddress = urlAddress;
		this.deleteId = deleteId;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "board_id", unique = true, nullable = false)
	public Integer getBoardId() {
		return this.boardId;
	}

	public void setBoardId(Integer boardId) {
		this.boardId = boardId;
	}

	@Column(name = "pfbx_customer_info_id", length = 20)
	public String getPfbxCustomerInfoId() {
		return this.pfbxCustomerInfoId;
	}

	public void setPfbxCustomerInfoId(String pfbxCustomerInfoId) {
		this.pfbxCustomerInfoId = pfbxCustomerInfoId;
	}

	@Column(name = "board_content", nullable = false, length = 500)
	public String getBoardContent() {
		return this.boardContent;
	}

	public void setBoardContent(String boardContent) {
		this.boardContent = boardContent;
	}

	@Column(name = "board_type", nullable = false, length = 1)
	public String getBoardType() {
		return this.boardType;
	}

	public void setBoardType(String boardType) {
		this.boardType = boardType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", nullable = false, length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", nullable = false, length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "has_url", nullable = false, length = 1)
	public String getHasUrl() {
		return this.hasUrl;
	}

	public void setHasUrl(String hasUrl) {
		this.hasUrl = hasUrl;
	}

	@Column(name = "url_address", length = 200)
	public String getUrlAddress() {
		return this.urlAddress;
	}

	public void setUrlAddress(String urlAddress) {
		this.urlAddress = urlAddress;
	}

	@Column(name = "delete_id", length = 20)
	public String getDeleteId() {
		return this.deleteId;
	}

	public void setDeleteId(String deleteId) {
		this.deleteId = deleteId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
