package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxBonusApply generated by hbm2java
 */
@Entity
@Table(name = "pfbx_bonus_apply")
public class PfbxBonusApply implements java.io.Serializable {

	private String applyId;
	private PfbxBank pfbxBank;
	private PfbxCustomerInfo pfbxCustomerInfo;
	private PfbxPersonal pfbxPersonal;
	private Date applyDate;
	private float applyMoney;
	private float tax;
	private String invoiceCheckStatus;
	private String invoiceStatus;
	private String invoiceNote;
	private String invoiceImg;
	private String applyStatus;
	private String applyNote;
	private Date payDate;
	private Date updateDate;
	private Date createDate;
	private Set<PfbxBonusTransDetail> pfbxBonusTransDetails = new HashSet<PfbxBonusTransDetail>(0);

	public PfbxBonusApply() {
	}

	public PfbxBonusApply(String applyId, PfbxCustomerInfo pfbxCustomerInfo, Date applyDate, float applyMoney,
			float tax, String invoiceStatus, String applyStatus, Date updateDate, Date createDate) {
		this.applyId = applyId;
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.applyDate = applyDate;
		this.applyMoney = applyMoney;
		this.tax = tax;
		this.invoiceStatus = invoiceStatus;
		this.applyStatus = applyStatus;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public PfbxBonusApply(String applyId, PfbxBank pfbxBank, PfbxCustomerInfo pfbxCustomerInfo,
			PfbxPersonal pfbxPersonal, Date applyDate, float applyMoney, float tax, String invoiceCheckStatus,
			String invoiceStatus, String invoiceNote, String invoiceImg, String applyStatus, String applyNote,
			Date payDate, Date updateDate, Date createDate, Set<PfbxBonusTransDetail> pfbxBonusTransDetails) {
		this.applyId = applyId;
		this.pfbxBank = pfbxBank;
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.pfbxPersonal = pfbxPersonal;
		this.applyDate = applyDate;
		this.applyMoney = applyMoney;
		this.tax = tax;
		this.invoiceCheckStatus = invoiceCheckStatus;
		this.invoiceStatus = invoiceStatus;
		this.invoiceNote = invoiceNote;
		this.invoiceImg = invoiceImg;
		this.applyStatus = applyStatus;
		this.applyNote = applyNote;
		this.payDate = payDate;
		this.updateDate = updateDate;
		this.createDate = createDate;
		this.pfbxBonusTransDetails = pfbxBonusTransDetails;
	}

	@Id

	@Column(name = "apply_id", unique = true, nullable = false, length = 20)
	public String getApplyId() {
		return this.applyId;
	}

	public void setApplyId(String applyId) {
		this.applyId = applyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfbx_bank")
	public PfbxBank getPfbxBank() {
		return this.pfbxBank;
	}

	public void setPfbxBank(PfbxBank pfbxBank) {
		this.pfbxBank = pfbxBank;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfb_id", nullable = false)
	public PfbxCustomerInfo getPfbxCustomerInfo() {
		return this.pfbxCustomerInfo;
	}

	public void setPfbxCustomerInfo(PfbxCustomerInfo pfbxCustomerInfo) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfbx_personal")
	public PfbxPersonal getPfbxPersonal() {
		return this.pfbxPersonal;
	}

	public void setPfbxPersonal(PfbxPersonal pfbxPersonal) {
		this.pfbxPersonal = pfbxPersonal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "apply_date", nullable = false, length = 10)
	public Date getApplyDate() {
		return this.applyDate;
	}

	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}

	@Column(name = "apply_money", nullable = false, precision = 10)
	public float getApplyMoney() {
		return this.applyMoney;
	}

	public void setApplyMoney(float applyMoney) {
		this.applyMoney = applyMoney;
	}

	@Column(name = "tax", nullable = false, precision = 10)
	public float getTax() {
		return this.tax;
	}

	public void setTax(float tax) {
		this.tax = tax;
	}

	@Column(name = "invoice_check_status", length = 1)
	public String getInvoiceCheckStatus() {
		return this.invoiceCheckStatus;
	}

	public void setInvoiceCheckStatus(String invoiceCheckStatus) {
		this.invoiceCheckStatus = invoiceCheckStatus;
	}

	@Column(name = "invoice_status", nullable = false, length = 1)
	public String getInvoiceStatus() {
		return this.invoiceStatus;
	}

	public void setInvoiceStatus(String invoiceStatus) {
		this.invoiceStatus = invoiceStatus;
	}

	@Column(name = "invoice_note", length = 200)
	public String getInvoiceNote() {
		return this.invoiceNote;
	}

	public void setInvoiceNote(String invoiceNote) {
		this.invoiceNote = invoiceNote;
	}

	@Column(name = "invoice_img", length = 100)
	public String getInvoiceImg() {
		return this.invoiceImg;
	}

	public void setInvoiceImg(String invoiceImg) {
		this.invoiceImg = invoiceImg;
	}

	@Column(name = "apply_status", nullable = false, length = 1)
	public String getApplyStatus() {
		return this.applyStatus;
	}

	public void setApplyStatus(String applyStatus) {
		this.applyStatus = applyStatus;
	}

	@Column(name = "apply_note", length = 200)
	public String getApplyNote() {
		return this.applyNote;
	}

	public void setApplyNote(String applyNote) {
		this.applyNote = applyNote;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pay_date", length = 10)
	public Date getPayDate() {
		return this.payDate;
	}

	public void setPayDate(Date payDate) {
		this.payDate = payDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxBonusApply")
	public Set<PfbxBonusTransDetail> getPfbxBonusTransDetails() {
		return this.pfbxBonusTransDetails;
	}

	public void setPfbxBonusTransDetails(Set<PfbxBonusTransDetail> pfbxBonusTransDetails) {
		this.pfbxBonusTransDetails = pfbxBonusTransDetails;
	}

}
