package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PfbxPriceSize generated by hbm2java
 */
@Entity
@Table(name = "pfbx_price_size")
public class PfbxPriceSize implements java.io.Serializable {

	private String id;
	private PfbxUserPrice pfbxUserPrice;
	private PfbxSize pfbxSize;

	public PfbxPriceSize() {
	}

	public PfbxPriceSize(String id, PfbxUserPrice pfbxUserPrice, PfbxSize pfbxSize) {
		this.id = id;
		this.pfbxUserPrice = pfbxUserPrice;
		this.pfbxSize = pfbxSize;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 20)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "p_id", nullable = false)
	public PfbxUserPrice getPfbxUserPrice() {
		return this.pfbxUserPrice;
	}

	public void setPfbxUserPrice(PfbxUserPrice pfbxUserPrice) {
		this.pfbxUserPrice = pfbxUserPrice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "size_ref", nullable = false)
	public PfbxSize getPfbxSize() {
		return this.pfbxSize;
	}

	public void setPfbxSize(PfbxSize pfbxSize) {
		this.pfbxSize = pfbxSize;
	}

}
