package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PfbxUserGroup generated by hbm2java
 */
@Entity
@Table(name = "pfbx_user_group")
public class PfbxUserGroup implements java.io.Serializable {

	private String GId;
	private PfbxCustomerInfo pfbxCustomerInfo;
	private String groupName;
	private int piositionAllowType;
	private int urlAllowType;
	private int sizeAllowType;
	private Integer deleteFlag;
	private Set<PfbxGroupArea> pfbxGroupAreas = new HashSet<PfbxGroupArea>(0);
	private Set<PfbxGroupUrl> pfbxGroupUrls = new HashSet<PfbxGroupUrl>(0);
	private Set<PfbxGroupSize> pfbxGroupSizes = new HashSet<PfbxGroupSize>(0);
	private Set<PfbxGroupCode> pfbxGroupCodes = new HashSet<PfbxGroupCode>(0);

	public PfbxUserGroup() {
	}

	public PfbxUserGroup(String GId, PfbxCustomerInfo pfbxCustomerInfo, String groupName, int piositionAllowType,
			int urlAllowType, int sizeAllowType) {
		this.GId = GId;
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.groupName = groupName;
		this.piositionAllowType = piositionAllowType;
		this.urlAllowType = urlAllowType;
		this.sizeAllowType = sizeAllowType;
	}

	public PfbxUserGroup(String GId, PfbxCustomerInfo pfbxCustomerInfo, String groupName, int piositionAllowType,
			int urlAllowType, int sizeAllowType, Integer deleteFlag, Set<PfbxGroupArea> pfbxGroupAreas,
			Set<PfbxGroupUrl> pfbxGroupUrls, Set<PfbxGroupSize> pfbxGroupSizes, Set<PfbxGroupCode> pfbxGroupCodes) {
		this.GId = GId;
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.groupName = groupName;
		this.piositionAllowType = piositionAllowType;
		this.urlAllowType = urlAllowType;
		this.sizeAllowType = sizeAllowType;
		this.deleteFlag = deleteFlag;
		this.pfbxGroupAreas = pfbxGroupAreas;
		this.pfbxGroupUrls = pfbxGroupUrls;
		this.pfbxGroupSizes = pfbxGroupSizes;
		this.pfbxGroupCodes = pfbxGroupCodes;
	}

	@Id

	@Column(name = "g_id", unique = true, nullable = false, length = 20)
	public String getGId() {
		return this.GId;
	}

	public void setGId(String GId) {
		this.GId = GId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_info_id", nullable = false)
	public PfbxCustomerInfo getPfbxCustomerInfo() {
		return this.pfbxCustomerInfo;
	}

	public void setPfbxCustomerInfo(PfbxCustomerInfo pfbxCustomerInfo) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
	}

	@Column(name = "group_name", nullable = false, length = 20)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "piosition_allow_type", nullable = false)
	public int getPiositionAllowType() {
		return this.piositionAllowType;
	}

	public void setPiositionAllowType(int piositionAllowType) {
		this.piositionAllowType = piositionAllowType;
	}

	@Column(name = "url_allow_type", nullable = false)
	public int getUrlAllowType() {
		return this.urlAllowType;
	}

	public void setUrlAllowType(int urlAllowType) {
		this.urlAllowType = urlAllowType;
	}

	@Column(name = "size_allow_type", nullable = false)
	public int getSizeAllowType() {
		return this.sizeAllowType;
	}

	public void setSizeAllowType(int sizeAllowType) {
		this.sizeAllowType = sizeAllowType;
	}

	@Column(name = "delete_flag")
	public Integer getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Integer deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserGroup")
	public Set<PfbxGroupArea> getPfbxGroupAreas() {
		return this.pfbxGroupAreas;
	}

	public void setPfbxGroupAreas(Set<PfbxGroupArea> pfbxGroupAreas) {
		this.pfbxGroupAreas = pfbxGroupAreas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserGroup")
	public Set<PfbxGroupUrl> getPfbxGroupUrls() {
		return this.pfbxGroupUrls;
	}

	public void setPfbxGroupUrls(Set<PfbxGroupUrl> pfbxGroupUrls) {
		this.pfbxGroupUrls = pfbxGroupUrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserGroup")
	public Set<PfbxGroupSize> getPfbxGroupSizes() {
		return this.pfbxGroupSizes;
	}

	public void setPfbxGroupSizes(Set<PfbxGroupSize> pfbxGroupSizes) {
		this.pfbxGroupSizes = pfbxGroupSizes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserGroup")
	public Set<PfbxGroupCode> getPfbxGroupCodes() {
		return this.pfbxGroupCodes;
	}

	public void setPfbxGroupCodes(Set<PfbxGroupCode> pfbxGroupCodes) {
		this.pfbxGroupCodes = pfbxGroupCodes;
	}

}
