package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxAllowUrl generated by hbm2java
 */
@Entity
@Table(name = "pfbx_allow_url")
public class PfbxAllowUrl implements java.io.Serializable {

	private Integer id;
	private PfbxCustomerInfo pfbxCustomerInfo;
	private String categoryCode;
	private String url;
	private String rootDomain;
	private String urlName;
	private String urlStatus;
	private String refuseNote;
	private String defaultType;
	private String deleteFlag;
	private Date updateDate;
	private Date createDate;

	public PfbxAllowUrl() {
	}

	public PfbxAllowUrl(PfbxCustomerInfo pfbxCustomerInfo, String urlStatus, Date updateDate, Date createDate) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.urlStatus = urlStatus;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public PfbxAllowUrl(PfbxCustomerInfo pfbxCustomerInfo, String categoryCode, String url, String rootDomain,
			String urlName, String urlStatus, String refuseNote, String defaultType, String deleteFlag, Date updateDate,
			Date createDate) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.categoryCode = categoryCode;
		this.url = url;
		this.rootDomain = rootDomain;
		this.urlName = urlName;
		this.urlStatus = urlStatus;
		this.refuseNote = refuseNote;
		this.defaultType = defaultType;
		this.deleteFlag = deleteFlag;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_info_id", nullable = false)
	public PfbxCustomerInfo getPfbxCustomerInfo() {
		return this.pfbxCustomerInfo;
	}

	public void setPfbxCustomerInfo(PfbxCustomerInfo pfbxCustomerInfo) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
	}

	@Column(name = "category_code", length = 20)
	public String getCategoryCode() {
		return this.categoryCode;
	}

	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	@Column(name = "url", length = 500)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "root_domain", length = 500)
	public String getRootDomain() {
		return this.rootDomain;
	}

	public void setRootDomain(String rootDomain) {
		this.rootDomain = rootDomain;
	}

	@Column(name = "url_name", length = 100)
	public String getUrlName() {
		return this.urlName;
	}

	public void setUrlName(String urlName) {
		this.urlName = urlName;
	}

	@Column(name = "url_status", nullable = false, length = 1)
	public String getUrlStatus() {
		return this.urlStatus;
	}

	public void setUrlStatus(String urlStatus) {
		this.urlStatus = urlStatus;
	}

	@Column(name = "refuse_note", length = 100)
	public String getRefuseNote() {
		return this.refuseNote;
	}

	public void setRefuseNote(String refuseNote) {
		this.refuseNote = refuseNote;
	}

	@Column(name = "default_type", length = 1)
	public String getDefaultType() {
		return this.defaultType;
	}

	public void setDefaultType(String defaultType) {
		this.defaultType = defaultType;
	}

	@Column(name = "delete_flag", length = 1)
	public String getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
