package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PfbxIndustry generated by hbm2java
 */
@Entity
@Table(name = "pfbx_industry")
public class PfbxIndustry implements java.io.Serializable {

	private int id;
	private String industry;
	private String userId;

	public PfbxIndustry() {
	}

	public PfbxIndustry(int id, String industry, String userId) {
		this.id = id;
		this.industry = industry;
		this.userId = userId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "industry", nullable = false, length = 100)
	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	@Column(name = "user_id", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
