package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxPersonal generated by hbm2java
 */
@Entity
@Table(name = "pfbx_personal")
public class PfbxPersonal implements java.io.Serializable {

	private Integer id;
	private PfbxCustomerInfo pfbxCustomerInfo;
	private String name;
	private Date birthday;
	private String zip;
	private String contactAddress;
	private String idCard;
	private String idCardImg;
	private String mainUse;
	private String deleteFlag;
	private String checkStatus;
	private String checkNote;
	private Date createDate;
	private Date updateDate;
	private Set<PfbxBonusApply> pfbxBonusApplies = new HashSet<PfbxBonusApply>(0);
	private Set<PfbxBonusApply> pfbxBonusApplies_1 = new HashSet<PfbxBonusApply>(0);

	public PfbxPersonal() {
	}

	public PfbxPersonal(PfbxCustomerInfo pfbxCustomerInfo, String name, Date birthday, String zip,
			String contactAddress, String idCard, String mainUse, String deleteFlag, String checkStatus,
			Date createDate, Date updateDate) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.name = name;
		this.birthday = birthday;
		this.zip = zip;
		this.contactAddress = contactAddress;
		this.idCard = idCard;
		this.mainUse = mainUse;
		this.deleteFlag = deleteFlag;
		this.checkStatus = checkStatus;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public PfbxPersonal(PfbxCustomerInfo pfbxCustomerInfo, String name, Date birthday, String zip,
			String contactAddress, String idCard, String idCardImg, String mainUse, String deleteFlag,
			String checkStatus, String checkNote, Date createDate, Date updateDate,
			Set<PfbxBonusApply> pfbxBonusApplies, Set<PfbxBonusApply> pfbxBonusApplies_1) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.name = name;
		this.birthday = birthday;
		this.zip = zip;
		this.contactAddress = contactAddress;
		this.idCard = idCard;
		this.idCardImg = idCardImg;
		this.mainUse = mainUse;
		this.deleteFlag = deleteFlag;
		this.checkStatus = checkStatus;
		this.checkNote = checkNote;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.pfbxBonusApplies = pfbxBonusApplies;
		this.pfbxBonusApplies_1 = pfbxBonusApplies_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfbx_customer_info", nullable = false)
	public PfbxCustomerInfo getPfbxCustomerInfo() {
		return this.pfbxCustomerInfo;
	}

	public void setPfbxCustomerInfo(PfbxCustomerInfo pfbxCustomerInfo) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", nullable = false, length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "zip", nullable = false, length = 5)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "contact_address", nullable = false, length = 200)
	public String getContactAddress() {
		return this.contactAddress;
	}

	public void setContactAddress(String contactAddress) {
		this.contactAddress = contactAddress;
	}

	@Column(name = "id_card", nullable = false, length = 20)
	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	@Column(name = "id_card_img", length = 50)
	public String getIdCardImg() {
		return this.idCardImg;
	}

	public void setIdCardImg(String idCardImg) {
		this.idCardImg = idCardImg;
	}

	@Column(name = "main_use", nullable = false, length = 1)
	public String getMainUse() {
		return this.mainUse;
	}

	public void setMainUse(String mainUse) {
		this.mainUse = mainUse;
	}

	@Column(name = "delete_flag", nullable = false, length = 1)
	public String getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Column(name = "check_status", nullable = false, length = 1)
	public String getCheckStatus() {
		return this.checkStatus;
	}

	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus;
	}

	@Column(name = "check_note", length = 200)
	public String getCheckNote() {
		return this.checkNote;
	}

	public void setCheckNote(String checkNote) {
		this.checkNote = checkNote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxPersonal")
	public Set<PfbxBonusApply> getPfbxBonusApplies() {
		return this.pfbxBonusApplies;
	}

	public void setPfbxBonusApplies(Set<PfbxBonusApply> pfbxBonusApplies) {
		this.pfbxBonusApplies = pfbxBonusApplies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxPersonal")
	public Set<PfbxBonusApply> getPfbxBonusApplies_1() {
		return this.pfbxBonusApplies_1;
	}

	public void setPfbxBonusApplies_1(Set<PfbxBonusApply> pfbxBonusApplies_1) {
		this.pfbxBonusApplies_1 = pfbxBonusApplies_1;
	}

}
