package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxBonusSetSpecial generated by hbm2java
 */
@Entity
@Table(name = "pfbx_bonus_set_special")
public class PfbxBonusSetSpecial implements java.io.Serializable {

	private Integer id;
	private String pfbId;
	private String specialName;
	private Date startDate;
	private Date endDate;
	private float pfbPercent;
	private float pchomeChargePercent;
	private Integer deleteFlag;
	private Date updateDate;
	private Date createDate;

	public PfbxBonusSetSpecial() {
	}

	public PfbxBonusSetSpecial(String pfbId, Date startDate, Date endDate, float pfbPercent, float pchomeChargePercent,
			Date updateDate, Date createDate) {
		this.pfbId = pfbId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.pfbPercent = pfbPercent;
		this.pchomeChargePercent = pchomeChargePercent;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	public PfbxBonusSetSpecial(String pfbId, String specialName, Date startDate, Date endDate, float pfbPercent,
			float pchomeChargePercent, Integer deleteFlag, Date updateDate, Date createDate) {
		this.pfbId = pfbId;
		this.specialName = specialName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.pfbPercent = pfbPercent;
		this.pchomeChargePercent = pchomeChargePercent;
		this.deleteFlag = deleteFlag;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "pfb_id", nullable = false, length = 20)
	public String getPfbId() {
		return this.pfbId;
	}

	public void setPfbId(String pfbId) {
		this.pfbId = pfbId;
	}

	@Column(name = "special_name", length = 50)
	public String getSpecialName() {
		return this.specialName;
	}

	public void setSpecialName(String specialName) {
		this.specialName = specialName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "pfb_percent", nullable = false, precision = 5)
	public float getPfbPercent() {
		return this.pfbPercent;
	}

	public void setPfbPercent(float pfbPercent) {
		this.pfbPercent = pfbPercent;
	}

	@Column(name = "pchome_charge_percent", nullable = false, precision = 5)
	public float getPchomeChargePercent() {
		return this.pchomeChargePercent;
	}

	public void setPchomeChargePercent(float pchomeChargePercent) {
		this.pchomeChargePercent = pchomeChargePercent;
	}

	@Column(name = "delete_flag")
	public Integer getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Integer deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
