package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfbxCustomerInfo generated by hbm2java
 */
@Entity
@Table(name = "pfbx_customer_info")
public class PfbxCustomerInfo implements java.io.Serializable {

	private String customerInfoId;
	private String memberId;
	private Date birthday;
	private String category;
	private String companyName;
	private String taxId;
	private String contactName;
	private String contactPhone;
	private String contactCell;
	private String websiteChineseName;
	private String websiteEnglishName;
	private String websiteDisplayUrl;
	private String status;
	private String statusNote;
	private Integer adType;
	private String playType;
	private Date closeDate;
	private Date activateDate;
	private Date createDate;
	private Date updateDate;
	private Set<AdmPfbxBlockUrl> admPfbxBlockUrls = new HashSet<AdmPfbxBlockUrl>(0);
	private Set<PfbxPosition> pfbxPositions = new HashSet<PfbxPosition>(0);
	private Set<PfbxUrl> pfbxUrls = new HashSet<PfbxUrl>(0);
	private Set<PfbxAllowUrl> pfbxAllowUrls = new HashSet<PfbxAllowUrl>(0);
	private Set<PfbxBonusApply> pfbxBonusApplies = new HashSet<PfbxBonusApply>(0);
	private Set<PfbxBonusApply> pfbxBonusApplies_1 = new HashSet<PfbxBonusApply>(0);
	private Set<PfbxBank> pfbxBanks = new HashSet<PfbxBank>(0);
	private Set<PfbxUserSample> pfbxUserSamples = new HashSet<PfbxUserSample>(0);
	private Set<PfbxPermission> pfbxPermissions = new HashSet<PfbxPermission>(0);
	private Set<PfbxUserGroup> pfbxUserGroups = new HashSet<PfbxUserGroup>(0);
	private Set<PfbxUser> pfbxUsers = new HashSet<PfbxUser>(0);
	private Set<PfbxCustomerInfoRefXType> pfbxCustomerInfoRefXTypes = new HashSet<PfbxCustomerInfoRefXType>(0);
	private Set<PfbxBonusDayReport> pfbxBonusDayReports = new HashSet<PfbxBonusDayReport>(0);
	private Set<PfbxBonusDayReport> pfbxBonusDayReports_1 = new HashSet<PfbxBonusDayReport>(0);
	private Set<PfbxPersonal> pfbxPersonals = new HashSet<PfbxPersonal>(0);
	private Set<PfbxUserOption> pfbxUserOptions = new HashSet<PfbxUserOption>(0);
	private Set<PfbxUserPrice> pfbxUserPrices = new HashSet<PfbxUserPrice>(0);

	public PfbxCustomerInfo() {
	}

	public PfbxCustomerInfo(String customerInfoId, String category, String companyName, String taxId,
			String contactName, String contactPhone, String contactCell, String websiteChineseName,
			String websiteEnglishName, String websiteDisplayUrl, String status, Date createDate, Date updateDate) {
		this.customerInfoId = customerInfoId;
		this.category = category;
		this.companyName = companyName;
		this.taxId = taxId;
		this.contactName = contactName;
		this.contactPhone = contactPhone;
		this.contactCell = contactCell;
		this.websiteChineseName = websiteChineseName;
		this.websiteEnglishName = websiteEnglishName;
		this.websiteDisplayUrl = websiteDisplayUrl;
		this.status = status;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public PfbxCustomerInfo(String customerInfoId, String memberId, Date birthday, String category, String companyName,
			String taxId, String contactName, String contactPhone, String contactCell, String websiteChineseName,
			String websiteEnglishName, String websiteDisplayUrl, String status, String statusNote, Integer adType,
			String playType, Date closeDate, Date activateDate, Date createDate, Date updateDate,
			Set<AdmPfbxBlockUrl> admPfbxBlockUrls, Set<PfbxPosition> pfbxPositions, Set<PfbxUrl> pfbxUrls,
			Set<PfbxAllowUrl> pfbxAllowUrls, Set<PfbxBonusApply> pfbxBonusApplies,
			Set<PfbxBonusApply> pfbxBonusApplies_1, Set<PfbxBank> pfbxBanks, Set<PfbxUserSample> pfbxUserSamples,
			Set<PfbxPermission> pfbxPermissions, Set<PfbxUserGroup> pfbxUserGroups, Set<PfbxUser> pfbxUsers,
			Set<PfbxCustomerInfoRefXType> pfbxCustomerInfoRefXTypes, Set<PfbxBonusDayReport> pfbxBonusDayReports,
			Set<PfbxBonusDayReport> pfbxBonusDayReports_1, Set<PfbxPersonal> pfbxPersonals,
			Set<PfbxUserOption> pfbxUserOptions, Set<PfbxUserPrice> pfbxUserPrices) {
		this.customerInfoId = customerInfoId;
		this.memberId = memberId;
		this.birthday = birthday;
		this.category = category;
		this.companyName = companyName;
		this.taxId = taxId;
		this.contactName = contactName;
		this.contactPhone = contactPhone;
		this.contactCell = contactCell;
		this.websiteChineseName = websiteChineseName;
		this.websiteEnglishName = websiteEnglishName;
		this.websiteDisplayUrl = websiteDisplayUrl;
		this.status = status;
		this.statusNote = statusNote;
		this.adType = adType;
		this.playType = playType;
		this.closeDate = closeDate;
		this.activateDate = activateDate;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.admPfbxBlockUrls = admPfbxBlockUrls;
		this.pfbxPositions = pfbxPositions;
		this.pfbxUrls = pfbxUrls;
		this.pfbxAllowUrls = pfbxAllowUrls;
		this.pfbxBonusApplies = pfbxBonusApplies;
		this.pfbxBonusApplies_1 = pfbxBonusApplies_1;
		this.pfbxBanks = pfbxBanks;
		this.pfbxUserSamples = pfbxUserSamples;
		this.pfbxPermissions = pfbxPermissions;
		this.pfbxUserGroups = pfbxUserGroups;
		this.pfbxUsers = pfbxUsers;
		this.pfbxCustomerInfoRefXTypes = pfbxCustomerInfoRefXTypes;
		this.pfbxBonusDayReports = pfbxBonusDayReports;
		this.pfbxBonusDayReports_1 = pfbxBonusDayReports_1;
		this.pfbxPersonals = pfbxPersonals;
		this.pfbxUserOptions = pfbxUserOptions;
		this.pfbxUserPrices = pfbxUserPrices;
	}

	@Id

	@Column(name = "customer_info_id", unique = true, nullable = false, length = 20)
	public String getCustomerInfoId() {
		return this.customerInfoId;
	}

	public void setCustomerInfoId(String customerInfoId) {
		this.customerInfoId = customerInfoId;
	}

	@Column(name = "member_id", length = 20)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "category", nullable = false, length = 1)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "company_name", nullable = false, length = 50)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "tax_id", nullable = false, length = 8)
	public String getTaxId() {
		return this.taxId;
	}

	public void setTaxId(String taxId) {
		this.taxId = taxId;
	}

	@Column(name = "contact_name", nullable = false, length = 20)
	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Column(name = "contact_phone", nullable = false, length = 20)
	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	@Column(name = "contact_cell", nullable = false, length = 10)
	public String getContactCell() {
		return this.contactCell;
	}

	public void setContactCell(String contactCell) {
		this.contactCell = contactCell;
	}

	@Column(name = "website_chinese_name", nullable = false, length = 50)
	public String getWebsiteChineseName() {
		return this.websiteChineseName;
	}

	public void setWebsiteChineseName(String websiteChineseName) {
		this.websiteChineseName = websiteChineseName;
	}

	@Column(name = "website_english_name", nullable = false, length = 50)
	public String getWebsiteEnglishName() {
		return this.websiteEnglishName;
	}

	public void setWebsiteEnglishName(String websiteEnglishName) {
		this.websiteEnglishName = websiteEnglishName;
	}

	@Column(name = "website_display_url", nullable = false)
	public String getWebsiteDisplayUrl() {
		return this.websiteDisplayUrl;
	}

	public void setWebsiteDisplayUrl(String websiteDisplayUrl) {
		this.websiteDisplayUrl = websiteDisplayUrl;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "status_note", length = 200)
	public String getStatusNote() {
		return this.statusNote;
	}

	public void setStatusNote(String statusNote) {
		this.statusNote = statusNote;
	}

	@Column(name = "ad_type")
	public Integer getAdType() {
		return this.adType;
	}

	public void setAdType(Integer adType) {
		this.adType = adType;
	}

	@Column(name = "play_type", length = 1)
	public String getPlayType() {
		return this.playType;
	}

	public void setPlayType(String playType) {
		this.playType = playType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "close_date", length = 10)
	public Date getCloseDate() {
		return this.closeDate;
	}

	public void setCloseDate(Date closeDate) {
		this.closeDate = closeDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "activate_date", length = 19)
	public Date getActivateDate() {
		return this.activateDate;
	}

	public void setActivateDate(Date activateDate) {
		this.activateDate = activateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<AdmPfbxBlockUrl> getAdmPfbxBlockUrls() {
		return this.admPfbxBlockUrls;
	}

	public void setAdmPfbxBlockUrls(Set<AdmPfbxBlockUrl> admPfbxBlockUrls) {
		this.admPfbxBlockUrls = admPfbxBlockUrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxPosition> getPfbxPositions() {
		return this.pfbxPositions;
	}

	public void setPfbxPositions(Set<PfbxPosition> pfbxPositions) {
		this.pfbxPositions = pfbxPositions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxUrl> getPfbxUrls() {
		return this.pfbxUrls;
	}

	public void setPfbxUrls(Set<PfbxUrl> pfbxUrls) {
		this.pfbxUrls = pfbxUrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxAllowUrl> getPfbxAllowUrls() {
		return this.pfbxAllowUrls;
	}

	public void setPfbxAllowUrls(Set<PfbxAllowUrl> pfbxAllowUrls) {
		this.pfbxAllowUrls = pfbxAllowUrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxBonusApply> getPfbxBonusApplies() {
		return this.pfbxBonusApplies;
	}

	public void setPfbxBonusApplies(Set<PfbxBonusApply> pfbxBonusApplies) {
		this.pfbxBonusApplies = pfbxBonusApplies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxBonusApply> getPfbxBonusApplies_1() {
		return this.pfbxBonusApplies_1;
	}

	public void setPfbxBonusApplies_1(Set<PfbxBonusApply> pfbxBonusApplies_1) {
		this.pfbxBonusApplies_1 = pfbxBonusApplies_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxBank> getPfbxBanks() {
		return this.pfbxBanks;
	}

	public void setPfbxBanks(Set<PfbxBank> pfbxBanks) {
		this.pfbxBanks = pfbxBanks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxUserSample> getPfbxUserSamples() {
		return this.pfbxUserSamples;
	}

	public void setPfbxUserSamples(Set<PfbxUserSample> pfbxUserSamples) {
		this.pfbxUserSamples = pfbxUserSamples;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxPermission> getPfbxPermissions() {
		return this.pfbxPermissions;
	}

	public void setPfbxPermissions(Set<PfbxPermission> pfbxPermissions) {
		this.pfbxPermissions = pfbxPermissions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxUserGroup> getPfbxUserGroups() {
		return this.pfbxUserGroups;
	}

	public void setPfbxUserGroups(Set<PfbxUserGroup> pfbxUserGroups) {
		this.pfbxUserGroups = pfbxUserGroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxUser> getPfbxUsers() {
		return this.pfbxUsers;
	}

	public void setPfbxUsers(Set<PfbxUser> pfbxUsers) {
		this.pfbxUsers = pfbxUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxCustomerInfoRefXType> getPfbxCustomerInfoRefXTypes() {
		return this.pfbxCustomerInfoRefXTypes;
	}

	public void setPfbxCustomerInfoRefXTypes(Set<PfbxCustomerInfoRefXType> pfbxCustomerInfoRefXTypes) {
		this.pfbxCustomerInfoRefXTypes = pfbxCustomerInfoRefXTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxBonusDayReport> getPfbxBonusDayReports() {
		return this.pfbxBonusDayReports;
	}

	public void setPfbxBonusDayReports(Set<PfbxBonusDayReport> pfbxBonusDayReports) {
		this.pfbxBonusDayReports = pfbxBonusDayReports;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxBonusDayReport> getPfbxBonusDayReports_1() {
		return this.pfbxBonusDayReports_1;
	}

	public void setPfbxBonusDayReports_1(Set<PfbxBonusDayReport> pfbxBonusDayReports_1) {
		this.pfbxBonusDayReports_1 = pfbxBonusDayReports_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxPersonal> getPfbxPersonals() {
		return this.pfbxPersonals;
	}

	public void setPfbxPersonals(Set<PfbxPersonal> pfbxPersonals) {
		this.pfbxPersonals = pfbxPersonals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxUserOption> getPfbxUserOptions() {
		return this.pfbxUserOptions;
	}

	public void setPfbxUserOptions(Set<PfbxUserOption> pfbxUserOptions) {
		this.pfbxUserOptions = pfbxUserOptions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxCustomerInfo")
	public Set<PfbxUserPrice> getPfbxUserPrices() {
		return this.pfbxUserPrices;
	}

	public void setPfbxUserPrices(Set<PfbxUserPrice> pfbxUserPrices) {
		this.pfbxUserPrices = pfbxUserPrices;
	}

}
