package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PfbxUserOption generated by hbm2java
 */
@Entity
@Table(name = "pfbx_user_option")
public class PfbxUserOption implements java.io.Serializable {

	private String OId;
	private PfbxCustomerInfo pfbxCustomerInfo;
	private String optionName;
	private String optionType;
	private int piositionAllowType;
	private int urlAllowType;
	private int sizeAllowType;
	private Set<PfbxOptionArea> pfbxOptionAreas = new HashSet<PfbxOptionArea>(0);
	private Set<PfbxOptionUrl> pfbxOptionUrls = new HashSet<PfbxOptionUrl>(0);
	private Set<PfbxBlockIndustry> pfbxBlockIndustries = new HashSet<PfbxBlockIndustry>(0);
	private Set<PfbxBlockCusurl> pfbxBlockCusurls = new HashSet<PfbxBlockCusurl>(0);
	private Set<PfbxAllowCusurl> pfbxAllowCusurls = new HashSet<PfbxAllowCusurl>(0);
	private Set<PfbxOptionCode> pfbxOptionCodes = new HashSet<PfbxOptionCode>(0);
	private Set<PfbxAllowIndustry> pfbxAllowIndustries = new HashSet<PfbxAllowIndustry>(0);
	private Set<PfbxOptionSize> pfbxOptionSizes = new HashSet<PfbxOptionSize>(0);

	public PfbxUserOption() {
	}

	public PfbxUserOption(String OId, PfbxCustomerInfo pfbxCustomerInfo, String optionName, int piositionAllowType,
			int urlAllowType, int sizeAllowType) {
		this.OId = OId;
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.optionName = optionName;
		this.piositionAllowType = piositionAllowType;
		this.urlAllowType = urlAllowType;
		this.sizeAllowType = sizeAllowType;
	}

	public PfbxUserOption(String OId, PfbxCustomerInfo pfbxCustomerInfo, String optionName, String optionType,
			int piositionAllowType, int urlAllowType, int sizeAllowType, Set<PfbxOptionArea> pfbxOptionAreas,
			Set<PfbxOptionUrl> pfbxOptionUrls, Set<PfbxBlockIndustry> pfbxBlockIndustries,
			Set<PfbxBlockCusurl> pfbxBlockCusurls, Set<PfbxAllowCusurl> pfbxAllowCusurls,
			Set<PfbxOptionCode> pfbxOptionCodes, Set<PfbxAllowIndustry> pfbxAllowIndustries,
			Set<PfbxOptionSize> pfbxOptionSizes) {
		this.OId = OId;
		this.pfbxCustomerInfo = pfbxCustomerInfo;
		this.optionName = optionName;
		this.optionType = optionType;
		this.piositionAllowType = piositionAllowType;
		this.urlAllowType = urlAllowType;
		this.sizeAllowType = sizeAllowType;
		this.pfbxOptionAreas = pfbxOptionAreas;
		this.pfbxOptionUrls = pfbxOptionUrls;
		this.pfbxBlockIndustries = pfbxBlockIndustries;
		this.pfbxBlockCusurls = pfbxBlockCusurls;
		this.pfbxAllowCusurls = pfbxAllowCusurls;
		this.pfbxOptionCodes = pfbxOptionCodes;
		this.pfbxAllowIndustries = pfbxAllowIndustries;
		this.pfbxOptionSizes = pfbxOptionSizes;
	}

	@Id

	@Column(name = "o_id", unique = true, nullable = false, length = 20)
	public String getOId() {
		return this.OId;
	}

	public void setOId(String OId) {
		this.OId = OId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_info_id", nullable = false)
	public PfbxCustomerInfo getPfbxCustomerInfo() {
		return this.pfbxCustomerInfo;
	}

	public void setPfbxCustomerInfo(PfbxCustomerInfo pfbxCustomerInfo) {
		this.pfbxCustomerInfo = pfbxCustomerInfo;
	}

	@Column(name = "option_name", nullable = false, length = 20)
	public String getOptionName() {
		return this.optionName;
	}

	public void setOptionName(String optionName) {
		this.optionName = optionName;
	}

	@Column(name = "option_type", length = 1)
	public String getOptionType() {
		return this.optionType;
	}

	public void setOptionType(String optionType) {
		this.optionType = optionType;
	}

	@Column(name = "piosition_allow_type", nullable = false)
	public int getPiositionAllowType() {
		return this.piositionAllowType;
	}

	public void setPiositionAllowType(int piositionAllowType) {
		this.piositionAllowType = piositionAllowType;
	}

	@Column(name = "url_allow_type", nullable = false)
	public int getUrlAllowType() {
		return this.urlAllowType;
	}

	public void setUrlAllowType(int urlAllowType) {
		this.urlAllowType = urlAllowType;
	}

	@Column(name = "size_allow_type", nullable = false)
	public int getSizeAllowType() {
		return this.sizeAllowType;
	}

	public void setSizeAllowType(int sizeAllowType) {
		this.sizeAllowType = sizeAllowType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserOption")
	public Set<PfbxOptionArea> getPfbxOptionAreas() {
		return this.pfbxOptionAreas;
	}

	public void setPfbxOptionAreas(Set<PfbxOptionArea> pfbxOptionAreas) {
		this.pfbxOptionAreas = pfbxOptionAreas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserOption")
	public Set<PfbxOptionUrl> getPfbxOptionUrls() {
		return this.pfbxOptionUrls;
	}

	public void setPfbxOptionUrls(Set<PfbxOptionUrl> pfbxOptionUrls) {
		this.pfbxOptionUrls = pfbxOptionUrls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserOption")
	public Set<PfbxBlockIndustry> getPfbxBlockIndustries() {
		return this.pfbxBlockIndustries;
	}

	public void setPfbxBlockIndustries(Set<PfbxBlockIndustry> pfbxBlockIndustries) {
		this.pfbxBlockIndustries = pfbxBlockIndustries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserOption")
	public Set<PfbxBlockCusurl> getPfbxBlockCusurls() {
		return this.pfbxBlockCusurls;
	}

	public void setPfbxBlockCusurls(Set<PfbxBlockCusurl> pfbxBlockCusurls) {
		this.pfbxBlockCusurls = pfbxBlockCusurls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserOption")
	public Set<PfbxAllowCusurl> getPfbxAllowCusurls() {
		return this.pfbxAllowCusurls;
	}

	public void setPfbxAllowCusurls(Set<PfbxAllowCusurl> pfbxAllowCusurls) {
		this.pfbxAllowCusurls = pfbxAllowCusurls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserOption")
	public Set<PfbxOptionCode> getPfbxOptionCodes() {
		return this.pfbxOptionCodes;
	}

	public void setPfbxOptionCodes(Set<PfbxOptionCode> pfbxOptionCodes) {
		this.pfbxOptionCodes = pfbxOptionCodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserOption")
	public Set<PfbxAllowIndustry> getPfbxAllowIndustries() {
		return this.pfbxAllowIndustries;
	}

	public void setPfbxAllowIndustries(Set<PfbxAllowIndustry> pfbxAllowIndustries) {
		this.pfbxAllowIndustries = pfbxAllowIndustries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pfbxUserOption")
	public Set<PfbxOptionSize> getPfbxOptionSizes() {
		return this.pfbxOptionSizes;
	}

	public void setPfbxOptionSizes(Set<PfbxOptionSize> pfbxOptionSizes) {
		this.pfbxOptionSizes = pfbxOptionSizes;
	}

}
