package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfdAdScreenshotShoted generated by hbm2java
 */
@Entity
@Table(name = "pfd_ad_screenshot_shoted")
public class PfdAdScreenshotShoted implements java.io.Serializable {

	private Integer id;
	private String adSeq;
	private Date adUpdateTime;
	private Date createTime;
	private Date updateTime;

	public PfdAdScreenshotShoted() {
	}

	public PfdAdScreenshotShoted(String adSeq, Date adUpdateTime, Date createTime, Date updateTime) {
		this.adSeq = adSeq;
		this.adUpdateTime = adUpdateTime;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ad_seq", nullable = false, length = 20)
	public String getAdSeq() {
		return this.adSeq;
	}

	public void setAdSeq(String adSeq) {
		this.adSeq = adSeq;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ad_update_time", nullable = false, length = 19)
	public Date getAdUpdateTime() {
		return this.adUpdateTime;
	}

	public void setAdUpdateTime(Date adUpdateTime) {
		this.adUpdateTime = adUpdateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
