package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfdAdScreenshot generated by hbm2java
 */
@Entity
@Table(name = "pfd_ad_screenshot")
public class PfdAdScreenshot implements java.io.Serializable {

	private Integer id;
	private String pfdCustomerInfoId;
	private String pfpCustomerInfoId;
	private String adSeq;
	private String adActionSeq;
	private String adGroupSeq;
	private int adType;
	private String typeCname;
	private int adDevice;
	private String deviceCname;
	private String templateProductSeq;
	private String adWidth;
	private String adHeight;
	private String url;
	private String referer;
	private int adPv;
	private String imgName;
	private String adOrWeb;
	private String status;
	private Date createTime;
	private Date updateTime;

	public PfdAdScreenshot() {
	}

	public PfdAdScreenshot(String pfdCustomerInfoId, String pfpCustomerInfoId, String adSeq, String adActionSeq,
			String adGroupSeq, int adType, String typeCname, int adDevice, String deviceCname,
			String templateProductSeq, String adWidth, String adHeight, String url, String referer, int adPv,
			String imgName, String adOrWeb, String status, Date createTime, Date updateTime) {
		this.pfdCustomerInfoId = pfdCustomerInfoId;
		this.pfpCustomerInfoId = pfpCustomerInfoId;
		this.adSeq = adSeq;
		this.adActionSeq = adActionSeq;
		this.adGroupSeq = adGroupSeq;
		this.adType = adType;
		this.typeCname = typeCname;
		this.adDevice = adDevice;
		this.deviceCname = deviceCname;
		this.templateProductSeq = templateProductSeq;
		this.adWidth = adWidth;
		this.adHeight = adHeight;
		this.url = url;
		this.referer = referer;
		this.adPv = adPv;
		this.imgName = imgName;
		this.adOrWeb = adOrWeb;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "pfd_customer_info_id", nullable = false, length = 20)
	public String getPfdCustomerInfoId() {
		return this.pfdCustomerInfoId;
	}

	public void setPfdCustomerInfoId(String pfdCustomerInfoId) {
		this.pfdCustomerInfoId = pfdCustomerInfoId;
	}

	@Column(name = "pfp_customer_info_id", nullable = false, length = 20)
	public String getPfpCustomerInfoId() {
		return this.pfpCustomerInfoId;
	}

	public void setPfpCustomerInfoId(String pfpCustomerInfoId) {
		this.pfpCustomerInfoId = pfpCustomerInfoId;
	}

	@Column(name = "ad_seq", nullable = false, length = 20)
	public String getAdSeq() {
		return this.adSeq;
	}

	public void setAdSeq(String adSeq) {
		this.adSeq = adSeq;
	}

	@Column(name = "ad_action_seq", nullable = false, length = 20)
	public String getAdActionSeq() {
		return this.adActionSeq;
	}

	public void setAdActionSeq(String adActionSeq) {
		this.adActionSeq = adActionSeq;
	}

	@Column(name = "ad_group_seq", nullable = false, length = 20)
	public String getAdGroupSeq() {
		return this.adGroupSeq;
	}

	public void setAdGroupSeq(String adGroupSeq) {
		this.adGroupSeq = adGroupSeq;
	}

	@Column(name = "ad_type", nullable = false)
	public int getAdType() {
		return this.adType;
	}

	public void setAdType(int adType) {
		this.adType = adType;
	}

	@Column(name = "typeCName", nullable = false, length = 20)
	public String getTypeCname() {
		return this.typeCname;
	}

	public void setTypeCname(String typeCname) {
		this.typeCname = typeCname;
	}

	@Column(name = "ad_device", nullable = false)
	public int getAdDevice() {
		return this.adDevice;
	}

	public void setAdDevice(int adDevice) {
		this.adDevice = adDevice;
	}

	@Column(name = "deviceCName", nullable = false, length = 20)
	public String getDeviceCname() {
		return this.deviceCname;
	}

	public void setDeviceCname(String deviceCname) {
		this.deviceCname = deviceCname;
	}

	@Column(name = "template_product_seq", nullable = false, length = 50)
	public String getTemplateProductSeq() {
		return this.templateProductSeq;
	}

	public void setTemplateProductSeq(String templateProductSeq) {
		this.templateProductSeq = templateProductSeq;
	}

	@Column(name = "ad_width", nullable = false, length = 5)
	public String getAdWidth() {
		return this.adWidth;
	}

	public void setAdWidth(String adWidth) {
		this.adWidth = adWidth;
	}

	@Column(name = "ad_height", nullable = false, length = 5)
	public String getAdHeight() {
		return this.adHeight;
	}

	public void setAdHeight(String adHeight) {
		this.adHeight = adHeight;
	}

	@Column(name = "url", nullable = false, length = 1024)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "referer", nullable = false, length = 1024)
	public String getReferer() {
		return this.referer;
	}

	public void setReferer(String referer) {
		this.referer = referer;
	}

	@Column(name = "adPv", nullable = false)
	public int getAdPv() {
		return this.adPv;
	}

	public void setAdPv(int adPv) {
		this.adPv = adPv;
	}

	@Column(name = "imgName", nullable = false, length = 1024)
	public String getImgName() {
		return this.imgName;
	}

	public void setImgName(String imgName) {
		this.imgName = imgName;
	}

	@Column(name = "ad_or_web", nullable = false, length = 10)
	public String getAdOrWeb() {
		return this.adOrWeb;
	}

	public void setAdOrWeb(String adOrWeb) {
		this.adOrWeb = adOrWeb;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
