package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfdAdScreenshotPagemenu generated by hbm2java
 */
@Entity
@Table(name = "pfd_ad_screenshot_pagemenu")
public class PfdAdScreenshotPagemenu implements java.io.Serializable {

	private Integer id;
	private String seq;
	private String name;
	private String url;
	private String width;
	private String height;
	private int adDevice;
	private String deviceFlag;
	private String headTxt;
	private String footTxt;
	private String replacedTxt;
	private String akbAdFlag;
	private String htmlCodeName;
	private String status;
	private Date createTime;
	private Date updateTime;

	public PfdAdScreenshotPagemenu() {
	}

	public PfdAdScreenshotPagemenu(String seq, String name, String url, String width, String height, int adDevice,
			String deviceFlag, String headTxt, String footTxt, String replacedTxt, String akbAdFlag,
			String htmlCodeName, String status, Date createTime, Date updateTime) {
		this.seq = seq;
		this.name = name;
		this.url = url;
		this.width = width;
		this.height = height;
		this.adDevice = adDevice;
		this.deviceFlag = deviceFlag;
		this.headTxt = headTxt;
		this.footTxt = footTxt;
		this.replacedTxt = replacedTxt;
		this.akbAdFlag = akbAdFlag;
		this.htmlCodeName = htmlCodeName;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "seq", nullable = false, length = 50)
	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", nullable = false, length = 512)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "width", nullable = false, length = 5)
	public String getWidth() {
		return this.width;
	}

	public void setWidth(String width) {
		this.width = width;
	}

	@Column(name = "height", nullable = false, length = 5)
	public String getHeight() {
		return this.height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	@Column(name = "ad_device", nullable = false)
	public int getAdDevice() {
		return this.adDevice;
	}

	public void setAdDevice(int adDevice) {
		this.adDevice = adDevice;
	}

	@Column(name = "device_flag", nullable = false, length = 10)
	public String getDeviceFlag() {
		return this.deviceFlag;
	}

	public void setDeviceFlag(String deviceFlag) {
		this.deviceFlag = deviceFlag;
	}

	@Column(name = "headTxt", nullable = false, length = 512)
	public String getHeadTxt() {
		return this.headTxt;
	}

	public void setHeadTxt(String headTxt) {
		this.headTxt = headTxt;
	}

	@Column(name = "footTxt", nullable = false, length = 128)
	public String getFootTxt() {
		return this.footTxt;
	}

	public void setFootTxt(String footTxt) {
		this.footTxt = footTxt;
	}

	@Column(name = "replacedTxt", nullable = false, length = 4096)
	public String getReplacedTxt() {
		return this.replacedTxt;
	}

	public void setReplacedTxt(String replacedTxt) {
		this.replacedTxt = replacedTxt;
	}

	@Column(name = "akbAdFlag", nullable = false, length = 100)
	public String getAkbAdFlag() {
		return this.akbAdFlag;
	}

	public void setAkbAdFlag(String akbAdFlag) {
		this.akbAdFlag = akbAdFlag;
	}

	@Column(name = "htmlCodeName", nullable = false, length = 50)
	public String getHtmlCodeName() {
		return this.htmlCodeName;
	}

	public void setHtmlCodeName(String htmlCodeName) {
		this.htmlCodeName = htmlCodeName;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
