package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfdBonusInvoice generated by hbm2java
 */
@Entity
@Table(name = "pfd_bonus_invoice")
public class PfdBonusInvoice implements java.io.Serializable {

	private Integer id;
	private PfdContract pfdContract;
	private String payType;
	private Date recordDate;
	private int closeYear;
	private int closeMonth;
	private float totalAdClkPrice;
	private float totalBonus;
	private String bonusType;
	private String download;
	private String billStatus;
	private String billNote;
	private String financeInvoiceSno;
	private Date financeInvoiceDate;
	private Float financeInvoiceMoney;
	private Date financePayDate;
	private String pfdInvoiceSno;
	private Date pfdInvoiceDate;
	private Float pfdInvoiceMoney;
	private String pfdPayCategory;
	private String pfdCheckSno;
	private Date pfdCheckCloseDate;
	private Float debitMoney;
	private Date debitDate;
	private Date balanceDate;
	private Integer payId;
	private Date createDate;
	private Date updateDate;

	public PfdBonusInvoice() {
	}

	public PfdBonusInvoice(PfdContract pfdContract, String payType, Date recordDate, int closeYear, int closeMonth,
			float totalAdClkPrice, float totalBonus, String download, String billStatus, Date createDate,
			Date updateDate) {
		this.pfdContract = pfdContract;
		this.payType = payType;
		this.recordDate = recordDate;
		this.closeYear = closeYear;
		this.closeMonth = closeMonth;
		this.totalAdClkPrice = totalAdClkPrice;
		this.totalBonus = totalBonus;
		this.download = download;
		this.billStatus = billStatus;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public PfdBonusInvoice(PfdContract pfdContract, String payType, Date recordDate, int closeYear, int closeMonth,
			float totalAdClkPrice, float totalBonus, String bonusType, String download, String billStatus,
			String billNote, String financeInvoiceSno, Date financeInvoiceDate, Float financeInvoiceMoney,
			Date financePayDate, String pfdInvoiceSno, Date pfdInvoiceDate, Float pfdInvoiceMoney,
			String pfdPayCategory, String pfdCheckSno, Date pfdCheckCloseDate, Float debitMoney, Date debitDate,
			Date balanceDate, Integer payId, Date createDate, Date updateDate) {
		this.pfdContract = pfdContract;
		this.payType = payType;
		this.recordDate = recordDate;
		this.closeYear = closeYear;
		this.closeMonth = closeMonth;
		this.totalAdClkPrice = totalAdClkPrice;
		this.totalBonus = totalBonus;
		this.bonusType = bonusType;
		this.download = download;
		this.billStatus = billStatus;
		this.billNote = billNote;
		this.financeInvoiceSno = financeInvoiceSno;
		this.financeInvoiceDate = financeInvoiceDate;
		this.financeInvoiceMoney = financeInvoiceMoney;
		this.financePayDate = financePayDate;
		this.pfdInvoiceSno = pfdInvoiceSno;
		this.pfdInvoiceDate = pfdInvoiceDate;
		this.pfdInvoiceMoney = pfdInvoiceMoney;
		this.pfdPayCategory = pfdPayCategory;
		this.pfdCheckSno = pfdCheckSno;
		this.pfdCheckCloseDate = pfdCheckCloseDate;
		this.debitMoney = debitMoney;
		this.debitDate = debitDate;
		this.balanceDate = balanceDate;
		this.payId = payId;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfd_contract", nullable = false)
	public PfdContract getPfdContract() {
		return this.pfdContract;
	}

	public void setPfdContract(PfdContract pfdContract) {
		this.pfdContract = pfdContract;
	}

	@Column(name = "pay_type", nullable = false, length = 1)
	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "record_date", nullable = false, length = 10)
	public Date getRecordDate() {
		return this.recordDate;
	}

	public void setRecordDate(Date recordDate) {
		this.recordDate = recordDate;
	}

	@Column(name = "close_year", nullable = false)
	public int getCloseYear() {
		return this.closeYear;
	}

	public void setCloseYear(int closeYear) {
		this.closeYear = closeYear;
	}

	@Column(name = "close_month", nullable = false)
	public int getCloseMonth() {
		return this.closeMonth;
	}

	public void setCloseMonth(int closeMonth) {
		this.closeMonth = closeMonth;
	}

	@Column(name = "total_ad_clk_price", nullable = false, precision = 10)
	public float getTotalAdClkPrice() {
		return this.totalAdClkPrice;
	}

	public void setTotalAdClkPrice(float totalAdClkPrice) {
		this.totalAdClkPrice = totalAdClkPrice;
	}

	@Column(name = "total_bonus", nullable = false, precision = 10)
	public float getTotalBonus() {
		return this.totalBonus;
	}

	public void setTotalBonus(float totalBonus) {
		this.totalBonus = totalBonus;
	}

	@Column(name = "bonus_type", length = 1)
	public String getBonusType() {
		return this.bonusType;
	}

	public void setBonusType(String bonusType) {
		this.bonusType = bonusType;
	}

	@Column(name = "download", nullable = false, length = 1)
	public String getDownload() {
		return this.download;
	}

	public void setDownload(String download) {
		this.download = download;
	}

	@Column(name = "bill_status", nullable = false, length = 2)
	public String getBillStatus() {
		return this.billStatus;
	}

	public void setBillStatus(String billStatus) {
		this.billStatus = billStatus;
	}

	@Column(name = "bill_note", length = 200)
	public String getBillNote() {
		return this.billNote;
	}

	public void setBillNote(String billNote) {
		this.billNote = billNote;
	}

	@Column(name = "finance_invoice_sno", length = 20)
	public String getFinanceInvoiceSno() {
		return this.financeInvoiceSno;
	}

	public void setFinanceInvoiceSno(String financeInvoiceSno) {
		this.financeInvoiceSno = financeInvoiceSno;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "finance_invoice_date", length = 10)
	public Date getFinanceInvoiceDate() {
		return this.financeInvoiceDate;
	}

	public void setFinanceInvoiceDate(Date financeInvoiceDate) {
		this.financeInvoiceDate = financeInvoiceDate;
	}

	@Column(name = "finance_invoice_money", precision = 10)
	public Float getFinanceInvoiceMoney() {
		return this.financeInvoiceMoney;
	}

	public void setFinanceInvoiceMoney(Float financeInvoiceMoney) {
		this.financeInvoiceMoney = financeInvoiceMoney;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "finance_pay_date", length = 10)
	public Date getFinancePayDate() {
		return this.financePayDate;
	}

	public void setFinancePayDate(Date financePayDate) {
		this.financePayDate = financePayDate;
	}

	@Column(name = "pfd_invoice_sno", length = 20)
	public String getPfdInvoiceSno() {
		return this.pfdInvoiceSno;
	}

	public void setPfdInvoiceSno(String pfdInvoiceSno) {
		this.pfdInvoiceSno = pfdInvoiceSno;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pfd_invoice_date", length = 10)
	public Date getPfdInvoiceDate() {
		return this.pfdInvoiceDate;
	}

	public void setPfdInvoiceDate(Date pfdInvoiceDate) {
		this.pfdInvoiceDate = pfdInvoiceDate;
	}

	@Column(name = "pfd_invoice_money", precision = 10)
	public Float getPfdInvoiceMoney() {
		return this.pfdInvoiceMoney;
	}

	public void setPfdInvoiceMoney(Float pfdInvoiceMoney) {
		this.pfdInvoiceMoney = pfdInvoiceMoney;
	}

	@Column(name = "pfd_pay_category", length = 1)
	public String getPfdPayCategory() {
		return this.pfdPayCategory;
	}

	public void setPfdPayCategory(String pfdPayCategory) {
		this.pfdPayCategory = pfdPayCategory;
	}

	@Column(name = "pfd_check_sno", length = 20)
	public String getPfdCheckSno() {
		return this.pfdCheckSno;
	}

	public void setPfdCheckSno(String pfdCheckSno) {
		this.pfdCheckSno = pfdCheckSno;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "pfd_check_close_date", length = 10)
	public Date getPfdCheckCloseDate() {
		return this.pfdCheckCloseDate;
	}

	public void setPfdCheckCloseDate(Date pfdCheckCloseDate) {
		this.pfdCheckCloseDate = pfdCheckCloseDate;
	}

	@Column(name = "debit_money", precision = 10)
	public Float getDebitMoney() {
		return this.debitMoney;
	}

	public void setDebitMoney(Float debitMoney) {
		this.debitMoney = debitMoney;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "debit_date", length = 10)
	public Date getDebitDate() {
		return this.debitDate;
	}

	public void setDebitDate(Date debitDate) {
		this.debitDate = debitDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "balance_date", length = 10)
	public Date getBalanceDate() {
		return this.balanceDate;
	}

	public void setBalanceDate(Date balanceDate) {
		this.balanceDate = balanceDate;
	}

	@Column(name = "pay_id")
	public Integer getPayId() {
		return this.payId;
	}

	public void setPayId(Integer payId) {
		this.payId = payId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
