package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfdBonusItemSet generated by hbm2java
 */
@Entity
@Table(name = "pfd_bonus_item_set")
public class PfdBonusItemSet implements java.io.Serializable {

	private Integer id;
	private PfdContract pfdContract;
	private String bonusItem;
	private String bonusType;
	private int subItemId;
	private Date createDate;
	private Date updateDate;

	public PfdBonusItemSet() {
	}

	public PfdBonusItemSet(PfdContract pfdContract, String bonusItem, String bonusType, int subItemId, Date createDate,
			Date updateDate) {
		this.pfdContract = pfdContract;
		this.bonusItem = bonusItem;
		this.bonusType = bonusType;
		this.subItemId = subItemId;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfd_contract", nullable = false)
	public PfdContract getPfdContract() {
		return this.pfdContract;
	}

	public void setPfdContract(PfdContract pfdContract) {
		this.pfdContract = pfdContract;
	}

	@Column(name = "bonus_item", nullable = false, length = 5)
	public String getBonusItem() {
		return this.bonusItem;
	}

	public void setBonusItem(String bonusItem) {
		this.bonusItem = bonusItem;
	}

	@Column(name = "bonus_type", nullable = false, length = 5)
	public String getBonusType() {
		return this.bonusType;
	}

	public void setBonusType(String bonusType) {
		this.bonusType = bonusType;
	}

	@Column(name = "sub_item_id", nullable = false)
	public int getSubItemId() {
		return this.subItemId;
	}

	public void setSubItemId(int subItemId) {
		this.subItemId = subItemId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
