package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfdBonusDayReport generated by hbm2java
 */
@Entity
@Table(name = "pfd_bonus_day_report")
public class PfdBonusDayReport implements java.io.Serializable {

	private Integer id;
	private PfdCustomerInfo pfdCustomerInfo;
	private Date reportDate;
	private float saveClkPrice;
	private Float freeClkPrice;
	private Float postpaidClkPrice;
	private Float saveBouns;
	private Float freeBonus;
	private Float postpaidBonus;
	private float pfdClkPrice;
	private float pfdMonthPercent;
	private float pfdBonusMoney;
	private Date createDate;

	public PfdBonusDayReport() {
	}

	public PfdBonusDayReport(PfdCustomerInfo pfdCustomerInfo, Date reportDate, float saveClkPrice, float pfdClkPrice,
			float pfdMonthPercent, float pfdBonusMoney, Date createDate) {
		this.pfdCustomerInfo = pfdCustomerInfo;
		this.reportDate = reportDate;
		this.saveClkPrice = saveClkPrice;
		this.pfdClkPrice = pfdClkPrice;
		this.pfdMonthPercent = pfdMonthPercent;
		this.pfdBonusMoney = pfdBonusMoney;
		this.createDate = createDate;
	}

	public PfdBonusDayReport(PfdCustomerInfo pfdCustomerInfo, Date reportDate, float saveClkPrice, Float freeClkPrice,
			Float postpaidClkPrice, Float saveBouns, Float freeBonus, Float postpaidBonus, float pfdClkPrice,
			float pfdMonthPercent, float pfdBonusMoney, Date createDate) {
		this.pfdCustomerInfo = pfdCustomerInfo;
		this.reportDate = reportDate;
		this.saveClkPrice = saveClkPrice;
		this.freeClkPrice = freeClkPrice;
		this.postpaidClkPrice = postpaidClkPrice;
		this.saveBouns = saveBouns;
		this.freeBonus = freeBonus;
		this.postpaidBonus = postpaidBonus;
		this.pfdClkPrice = pfdClkPrice;
		this.pfdMonthPercent = pfdMonthPercent;
		this.pfdBonusMoney = pfdBonusMoney;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfd_id", nullable = false)
	public PfdCustomerInfo getPfdCustomerInfo() {
		return this.pfdCustomerInfo;
	}

	public void setPfdCustomerInfo(PfdCustomerInfo pfdCustomerInfo) {
		this.pfdCustomerInfo = pfdCustomerInfo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "report_date", nullable = false, length = 10)
	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	@Column(name = "save_clk_price", nullable = false, precision = 10)
	public float getSaveClkPrice() {
		return this.saveClkPrice;
	}

	public void setSaveClkPrice(float saveClkPrice) {
		this.saveClkPrice = saveClkPrice;
	}

	@Column(name = "free_clk_price", precision = 10)
	public Float getFreeClkPrice() {
		return this.freeClkPrice;
	}

	public void setFreeClkPrice(Float freeClkPrice) {
		this.freeClkPrice = freeClkPrice;
	}

	@Column(name = "postpaid_clk_price", precision = 10)
	public Float getPostpaidClkPrice() {
		return this.postpaidClkPrice;
	}

	public void setPostpaidClkPrice(Float postpaidClkPrice) {
		this.postpaidClkPrice = postpaidClkPrice;
	}

	@Column(name = "save_bouns", precision = 10)
	public Float getSaveBouns() {
		return this.saveBouns;
	}

	public void setSaveBouns(Float saveBouns) {
		this.saveBouns = saveBouns;
	}

	@Column(name = "free_bonus", precision = 10)
	public Float getFreeBonus() {
		return this.freeBonus;
	}

	public void setFreeBonus(Float freeBonus) {
		this.freeBonus = freeBonus;
	}

	@Column(name = "postpaid_bonus", precision = 10)
	public Float getPostpaidBonus() {
		return this.postpaidBonus;
	}

	public void setPostpaidBonus(Float postpaidBonus) {
		this.postpaidBonus = postpaidBonus;
	}

	@Column(name = "pfd_clk_price", nullable = false, precision = 10)
	public float getPfdClkPrice() {
		return this.pfdClkPrice;
	}

	public void setPfdClkPrice(float pfdClkPrice) {
		this.pfdClkPrice = pfdClkPrice;
	}

	@Column(name = "pfd_month_percent", nullable = false, precision = 5)
	public float getPfdMonthPercent() {
		return this.pfdMonthPercent;
	}

	public void setPfdMonthPercent(float pfdMonthPercent) {
		this.pfdMonthPercent = pfdMonthPercent;
	}

	@Column(name = "pfd_bonus_money", nullable = false, precision = 10)
	public float getPfdBonusMoney() {
		return this.pfdBonusMoney;
	}

	public void setPfdBonusMoney(float pfdBonusMoney) {
		this.pfdBonusMoney = pfdBonusMoney;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
