package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfdBonusRecord generated by hbm2java
 */
@Entity
@Table(name = "pfd_bonus_record")
public class PfdBonusRecord implements java.io.Serializable {

	private Integer id;
	private PfdContract pfdContract;
	private String payType;
	private int year;
	private int month;
	private int quarter;
	private int closeYear;
	private int closeMonth;
	private String bonusItem;
	private String bonusName;
	private Date startDate;
	private Date endDate;
	private float nowClkPrice;
	private float nextClkPrice;
	private float nowPercent;
	private float nextPercent;
	private float deductBonus;
	private int nowAmount;
	private int nextAmount;
	private float nowBonus;
	private float nextBonus;
	private String reportActoin;
	private String bonusNote;
	private Date createDate;
	private Date updateDate;

	public PfdBonusRecord() {
	}

	public PfdBonusRecord(PfdContract pfdContract, String payType, int year, int month, int quarter, int closeYear,
			int closeMonth, String bonusItem, String bonusName, Date startDate, Date endDate, float nowClkPrice,
			float nextClkPrice, float nowPercent, float nextPercent, float deductBonus, int nowAmount, int nextAmount,
			float nowBonus, float nextBonus, String reportActoin, String bonusNote, Date createDate, Date updateDate) {
		this.pfdContract = pfdContract;
		this.payType = payType;
		this.year = year;
		this.month = month;
		this.quarter = quarter;
		this.closeYear = closeYear;
		this.closeMonth = closeMonth;
		this.bonusItem = bonusItem;
		this.bonusName = bonusName;
		this.startDate = startDate;
		this.endDate = endDate;
		this.nowClkPrice = nowClkPrice;
		this.nextClkPrice = nextClkPrice;
		this.nowPercent = nowPercent;
		this.nextPercent = nextPercent;
		this.deductBonus = deductBonus;
		this.nowAmount = nowAmount;
		this.nextAmount = nextAmount;
		this.nowBonus = nowBonus;
		this.nextBonus = nextBonus;
		this.reportActoin = reportActoin;
		this.bonusNote = bonusNote;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfd_contract", nullable = false)
	public PfdContract getPfdContract() {
		return this.pfdContract;
	}

	public void setPfdContract(PfdContract pfdContract) {
		this.pfdContract = pfdContract;
	}

	@Column(name = "pay_type", nullable = false, length = 1)
	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	@Column(name = "year", nullable = false)
	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	@Column(name = "month", nullable = false)
	public int getMonth() {
		return this.month;
	}

	public void setMonth(int month) {
		this.month = month;
	}

	@Column(name = "quarter", nullable = false)
	public int getQuarter() {
		return this.quarter;
	}

	public void setQuarter(int quarter) {
		this.quarter = quarter;
	}

	@Column(name = "close_year", nullable = false)
	public int getCloseYear() {
		return this.closeYear;
	}

	public void setCloseYear(int closeYear) {
		this.closeYear = closeYear;
	}

	@Column(name = "close_month", nullable = false)
	public int getCloseMonth() {
		return this.closeMonth;
	}

	public void setCloseMonth(int closeMonth) {
		this.closeMonth = closeMonth;
	}

	@Column(name = "bonus_item", nullable = false, length = 5)
	public String getBonusItem() {
		return this.bonusItem;
	}

	public void setBonusItem(String bonusItem) {
		this.bonusItem = bonusItem;
	}

	@Column(name = "bonus_name", nullable = false, length = 100)
	public String getBonusName() {
		return this.bonusName;
	}

	public void setBonusName(String bonusName) {
		this.bonusName = bonusName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "now_clk_price", nullable = false, precision = 10)
	public float getNowClkPrice() {
		return this.nowClkPrice;
	}

	public void setNowClkPrice(float nowClkPrice) {
		this.nowClkPrice = nowClkPrice;
	}

	@Column(name = "next_clk_price", nullable = false, precision = 10)
	public float getNextClkPrice() {
		return this.nextClkPrice;
	}

	public void setNextClkPrice(float nextClkPrice) {
		this.nextClkPrice = nextClkPrice;
	}

	@Column(name = "now_percent", nullable = false, precision = 10)
	public float getNowPercent() {
		return this.nowPercent;
	}

	public void setNowPercent(float nowPercent) {
		this.nowPercent = nowPercent;
	}

	@Column(name = "next_percent", nullable = false, precision = 10)
	public float getNextPercent() {
		return this.nextPercent;
	}

	public void setNextPercent(float nextPercent) {
		this.nextPercent = nextPercent;
	}

	@Column(name = "deduct_bonus", nullable = false, precision = 10)
	public float getDeductBonus() {
		return this.deductBonus;
	}

	public void setDeductBonus(float deductBonus) {
		this.deductBonus = deductBonus;
	}

	@Column(name = "now_amount", nullable = false)
	public int getNowAmount() {
		return this.nowAmount;
	}

	public void setNowAmount(int nowAmount) {
		this.nowAmount = nowAmount;
	}

	@Column(name = "next_amount", nullable = false)
	public int getNextAmount() {
		return this.nextAmount;
	}

	public void setNextAmount(int nextAmount) {
		this.nextAmount = nextAmount;
	}

	@Column(name = "now_bonus", nullable = false, precision = 10)
	public float getNowBonus() {
		return this.nowBonus;
	}

	public void setNowBonus(float nowBonus) {
		this.nowBonus = nowBonus;
	}

	@Column(name = "next_bonus", nullable = false, precision = 10)
	public float getNextBonus() {
		return this.nextBonus;
	}

	public void setNextBonus(float nextBonus) {
		this.nextBonus = nextBonus;
	}

	@Column(name = "report_actoin", nullable = false, length = 500)
	public String getReportActoin() {
		return this.reportActoin;
	}

	public void setReportActoin(String reportActoin) {
		this.reportActoin = reportActoin;
	}

	@Column(name = "bonus_note", nullable = false, length = 500)
	public String getBonusNote() {
		return this.bonusNote;
	}

	public void setBonusNote(String bonusNote) {
		this.bonusNote = bonusNote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
