package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfdVirtualRecord generated by hbm2java
 */
@Entity
@Table(name = "pfd_virtual_record")
public class PfdVirtualRecord implements java.io.Serializable {

	private String recordId;
	private PfpCustomerInfo pfpCustomerInfo;
	private PfdCustomerInfo pfdCustomerInfo;
	private PfdContract pfdContract;
	private float addMoney;
	private Date addDate;
	private Date createDate;
	private Date updateDate;

	public PfdVirtualRecord() {
	}

	public PfdVirtualRecord(String recordId, PfpCustomerInfo pfpCustomerInfo, PfdCustomerInfo pfdCustomerInfo,
			PfdContract pfdContract, float addMoney, Date addDate, Date createDate, Date updateDate) {
		this.recordId = recordId;
		this.pfpCustomerInfo = pfpCustomerInfo;
		this.pfdCustomerInfo = pfdCustomerInfo;
		this.pfdContract = pfdContract;
		this.addMoney = addMoney;
		this.addDate = addDate;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id

	@Column(name = "record_id", unique = true, nullable = false, length = 20)
	public String getRecordId() {
		return this.recordId;
	}

	public void setRecordId(String recordId) {
		this.recordId = recordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfp_customer_info_id", nullable = false)
	public PfpCustomerInfo getPfpCustomerInfo() {
		return this.pfpCustomerInfo;
	}

	public void setPfpCustomerInfo(PfpCustomerInfo pfpCustomerInfo) {
		this.pfpCustomerInfo = pfpCustomerInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfd_customer_info_id", nullable = false)
	public PfdCustomerInfo getPfdCustomerInfo() {
		return this.pfdCustomerInfo;
	}

	public void setPfdCustomerInfo(PfdCustomerInfo pfdCustomerInfo) {
		this.pfdCustomerInfo = pfdCustomerInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pfd_contract", nullable = false)
	public PfdContract getPfdContract() {
		return this.pfdContract;
	}

	public void setPfdContract(PfdContract pfdContract) {
		this.pfdContract = pfdContract;
	}

	@Column(name = "add_money", nullable = false, precision = 10)
	public float getAddMoney() {
		return this.addMoney;
	}

	public void setAddMoney(float addMoney) {
		this.addMoney = addMoney;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "add_date", nullable = false, length = 10)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
