package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpAdPvclkScreenshot generated by hbm2java
 */
@Entity
@Table(name = "pfp_ad_pvclk_screenshot")
public class PfpAdPvclkScreenshot implements java.io.Serializable {

	private Integer adPvclkScreenshotSeq;
	private String customerInfoId;
	private String pfdCustomerInfoId;
	private String adSeq;
	private String adGroupSeq;
	private String adActionSeq;
	private int adType;
	private Date adPvclkDate;
	private int adPvclkTime;
	private String templateProductSeq;
	private String adUrl;
	private String referer;
	private int adPv;
	private Date updateTime;
	private Date createTime;

	public PfpAdPvclkScreenshot() {
	}

	public PfpAdPvclkScreenshot(String customerInfoId, String adSeq, int adType, Date adPvclkDate, int adPvclkTime,
			String templateProductSeq, String adUrl, String referer, int adPv, Date updateTime, Date createTime) {
		this.customerInfoId = customerInfoId;
		this.adSeq = adSeq;
		this.adType = adType;
		this.adPvclkDate = adPvclkDate;
		this.adPvclkTime = adPvclkTime;
		this.templateProductSeq = templateProductSeq;
		this.adUrl = adUrl;
		this.referer = referer;
		this.adPv = adPv;
		this.updateTime = updateTime;
		this.createTime = createTime;
	}

	public PfpAdPvclkScreenshot(String customerInfoId, String pfdCustomerInfoId, String adSeq, String adGroupSeq,
			String adActionSeq, int adType, Date adPvclkDate, int adPvclkTime, String templateProductSeq, String adUrl,
			String referer, int adPv, Date updateTime, Date createTime) {
		this.customerInfoId = customerInfoId;
		this.pfdCustomerInfoId = pfdCustomerInfoId;
		this.adSeq = adSeq;
		this.adGroupSeq = adGroupSeq;
		this.adActionSeq = adActionSeq;
		this.adType = adType;
		this.adPvclkDate = adPvclkDate;
		this.adPvclkTime = adPvclkTime;
		this.templateProductSeq = templateProductSeq;
		this.adUrl = adUrl;
		this.referer = referer;
		this.adPv = adPv;
		this.updateTime = updateTime;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ad_pvclk_screenshot_seq", unique = true, nullable = false)
	public Integer getAdPvclkScreenshotSeq() {
		return this.adPvclkScreenshotSeq;
	}

	public void setAdPvclkScreenshotSeq(Integer adPvclkScreenshotSeq) {
		this.adPvclkScreenshotSeq = adPvclkScreenshotSeq;
	}

	@Column(name = "customer_info_id", nullable = false, length = 20)
	public String getCustomerInfoId() {
		return this.customerInfoId;
	}

	public void setCustomerInfoId(String customerInfoId) {
		this.customerInfoId = customerInfoId;
	}

	@Column(name = "pfd_customer_info_id", length = 20)
	public String getPfdCustomerInfoId() {
		return this.pfdCustomerInfoId;
	}

	public void setPfdCustomerInfoId(String pfdCustomerInfoId) {
		this.pfdCustomerInfoId = pfdCustomerInfoId;
	}

	@Column(name = "ad_seq", nullable = false, length = 20)
	public String getAdSeq() {
		return this.adSeq;
	}

	public void setAdSeq(String adSeq) {
		this.adSeq = adSeq;
	}

	@Column(name = "ad_group_seq", length = 20)
	public String getAdGroupSeq() {
		return this.adGroupSeq;
	}

	public void setAdGroupSeq(String adGroupSeq) {
		this.adGroupSeq = adGroupSeq;
	}

	@Column(name = "ad_action_seq", length = 20)
	public String getAdActionSeq() {
		return this.adActionSeq;
	}

	public void setAdActionSeq(String adActionSeq) {
		this.adActionSeq = adActionSeq;
	}

	@Column(name = "ad_type", nullable = false)
	public int getAdType() {
		return this.adType;
	}

	public void setAdType(int adType) {
		this.adType = adType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ad_pvclk_date", nullable = false, length = 10)
	public Date getAdPvclkDate() {
		return this.adPvclkDate;
	}

	public void setAdPvclkDate(Date adPvclkDate) {
		this.adPvclkDate = adPvclkDate;
	}

	@Column(name = "ad_pvclk_time", nullable = false)
	public int getAdPvclkTime() {
		return this.adPvclkTime;
	}

	public void setAdPvclkTime(int adPvclkTime) {
		this.adPvclkTime = adPvclkTime;
	}

	@Column(name = "template_product_seq", nullable = false, length = 20)
	public String getTemplateProductSeq() {
		return this.templateProductSeq;
	}

	public void setTemplateProductSeq(String templateProductSeq) {
		this.templateProductSeq = templateProductSeq;
	}

	@Column(name = "ad_url", nullable = false, length = 1000)
	public String getAdUrl() {
		return this.adUrl;
	}

	public void setAdUrl(String adUrl) {
		this.adUrl = adUrl;
	}

	@Column(name = "referer", nullable = false, length = 2000)
	public String getReferer() {
		return this.referer;
	}

	public void setReferer(String referer) {
		this.referer = referer;
	}

	@Column(name = "ad_pv", nullable = false)
	public int getAdPv() {
		return this.adPv;
	}

	public void setAdPv(int adPv) {
		this.adPv = adPv;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
