package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpAdPvclkReferer generated by hbm2java
 */
@Entity
@Table(name = "pfp_ad_pvclk_referer")
public class PfpAdPvclkReferer implements java.io.Serializable {

	private Integer adPvclkRefererId;
	private String pfbxCustomerInfoId;
	private Date adPvclkDate;
	private int adPvclkTime;
	private String referer;
	private int adPv;
	private int adClk;
	private float adPvPrice;
	private float adClkPrice;
	private Date updateDate;
	private Date createDate;

	public PfpAdPvclkReferer() {
	}

	public PfpAdPvclkReferer(String pfbxCustomerInfoId, Date adPvclkDate, int adPvclkTime, String referer, int adPv,
			int adClk, float adPvPrice, float adClkPrice, Date updateDate, Date createDate) {
		this.pfbxCustomerInfoId = pfbxCustomerInfoId;
		this.adPvclkDate = adPvclkDate;
		this.adPvclkTime = adPvclkTime;
		this.referer = referer;
		this.adPv = adPv;
		this.adClk = adClk;
		this.adPvPrice = adPvPrice;
		this.adClkPrice = adClkPrice;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ad_pvclk_referer_id", unique = true, nullable = false)
	public Integer getAdPvclkRefererId() {
		return this.adPvclkRefererId;
	}

	public void setAdPvclkRefererId(Integer adPvclkRefererId) {
		this.adPvclkRefererId = adPvclkRefererId;
	}

	@Column(name = "pfbx_customer_info_id", nullable = false, length = 20)
	public String getPfbxCustomerInfoId() {
		return this.pfbxCustomerInfoId;
	}

	public void setPfbxCustomerInfoId(String pfbxCustomerInfoId) {
		this.pfbxCustomerInfoId = pfbxCustomerInfoId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ad_pvclk_date", nullable = false, length = 10)
	public Date getAdPvclkDate() {
		return this.adPvclkDate;
	}

	public void setAdPvclkDate(Date adPvclkDate) {
		this.adPvclkDate = adPvclkDate;
	}

	@Column(name = "ad_pvclk_time", nullable = false)
	public int getAdPvclkTime() {
		return this.adPvclkTime;
	}

	public void setAdPvclkTime(int adPvclkTime) {
		this.adPvclkTime = adPvclkTime;
	}

	@Column(name = "referer", nullable = false, length = 2000)
	public String getReferer() {
		return this.referer;
	}

	public void setReferer(String referer) {
		this.referer = referer;
	}

	@Column(name = "ad_pv", nullable = false)
	public int getAdPv() {
		return this.adPv;
	}

	public void setAdPv(int adPv) {
		this.adPv = adPv;
	}

	@Column(name = "ad_clk", nullable = false)
	public int getAdClk() {
		return this.adClk;
	}

	public void setAdClk(int adClk) {
		this.adClk = adClk;
	}

	@Column(name = "ad_pv_price", nullable = false, precision = 10)
	public float getAdPvPrice() {
		return this.adPvPrice;
	}

	public void setAdPvPrice(float adPvPrice) {
		this.adPvPrice = adPvPrice;
	}

	@Column(name = "ad_clk_price", nullable = false, precision = 10)
	public float getAdClkPrice() {
		return this.adClkPrice;
	}

	public void setAdClkPrice(float adClkPrice) {
		this.adClkPrice = adClkPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
