package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpAdCategoryMapping generated by hbm2java
 */
@Entity
@Table(name = "pfp_ad_category_mapping")
public class PfpAdCategoryMapping implements java.io.Serializable {

	private String adSeq;
	private String code;
	private Date updateDate;
	private Date createDate;

	public PfpAdCategoryMapping() {
	}

	public PfpAdCategoryMapping(String adSeq, String code, Date updateDate, Date createDate) {
		this.adSeq = adSeq;
		this.code = code;
		this.updateDate = updateDate;
		this.createDate = createDate;
	}

	@Id

	@Column(name = "ad_seq", unique = true, nullable = false, length = 20)
	public String getAdSeq() {
		return this.adSeq;
	}

	public void setAdSeq(String adSeq) {
		this.adSeq = adSeq;
	}

	@Column(name = "code", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
