package com.pchome.akbadm.db.pojo;

// Generated 2018/10/22 下午 04:50:20 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpCodeTracking generated by hbm2java
 */
@Entity
@Table(name = "pfp_code_tracking")
public class PfpCodeTracking implements java.io.Serializable {

    private String trackingSeq;
    private PfpCode pfpCode;
    private PfpCustomerInfo pfpCustomerInfo;
    private String trackingName;
    private int trackingRangeDate;
    private Date updateDate;
    private Date createDate;

    public PfpCodeTracking() {
    }

    public PfpCodeTracking(String trackingSeq, PfpCode pfpCode,
            PfpCustomerInfo pfpCustomerInfo, String trackingName,
            int trackingRangeDate, Date updateDate, Date createDate) {
        this.trackingSeq = trackingSeq;
        this.pfpCode = pfpCode;
        this.pfpCustomerInfo = pfpCustomerInfo;
        this.trackingName = trackingName;
        this.trackingRangeDate = trackingRangeDate;
        this.updateDate = updateDate;
        this.createDate = createDate;
    }

    @Id
    @Column(name = "tracking_seq", unique = true, nullable = false, length = 20)
    public String getTrackingSeq() {
        return this.trackingSeq;
    }

    public void setTrackingSeq(String trackingSeq) {
        this.trackingSeq = trackingSeq;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pa_id", nullable = false)
    public PfpCode getPfpCode() {
        return this.pfpCode;
    }

    public void setPfpCode(PfpCode pfpCode) {
        this.pfpCode = pfpCode;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pfp_customer_info_id", nullable = false)
    public PfpCustomerInfo getPfpCustomerInfo() {
        return this.pfpCustomerInfo;
    }

    public void setPfpCustomerInfo(PfpCustomerInfo pfpCustomerInfo) {
        this.pfpCustomerInfo = pfpCustomerInfo;
    }

    @Column(name = "tracking_name", nullable = false, length = 20)
    public String getTrackingName() {
        return this.trackingName;
    }

    public void setTrackingName(String trackingName) {
        this.trackingName = trackingName;
    }

    @Column(name = "tracking_range_date", nullable = false)
    public int getTrackingRangeDate() {
        return this.trackingRangeDate;
    }

    public void setTrackingRangeDate(int trackingRangeDate) {
        this.trackingRangeDate = trackingRangeDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_date", nullable = false, length = 19)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", nullable = false, length = 19)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

}
