package com.pchome.akbadm.db.pojo;

// Generated 2019/1/3 下午 05:25:20 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpCodeAdactionMerge generated by hbm2java
 */
@Entity
@Table(name = "pfp_code_adaction_merge")
public class PfpCodeAdactionMerge implements java.io.Serializable {

    private Integer id;
    private String adActionSeq;
    private String codeType;
    private String codeId;
    private Date updateDate;
    private Date createDate;

    public PfpCodeAdactionMerge() {
    }

    public PfpCodeAdactionMerge(String adActionSeq, String codeType,
            String codeId, Date updateDate, Date createDate) {
        this.adActionSeq = adActionSeq;
        this.codeType = codeType;
        this.codeId = codeId;
        this.updateDate = updateDate;
        this.createDate = createDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "ad_action_seq", nullable = false, length = 20)
    public String getAdActionSeq() {
        return this.adActionSeq;
    }

    public void setAdActionSeq(String adActionSeq) {
        this.adActionSeq = adActionSeq;
    }

    @Column(name = "code_type", nullable = false, length = 1)
    public String getCodeType() {
        return this.codeType;
    }

    public void setCodeType(String codeType) {
        this.codeType = codeType;
    }

    @Column(name = "code_id", nullable = false, length = 20)
    public String getCodeId() {
        return this.codeId;
    }

    public void setCodeId(String codeId) {
        this.codeId = codeId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_date", nullable = false, length = 19)
    public Date getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_date", nullable = false, length = 19)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

}
