package com.pchome.akbadm.db.pojo;
// Generated 2018/7/30 �U�� 06:36:43 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PfpRefundOrderRelease generated by hbm2java
 */
@Entity
@Table(name = "pfp_refund_order_release")
public class PfpRefundOrderRelease implements java.io.Serializable {

	private Integer seq;
	private PfpRefundOrder pfpRefundOrder;
	private String payType;
	private String status;
	private Date applyTime;
	private Date checkTime;
	private String checkUser;
	private float refundPriceTax;
	private String rejectReason;
	private Date createDate;
	private Date updateDate;

	public PfpRefundOrderRelease() {
	}

	public PfpRefundOrderRelease(PfpRefundOrder pfpRefundOrder, String payType, String status, Date applyTime,
			float refundPriceTax, Date createDate, Date updateDate) {
		this.pfpRefundOrder = pfpRefundOrder;
		this.payType = payType;
		this.status = status;
		this.applyTime = applyTime;
		this.refundPriceTax = refundPriceTax;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public PfpRefundOrderRelease(PfpRefundOrder pfpRefundOrder, String payType, String status, Date applyTime,
			Date checkTime, String checkUser, float refundPriceTax, String rejectReason, Date createDate,
			Date updateDate) {
		this.pfpRefundOrder = pfpRefundOrder;
		this.payType = payType;
		this.status = status;
		this.applyTime = applyTime;
		this.checkTime = checkTime;
		this.checkUser = checkUser;
		this.refundPriceTax = refundPriceTax;
		this.rejectReason = rejectReason;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "seq", unique = true, nullable = false)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "refund_order_id", nullable = false)
	public PfpRefundOrder getPfpRefundOrder() {
		return this.pfpRefundOrder;
	}

	public void setPfpRefundOrder(PfpRefundOrder pfpRefundOrder) {
		this.pfpRefundOrder = pfpRefundOrder;
	}

	@Column(name = "pay_type", nullable = false, length = 1)
	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "apply_time", nullable = false, length = 19)
	public Date getApplyTime() {
		return this.applyTime;
	}

	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "check_time", length = 19)
	public Date getCheckTime() {
		return this.checkTime;
	}

	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}

	@Column(name = "check_user", length = 50)
	public String getCheckUser() {
		return this.checkUser;
	}

	public void setCheckUser(String checkUser) {
		this.checkUser = checkUser;
	}

	@Column(name = "refund_price_tax", nullable = false, precision = 10)
	public float getRefundPriceTax() {
		return this.refundPriceTax;
	}

	public void setRefundPriceTax(float refundPriceTax) {
		this.refundPriceTax = refundPriceTax;
	}

	@Column(name = "reject_reason", length = 50)
	public String getRejectReason() {
		return this.rejectReason;
	}

	public void setRejectReason(String rejectReason) {
		this.rejectReason = rejectReason;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
