package com.pchome.enumerate.ad;

public enum EnumIndexField {
    PK,
    AD_ACTION_ID,
    AD_GROUP_ID,
    AD_ID,
    AD_KEYWORD_ID,
    AD_KEYWORD,
    AD_EXCLUDE_KEYWORD,
    AD_ACTION_CONTROL_PRICE,
    AD_KEYWORD_SEARCH_PRICE,
    AD_KEYWORD_SEARCH_PHRASE_PRICE,
    AD_KEYWORD_SEARCH_PRECISION_PRICE,
    AD_KEYWORD_CHANNEL_PRICE,
    AD_KEYWORD_TEMP_PRICE,
    AD_KEYWORD_OPEN,
    AD_KEYWORD_PHRASE_OPEN,
    AD_KEYWORD_PRECISION_OPEN,
    AD_KEYWORD_PV,
    AD_KEYWORD_CLK,
    RECOGNIZE,
    UPDATE_DATE,
    CREATE_DATE;
}
